project_id = "qwhunliohlkkahbspfiu"

[functions.send-account-invitation]
verify_jwt = false

[functions.process-monthly-depreciation]
verify_jwt = false

[functions.refresh-stats-cache]
verify_jwt = false