project_id = "qwhunliohlkkahbspfiu"

[functions.set-browsed-company]
verify_jwt = true

[functions.send-account-invitation]
verify_jwt = true

[functions.process-monthly-depreciation]
verify_jwt = true

[functions.refresh-stats-cache]
verify_jwt = true

[functions.quotation-approval]
verify_jwt = true

[functions.legal-ai-api]
verify_jwt = true

[functions.legal-ai-enhanced]
verify_jwt = true

[functions.self-learning-ai]
verify_jwt = true

[functions.intelligent-clarification]
verify_jwt = true

[functions.clarification-learning]
verify_jwt = true

[functions.ai-self-evaluation]
verify_jwt = true

[functions.openai-chat]
verify_jwt = true

[functions.transfer-user-company]
verify_jwt = true

[functions.sync-document-alerts]
verify_jwt = true

[functions.extract-traffic-violations]
verify_jwt = true