project_id = "qwhunliohlkkahbspfiu"

[functions.send-account-invitation]
verify_jwt = false

[functions.process-monthly-depreciation]
verify_jwt = false

[functions.refresh-stats-cache]
verify_jwt = false

[functions.quotation-approval]
verify_jwt = false

[functions.legal-ai-api]
verify_jwt = false

[functions.legal-ai-enhanced]
verify_jwt = false