#!/usr/bin/env python3
"""
Generate SQL to import vehicle data from agreements_with_details.sql
to contracts table in Al-Arraf company
"""

import re

# Read the agreements_with_details.sql file
with open('.qoder/agreements_with_details.sql', 'r', encoding='utf-8') as f:
    content = f.read()

# Extract all INSERT statements
insert_pattern = r"INSERT INTO agreements_with_details VALUES \('([^']+)', '([^']*)', '([^']*)', '([^']*)', '([^']*)', ([^,]+), '([^']*)', '([^']*)', '([^']*)', '([^']*)', '([^']*)', ([^,]+), '([^']*)', '([^']*)', ([^,]*), ([^,]+), '([^']*)', ([^,]+), ([^,]+), '([^']*)', '([^']*)', ([^,]+), '([^']*)', ([^,]+), ([^,]+), ([^,]+), ([^,]+), '([^']*)', ([^)]+)\);"

matches = re.findall(insert_pattern, content)

print("-- ================================================================")
print("-- AUTO-GENERATED: Import Vehicle Data to Contracts")
print("-- ================================================================")
print(f"-- Total records found: {len(matches)}")
print("-- Generated by: generate_import_sql.py")
print("-- ================================================================")
print()

print("DO $$")
print("DECLARE")
print("  v_company_id UUID := '24bc0b21-4e2d-4413-9842-31719a3669f4';")
print("  v_updated INTEGER := 0;")
print("  v_total_updated INTEGER := 0;")
print("BEGIN")
print("  RAISE NOTICE '';")
print("  RAISE NOTICE '====================================================================';")
print("  RAISE NOTICE '🚗 IMPORTING VEHICLE DATA FROM AGREEMENTS FILE';")
print("  RAISE NOTICE '====================================================================';")
print(f"  RAISE NOTICE 'Total records to process: {len(matches)}';")
print("  RAISE NOTICE '';")
print()

# Generate UPDATE statements for each record
for idx, match in enumerate(matches, 1):
    uuid = match[0]
    agreement_number = match[1]
    license_plate = match[8]  # Column 10 in the INSERT
    make = match[9]           # Column 11
    model = match[10]         # Column 12
    year = match[11]          # Column 13
    
    # Only update if we have vehicle data
    if license_plate and license_plate.strip():
        print(f"  -- Record {idx}/{len(matches)}: {agreement_number} ({license_plate})")
        print(f"  UPDATE contracts")
        print(f"  SET ")
        print(f"    license_plate = '{license_plate}',")
        print(f"    make = '{make}',")
        print(f"    model = '{model}',")
        print(f"    year = {year},")
        print(f"    updated_at = NOW()")
        print(f"  WHERE id = '{uuid}'")
        print(f"    AND company_id = v_company_id")
        print(f"    AND (license_plate IS NULL OR TRIM(license_plate) = '');")
        print()
        print(f"  GET DIAGNOSTICS v_updated = ROW_COUNT;")
        print(f"  v_total_updated := v_total_updated + v_updated;")
        print()
        
        # Progress notification every 50 records
        if idx % 50 == 0:
            print(f"  RAISE NOTICE '   Progress: {idx}/{len(matches)} processed...';")
            print()

print("  RAISE NOTICE '';")
print("  RAISE NOTICE '====================================================================';")
print("  RAISE NOTICE '✅ IMPORT COMPLETED!';")
print("  RAISE NOTICE '====================================================================';")
print("  RAISE NOTICE 'Total contracts updated: %', v_total_updated;")
print("  RAISE NOTICE '';")
print("  RAISE NOTICE '🎯 NEXT STEP:';")
print("  RAISE NOTICE 'Run complete_alaraf_vehicle_sync.sql to link vehicles!';")
print("  RAISE NOTICE '====================================================================';")
print("  RAISE NOTICE '';")
print("END $$;")
print()

print("-- ================================================================")
print("-- Verification Query")
print("-- ================================================================")
print("SELECT ")
print("  '✅ Contracts with vehicle data after import' as status,")
print("  COUNT(*) as total")
print("FROM contracts")
print("WHERE company_id = '24bc0b21-4e2d-4413-9842-31719a3669f4'")
print("  AND license_plate IS NOT NULL")
print("  AND TRIM(license_plate) != '';")

print()
print("-- Show sample")
print("SELECT ")
print("  '📋 Sample Contracts' as section,")
print("  contract_number,")
print("  license_plate,")
print("  make,")
print("  model,")
print("  year")
print("FROM contracts")
print("WHERE company_id = '24bc0b21-4e2d-4413-9842-31719a3669f4'")
print("  AND license_plate IS NOT NULL")
print("ORDER BY created_at DESC")
print("LIMIT 10;")

