-- Shared fail-closed safety kernel for Fleetify's autonomous agents.
-- This migration governs machine invocation, conflict windows, direct evidence
-- ownership and signed-contract identity transitions. It does not enable a new
-- writer or change an existing schedule.

BEGIN;

CREATE TABLE public.agent_safety_policies (
  agent_id text PRIMARY KEY,
  schedule_name text NULL UNIQUE,
  display_name text NOT NULL,
  execution_mode text NOT NULL
    CHECK (execution_mode IN ('observe', 'propose', 'auto_apply')),
  risk_level text NOT NULL
    CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
  conflict_group text NOT NULL,
  max_runtime_seconds integer NOT NULL DEFAULT 600
    CHECK (max_runtime_seconds BETWEEN 10 AND 3600),
  minimum_confidence numeric NOT NULL DEFAULT 1
    CHECK (minimum_confidence BETWEEN 0 AND 1),
  requires_direct_entity_link boolean NOT NULL DEFAULT true,
  allows_cross_entity_evidence boolean NOT NULL DEFAULT false,
  evidence_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.agent_invocation_leases (
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  conflict_group text NOT NULL,
  agent_id text NOT NULL REFERENCES public.agent_safety_policies(agent_id) ON DELETE RESTRICT,
  request_id text NOT NULL,
  acquired_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (company_id, conflict_group)
);

CREATE INDEX agent_invocation_leases_expiry_idx
  ON public.agent_invocation_leases(expires_at);

CREATE TABLE public.agent_safety_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id uuid NULL REFERENCES public.companies(id) ON DELETE SET NULL,
  agent_id text NOT NULL REFERENCES public.agent_safety_policies(agent_id) ON DELETE RESTRICT,
  request_id text NULL,
  operation text NOT NULL,
  entity_type text NULL,
  entity_id text NULL,
  outcome text NOT NULL
    CHECK (outcome IN ('allowed', 'blocked', 'busy', 'duplicate', 'succeeded', 'failed', 'timed_out')),
  reason_code text NOT NULL,
  confidence numeric NULL CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX agent_safety_events_agent_time_idx
  ON public.agent_safety_events(agent_id, created_at DESC);
CREATE INDEX agent_safety_events_company_outcome_idx
  ON public.agent_safety_events(company_id, outcome, created_at DESC);

ALTER TABLE public.agent_safety_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_invocation_leases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_safety_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
  public.agent_safety_policies,
  public.agent_invocation_leases,
  public.agent_safety_events
FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.agent_safety_policies TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.agent_invocation_leases TO service_role;
GRANT SELECT, INSERT ON TABLE public.agent_safety_events TO service_role;

INSERT INTO public.agent_safety_policies (
  agent_id,
  schedule_name,
  display_name,
  execution_mode,
  risk_level,
  conflict_group,
  max_runtime_seconds,
  minimum_confidence,
  requires_direct_entity_link,
  allows_cross_entity_evidence,
  evidence_policy
)
VALUES
  ('system-audit-orchestrator', 'system-audit-orchestrator-v14', 'منسق تدقيق النظام', 'auto_apply', 'critical', 'system_mutation', 900, 0.95, true, false, '{"repair_allowlist":true,"postconditions":true}'),
  ('system-audit-review-task-sync', 'system-audit-review-task-sync-v1', 'مزامن مراجعات التدقيق', 'auto_apply', 'medium', 'review_lifecycle', 300, 1, true, false, '{"close_only_grace_snapshots":2}'),
  ('agent-operational-alerts', 'agent-operational-alerts-v1', 'تنبيهات تشغيل الوكلاء', 'auto_apply', 'low', 'agent_observability', 120, 1, true, false, '{"dedupe_required":true}'),
  ('violation-inbox-processor', 'violation-inbox-processor', 'معالج مخالفات الصندوق', 'auto_apply', 'high', 'traffic_ingest', 600, 0.95, true, false, '{"required_keys":["source_message_id","normalized_plate"]}'),
  ('traffic-mail-ingest', 'traffic-mail-ingest-v1', 'مزامن بريد المخالفات', 'auto_apply', 'high', 'traffic_ingest', 600, 0.95, true, false, '{"required_keys":["source_message_id","content_hash"],"company_scope_required":true,"ambiguous_vehicle_or_contract":"review"}'),
  ('nightly-ops-auditor', 'nightly-ops-auditor', 'مدقق العمليات الليلي', 'propose', 'medium', 'system_observation', 600, 0.9, true, false, '{"read_before_write":true}'),
  ('smart-contract-assigner', 'smart-contract-assigner', 'موزع العقود الذكي', 'auto_apply', 'high', 'contract_assignment', 600, 1, true, false, '{"direct_contract_vehicle_link":true}'),
  ('customer-duplicate-detector', 'customer-duplicate-detector', 'كاشف تكرار العملاء', 'auto_apply', 'high', 'customer_identity', 600, 0.95, true, false, '{"national_id_exact_or_review":true,"atomic_apply_rpc":true}'),
  ('customer-proposal-ai-reviewer', 'customer-proposal-ai-reviewer', 'مراجع مقترحات هوية العميل', 'auto_apply', 'high', 'customer_identity', 600, 0.95, true, false, '{"source_document_required":true,"atomic_apply_rpc":true}'),
  ('contract-id-scanner', 'contract-id-scanner', 'ماسح هوية العقد', 'propose', 'critical', 'contract_identity', 600, 1, true, false, '{"exact_identity_for_match":true}'),
  ('contract-terms-scanner', 'nightly-contract-terms-scan', 'ماسح شروط العقد', 'auto_apply', 'high', 'contract_terms', 900, 0.95, true, false, '{"identity_matched_document":true,"financial_ambiguity_blocks_apply":true}'),
  ('legal-notice-agent', 'automatic-formal-notice-agent', 'وكيل الإعذار التلقائي', 'auto_apply', 'critical', 'legal_external_delivery', 300, 1, true, false, '{"live_balance_required":true,"delivery_proof_required":true}'),
  ('missing-contract-pdf-agent', 'missing-contract-pdf-agent', 'وكيل طلب نسخة العقد', 'auto_apply', 'high', 'legal_external_delivery', 45, 1, true, false, '{"direct_contract_check":true,"dedupe_required":true}'),
  ('taqadi-filing-agent', NULL, 'وكيل رفع الدعوى في تقاضي', 'auto_apply', 'critical', 'legal_filing', 1800, 1, true, false, '{"matched_contract_identity":true,"server_approval":true,"final_receipt_required":true}'),
  ('legal-case-ai-reviewer', NULL, 'مراجع القضية القانونية', 'propose', 'critical', 'legal_readiness', 600, 1, true, false, '{"matched_contract_identity":true,"live_finance":true}'),
  ('payment-match-agent', NULL, 'وكيل مطابقة الدفعات', 'propose', 'critical', 'financial_binding', 600, 1, true, false, '{"same_company_customer_contract":true}'),
  ('collection-message-agent', NULL, 'وكيل اقتراح رسالة التحصيل', 'propose', 'high', 'collection_advice', 120, 1, true, false, '{"live_balance_required":true,"draft_only":true}'),
  ('correction-verifier-agent', NULL, 'وكيل تدقيق تصحيحات الموظف', 'propose', 'high', 'customer_identity', 120, 1, true, false, '{"source_evidence_required":true,"no_auto_apply":true}'),
  ('customer-id-autofill-agent', NULL, 'وكيل استخراج هوية العميل', 'propose', 'critical', 'customer_identity', 120, 1, true, false, '{"company_scope_required":true,"no_guessing":true}'),
  ('daily-closeout-ai-reviewer', NULL, 'مراجع الإغلاق اليومي', 'propose', 'medium', 'review_lifecycle', 300, 1, true, false, '{"company_scope_required":true,"review_only":true}'),
  ('journal-entry-ai-reviewer', NULL, 'مراجع القيود المحاسبية', 'propose', 'critical', 'financial_review', 300, 1, true, false, '{"balanced_entry_required":true,"review_only":true}'),
  ('intelligent-contract-processor', NULL, 'معالج بيانات العقد', 'propose', 'high', 'contract_identity', 120, 1, true, false, '{"company_scope_required":true,"ambiguous_values_rejected":true}'),
  ('excel-import-ai-reviewer', NULL, 'مراجع استيراد إكسل', 'propose', 'high', 'financial_review', 600, 1, true, false, '{"company_scope_required":true,"staging_only":true,"duplicate_hash_required":true}'),
  ('historical-invoice-backfill', NULL, 'وكيل استكمال الفواتير التاريخية', 'auto_apply', 'critical', 'financial_reconciliation', 1800, 1, true, false, '{"dry_run_default":true,"privileged_actor_required":true,"company_scope_required":true,"bounded_contract_page":200}'),
  ('monthly-contract-invoice-reconciliation', 'monthly-contract-invoice-reconciliation', 'مصالحة فواتير العقود', 'auto_apply', 'critical', 'financial_reconciliation', 900, 1, true, false, '{"balanced_journal":true,"live_allocations":true}'),
  ('generate-monthly-invoices', 'generate-monthly-invoices', 'مولد الفواتير الشهري', 'auto_apply', 'critical', 'financial_reconciliation', 900, 1, true, false, '{"prepaid_due_date":true,"idempotent_month":true,"company_scope_required":true}'),
  ('monthly-vehicle-depreciation', 'monthly-vehicle-depreciation', 'وكيل إهلاك المركبات الشهري', 'auto_apply', 'critical', 'financial_posting', 900, 1, true, false, '{"first_of_month_required":true,"closed_period_block":true,"balanced_journal":true,"idempotent_vehicle_month":true,"company_scope_required":true}'),
  ('payment-reminder-agent', 'process-payment-reminders', 'وكيل تذكيرات الدفع', 'auto_apply', 'high', 'collection_external_delivery', 900, 1, true, false, '{"delivery_claim_required":true,"company_scope_required":true}'),
  ('legal-judgment-payment-matcher', 'legal-judgment-payment-matcher-hourly', 'مطابق سداد الأحكام', 'propose', 'critical', 'financial_binding', 600, 1, true, false, '{"same_case_contract":true}'),
  ('daily-contract-health-guard', 'daily-contract-health-guard-v1', 'حارس صحة العقود', 'propose', 'high', 'contract_health', 600, 0.95, true, false, '{"no_cross_contract_copy":true}'),
  ('daily-legal-workflow-guard', 'daily-legal-workflow-guard-v1', 'حارس سير العمل القانوني', 'propose', 'critical', 'legal_readiness', 600, 1, true, false, '{"case_contract_customer_match":true}'),
  ('update-delinquent-customers', 'update-delinquent-customers', 'محدث المتعثرين', 'auto_apply', 'critical', 'financial_reconciliation', 600, 1, true, false, '{"live_ledger_source":true}'),
  ('close-stale-system-audit-reviews', NULL, 'مصرف المراجعات القديمة', 'auto_apply', 'medium', 'review_lifecycle', 300, 1, true, false, '{"creates_findings":false,"creates_tasks":false}')
  ,('safe-auto-repair', NULL, 'وكيل الإصلاح القديم المتقاعد', 'propose', 'critical', 'system_mutation', 900, 1, true, false, '{"retired":true,"replacement":"system-audit-orchestrator"}')
  ,('daily-audit-agent', NULL, 'وكيل التدقيق اليومي القديم', 'propose', 'critical', 'system_mutation', 900, 1, true, false, '{"retired":true,"replacement":"system-audit-orchestrator","dry_run_only":true}')
  ,('legacy-legal-case-trigger', NULL, 'منشئ القضايا القديم', 'propose', 'critical', 'legal_filing', 300, 1, true, false, '{"retired":true,"replacement":"legal-notice-agent + taqadi-filing-agent"}')
  ,('legacy-daily-report-agent', NULL, 'مرسل التقرير اليومي القديم', 'propose', 'high', 'report_external_delivery', 300, 1, true, false, '{"retired":true,"credential_rotation_required":true}')
  ,('legacy-weekly-report-agent', NULL, 'مرسل التقرير الأسبوعي القديم', 'propose', 'high', 'report_external_delivery', 300, 1, true, false, '{"retired":true,"credential_rotation_required":true}')
  ,('legacy-traffic-fine-webhook', NULL, 'معالج المخالفة القديم', 'propose', 'critical', 'traffic_ingest', 300, 1, true, false, '{"retired":true,"replacement":"traffic-mail-ingest + violation-inbox-processor"}')
  ,('legacy-monitoring-collector', NULL, 'جامع المراقبة القديم', 'propose', 'high', 'agent_observability', 300, 1, true, false, '{"retired":true,"replacement":"signed api-monitoring-webhook"}')
  ,('legacy-whatsapp-document-sender', NULL, 'مرسل مستندات واتساب القديم', 'propose', 'critical', 'external_document_delivery', 300, 1, true, false, '{"retired":true,"reason":"public_pdf_and_embedded_provider_credentials"}')
  ,('legacy-public-legal-document-upload', NULL, 'رافع المستند القانوني العام القديم', 'propose', 'critical', 'legal_evidence', 300, 1, true, false, '{"retired":true,"reason":"unscoped_service_role_public_upload"}')
ON CONFLICT (agent_id) DO UPDATE
SET schedule_name = EXCLUDED.schedule_name,
    display_name = EXCLUDED.display_name,
    execution_mode = EXCLUDED.execution_mode,
    risk_level = EXCLUDED.risk_level,
    conflict_group = EXCLUDED.conflict_group,
    max_runtime_seconds = EXCLUDED.max_runtime_seconds,
    minimum_confidence = EXCLUDED.minimum_confidence,
    requires_direct_entity_link = EXCLUDED.requires_direct_entity_link,
    allows_cross_entity_evidence = EXCLUDED.allows_cross_entity_evidence,
    evidence_policy = EXCLUDED.evidence_policy,
    enabled = true,
    updated_at = now();

UPDATE public.agent_safety_policies
SET enabled = false,
    updated_at = now()
WHERE agent_id IN (
  'safe-auto-repair',
  'daily-audit-agent',
  'legacy-legal-case-trigger',
    'legacy-daily-report-agent',
    'legacy-weekly-report-agent',
    'legacy-traffic-fine-webhook',
    'legacy-monitoring-collector',
    'legacy-whatsapp-document-sender',
    'legacy-public-legal-document-upload'
  );

CREATE OR REPLACE FUNCTION public.verify_scheduled_agent_invocation_v2(
  p_agent_id text,
  p_company_id uuid,
  p_supplied_secret text,
  p_request_id text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_policy public.agent_safety_policies%ROWTYPE;
  v_request_id text := NULLIF(pg_catalog.left(COALESCE(p_request_id, ''), 200), '');
  v_claimed boolean := false;
BEGIN
  IF NOT public.verify_scheduled_agent_invocation_v1(
    p_agent_id,
    p_company_id,
    p_supplied_secret,
    v_request_id
  ) THEN
    RETURN false;
  END IF;

  SELECT policy.*
  INTO v_policy
  FROM public.agent_safety_policies policy
  WHERE policy.agent_id = p_agent_id
    AND policy.enabled = true;

  IF v_policy.agent_id IS NULL OR p_company_id IS NULL OR v_request_id IS NULL THEN
    RETURN false;
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'agent-invocation:' || p_company_id::text || ':' || v_policy.conflict_group,
      0
    )
  );

  IF EXISTS (
    SELECT 1
    FROM public.agent_safety_events event
    WHERE event.company_id = p_company_id
      AND event.agent_id = p_agent_id
      AND event.request_id = v_request_id
      AND event.operation = 'scheduled_invocation'
      AND event.outcome = 'allowed'
  ) THEN
    INSERT INTO public.agent_safety_events (
      company_id,
      agent_id,
      request_id,
      operation,
      outcome,
      reason_code,
      confidence,
      evidence
    ) VALUES (
      p_company_id,
      p_agent_id,
      v_request_id,
      'scheduled_invocation',
      'duplicate',
      'request_id_already_allowed',
      1,
      jsonb_build_object('conflict_group', v_policy.conflict_group)
    );
    RETURN false;
  END IF;

  DELETE FROM public.agent_invocation_leases lease
  WHERE lease.company_id = p_company_id
    AND lease.conflict_group = v_policy.conflict_group
    AND lease.expires_at <= now();

  INSERT INTO public.agent_invocation_leases (
    company_id,
    conflict_group,
    agent_id,
    request_id,
    expires_at
  ) VALUES (
    p_company_id,
    v_policy.conflict_group,
    p_agent_id,
    v_request_id,
    now() + pg_catalog.make_interval(secs => v_policy.max_runtime_seconds)
  )
  ON CONFLICT (company_id, conflict_group) DO UPDATE
  SET agent_id = EXCLUDED.agent_id,
      request_id = EXCLUDED.request_id,
      acquired_at = now(),
      expires_at = EXCLUDED.expires_at
  WHERE public.agent_invocation_leases.request_id = EXCLUDED.request_id
  RETURNING true INTO v_claimed;

  INSERT INTO public.agent_safety_events (
    company_id,
    agent_id,
    request_id,
    operation,
    outcome,
    reason_code,
    confidence,
    evidence
  ) VALUES (
    p_company_id,
    p_agent_id,
    v_request_id,
    'scheduled_invocation',
    CASE WHEN v_claimed THEN 'allowed' ELSE 'busy' END,
    CASE WHEN v_claimed THEN 'machine_identity_and_policy_valid' ELSE 'conflict_group_lease_active' END,
    1,
    jsonb_build_object('conflict_group', v_policy.conflict_group)
  );

  RETURN v_claimed;
END;
$function$;

REVOKE ALL ON FUNCTION public.verify_scheduled_agent_invocation_v2(text,uuid,text,text)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_scheduled_agent_invocation_v2(text,uuid,text,text)
TO service_role;

CREATE OR REPLACE FUNCTION public.normalize_legal_party_name_v1(p_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path TO ''
AS $function$
  SELECT pg_catalog.regexp_replace(
    pg_catalog.translate(
      pg_catalog.regexp_replace(
        pg_catalog.lower(COALESCE(p_value, '')),
        '[ًٌٍَُِّْٰـ]',
        '',
        'g'
      ),
      'أإآٱىةؤئ',
      'اااايهوي'
    ),
    '[^ء-يa-z0-9]+',
    '',
    'g'
  );
$function$;

CREATE OR REPLACE FUNCTION public.guard_signed_contract_evidence_integrity_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
DECLARE
  v_customer public.customers%ROWTYPE;
  v_expected_name text;
  v_extracted_name text;
  v_customer_name_ar text;
  v_customer_name_en text;
  v_customer_company_name_ar text;
  v_customer_company_name_en text;
  v_expected_id text;
  v_extracted_id text;
  v_customer_id text;
BEGIN
  IF TG_OP = 'UPDATE'
     AND OLD.document_type IN ('signed_contract', 'signed_contract_image')
     AND (
       OLD.company_id IS DISTINCT FROM NEW.company_id
       OR OLD.contract_id IS DISTINCT FROM NEW.contract_id
       OR OLD.file_path IS DISTINCT FROM NEW.file_path
       OR OLD.document_type IS DISTINCT FROM NEW.document_type
     ) THEN
    RAISE EXCEPTION 'SIGNED_CONTRACT_EVIDENCE_IMMUTABLE: upload a new evidence row and verify it independently'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.document_type NOT IN ('signed_contract', 'signed_contract_image') THEN
    RETURN NEW;
  END IF;

  IF NULLIF(BTRIM(NEW.file_path), '') IS NOT NULL AND EXISTS (
    SELECT 1
    FROM public.contract_documents other
    WHERE other.company_id = NEW.company_id
      AND other.id IS DISTINCT FROM NEW.id
      AND other.file_path = NEW.file_path
      AND other.document_type IN ('signed_contract', 'signed_contract_image')
      AND other.contract_id IS DISTINCT FROM NEW.contract_id
  ) THEN
    RAISE EXCEPTION 'SIGNED_CONTRACT_FILE_REUSED_ACROSS_CONTRACTS'
      USING ERRCODE = '23505';
  END IF;

  IF NEW.legal_identity_match_status <> 'matched'
     OR (
       TG_OP = 'UPDATE'
       AND OLD.legal_identity_match_status = 'matched'
       AND OLD.legal_identity_expected_name IS NOT DISTINCT FROM NEW.legal_identity_expected_name
       AND OLD.legal_identity_extracted_name IS NOT DISTINCT FROM NEW.legal_identity_extracted_name
       AND OLD.legal_identity_expected_id IS NOT DISTINCT FROM NEW.legal_identity_expected_id
       AND OLD.legal_identity_extracted_id IS NOT DISTINCT FROM NEW.legal_identity_extracted_id
     ) THEN
    RETURN NEW;
  END IF;

  IF NEW.contract_id IS NULL
     OR NULLIF(BTRIM(NEW.file_path), '') IS NULL
     OR NEW.legal_identity_checked_at IS NULL THEN
    RAISE EXCEPTION 'SIGNED_CONTRACT_MATCH_REQUIRES_DIRECT_FILE_AND_CHECK_TIMESTAMP'
      USING ERRCODE = '23514';
  END IF;

  SELECT customer.*
  INTO v_customer
  FROM public.contracts contract
  JOIN public.customers customer
    ON customer.id = contract.customer_id
   AND customer.company_id = contract.company_id
  WHERE contract.id = NEW.contract_id
    AND contract.company_id = NEW.company_id;

  IF v_customer.id IS NULL THEN
    RAISE EXCEPTION 'SIGNED_CONTRACT_CUSTOMER_NOT_FOUND'
      USING ERRCODE = '23503';
  END IF;

  v_expected_name := public.normalize_legal_party_name_v1(NEW.legal_identity_expected_name);
  v_extracted_name := public.normalize_legal_party_name_v1(NEW.legal_identity_extracted_name);
  v_customer_name_ar := public.normalize_legal_party_name_v1(
    concat_ws(' ', v_customer.first_name_ar, v_customer.last_name_ar)
  );
  v_customer_name_en := public.normalize_legal_party_name_v1(
    concat_ws(' ', v_customer.first_name, v_customer.last_name)
  );
  v_customer_company_name_ar := public.normalize_legal_party_name_v1(
    v_customer.company_name_ar
  );
  v_customer_company_name_en := public.normalize_legal_party_name_v1(
    v_customer.company_name
  );
  v_expected_id := pg_catalog.regexp_replace(COALESCE(NEW.legal_identity_expected_id, ''), '[^0-9]', '', 'g');
  v_extracted_id := pg_catalog.regexp_replace(COALESCE(NEW.legal_identity_extracted_id, ''), '[^0-9]', '', 'g');
  v_customer_id := pg_catalog.regexp_replace(COALESCE(v_customer.national_id, ''), '[^0-9]', '', 'g');

  IF NOT (
    (
      v_expected_id <> ''
      AND v_expected_id = v_extracted_id
      AND v_customer_id <> ''
      AND v_expected_id = v_customer_id
    )
    OR
    (
      v_expected_name <> ''
      AND v_expected_name = v_extracted_name
      AND (
        v_expected_name = v_customer_name_ar
        OR v_expected_name = v_customer_name_en
        OR v_expected_name = v_customer_company_name_ar
        OR v_expected_name = v_customer_company_name_en
      )
    )
  ) THEN
    RAISE EXCEPTION 'SIGNED_CONTRACT_IDENTITY_NOT_EXACT'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_00_guard_signed_contract_binding_v1
ON public.contract_documents;
CREATE TRIGGER trg_00_guard_signed_contract_binding_v1
BEFORE INSERT OR UPDATE OF company_id, contract_id, file_path, document_type
ON public.contract_documents
FOR EACH ROW
EXECUTE FUNCTION public.guard_signed_contract_evidence_integrity_v1();

DROP TRIGGER IF EXISTS trg_01_guard_signed_contract_identity_match_v1
ON public.contract_documents;
CREATE TRIGGER trg_01_guard_signed_contract_identity_match_v1
BEFORE INSERT OR UPDATE OF
  legal_identity_match_status,
  legal_identity_expected_name,
  legal_identity_extracted_name,
  legal_identity_expected_id,
  legal_identity_extracted_id,
  legal_identity_checked_at
ON public.contract_documents
FOR EACH ROW
EXECUTE FUNCTION public.guard_signed_contract_evidence_integrity_v1();

REVOKE ALL ON FUNCTION public.normalize_legal_party_name_v1(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.guard_signed_contract_evidence_integrity_v1() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.normalize_legal_party_name_v1(text)
TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.contract_terms_scan_batch_candidates_v4(
  p_company_id uuid,
  p_limit integer DEFAULT 4,
  p_contract_id uuid DEFAULT NULL
)
RETURNS TABLE (
  contract_id uuid,
  company_id uuid,
  document_id uuid,
  contract_number text,
  contract_amount numeric,
  expected_amount numeric,
  trigger_reason text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  WITH candidate AS (
    SELECT
      contract.id AS contract_id,
      contract.company_id,
      document.id AS document_id,
      contract.contract_number,
      contract.contract_amount,
      COALESCE(NULLIF(graph.schedule_total, 0), date_graph.expected_amount) AS expected_amount,
      CASE
        WHEN graph.missing_invoice_count > 0 THEN 'active_schedule_missing_invoice'
        WHEN graph.active_schedule_count > 0 AND graph.active_invoice_count = 0
          THEN 'schedule_graph_without_invoices'
        WHEN failed_repair.has_failed_repair THEN 'audit_repair_requires_document_decision'
        ELSE 'contract_amount_graph_mismatch'
      END AS trigger_reason,
      CASE
        WHEN graph.missing_invoice_count > 0 THEN 1
        WHEN graph.active_schedule_count > 0 AND graph.active_invoice_count = 0 THEN 2
        WHEN failed_repair.has_failed_repair THEN 3
        ELSE 4
      END AS priority_rank,
      contract.updated_at
    FROM public.contracts contract
    JOIN LATERAL (
      SELECT doc.id
      FROM public.contract_documents doc
      WHERE doc.contract_id = contract.id
        AND doc.company_id = contract.company_id
        AND doc.document_type IN ('signed_contract', 'signed_contract_image')
        AND doc.file_path IS NOT NULL
        AND doc.legal_identity_match_status = 'matched'
      ORDER BY doc.created_at DESC, doc.id
      LIMIT 1
    ) document ON true
    CROSS JOIN LATERAL (
      SELECT round(
        contract.monthly_amount * GREATEST(1, (
          (EXTRACT(YEAR FROM date_trunc('month', contract.end_date))
            - EXTRACT(YEAR FROM date_trunc('month', contract.start_date))) * 12
          + EXTRACT(MONTH FROM date_trunc('month', contract.end_date))
          - EXTRACT(MONTH FROM date_trunc('month', contract.start_date))
          + 1
        )::integer),
        2
      ) AS expected_amount
    ) date_graph
    CROSS JOIN LATERAL (
      SELECT
        count(*) FILTER (
          WHERE lower(COALESCE(schedule.status, '')) NOT IN (
            'cancelled', 'canceled', 'void', 'voided', 'deleted', 'inactive'
          )
        )::integer AS active_schedule_count,
        COALESCE(sum(schedule.amount) FILTER (
          WHERE lower(COALESCE(schedule.status, '')) NOT IN (
            'cancelled', 'canceled', 'void', 'voided', 'deleted', 'inactive'
          )
        ), 0)::numeric AS schedule_total,
        count(*) FILTER (
          WHERE lower(COALESCE(schedule.status, '')) NOT IN (
            'cancelled', 'canceled', 'void', 'voided', 'deleted', 'inactive'
          )
            AND schedule.invoice_id IS NULL
        )::integer AS missing_invoice_count,
        (
          SELECT count(*)::integer
          FROM public.invoices invoice
          WHERE invoice.company_id = contract.company_id
            AND invoice.contract_id = contract.id
            AND COALESCE(invoice.total_amount, 0) > 0.01
            AND lower(COALESCE(invoice.status, '')) NOT IN (
              'cancelled', 'canceled', 'void', 'voided', 'deleted', 'inactive'
            )
            AND lower(COALESCE(invoice.payment_status, '')) NOT IN (
              'cancelled', 'canceled', 'void', 'voided', 'deleted', 'inactive'
            )
        ) AS active_invoice_count
      FROM public.contract_payment_schedules schedule
      WHERE schedule.company_id = contract.company_id
        AND schedule.contract_id = contract.id
    ) graph
    CROSS JOIN LATERAL (
      SELECT EXISTS (
        SELECT 1
        FROM public.system_agent_findings finding
        WHERE finding.company_id = contract.company_id
          AND finding.code = 'schedule.missing_invoice'
          AND finding.status = 'failed'
          AND finding.evidence ->> 'contractId' = contract.id::text
      ) AS has_failed_repair
    ) failed_repair
    WHERE contract.company_id = p_company_id
      AND (p_contract_id IS NULL OR contract.id = p_contract_id)
      AND contract.status IN ('active', 'under_legal_procedure')
      AND COALESCE(contract.monthly_amount, 0) > 0
      AND contract.start_date IS NOT NULL
      AND contract.end_date IS NOT NULL
      AND contract.end_date >= contract.start_date
      AND (
        graph.missing_invoice_count > 0
        OR (graph.active_schedule_count > 0 AND graph.active_invoice_count = 0)
        OR failed_repair.has_failed_repair
        OR abs(contract.contract_amount - COALESCE(NULLIF(graph.schedule_total, 0), date_graph.expected_amount)) > 1
      )
      AND NOT EXISTS (
        SELECT 1
        FROM public.contract_terms_scan_proposals proposal
        WHERE proposal.contract_id = contract.id
          AND proposal.status = 'applied'
          AND proposal.updated_at > now() - interval '1 day'
      )
  )
  SELECT
    candidate.contract_id,
    candidate.company_id,
    candidate.document_id,
    candidate.contract_number,
    candidate.contract_amount,
    candidate.expected_amount,
    candidate.trigger_reason
  FROM candidate
  ORDER BY candidate.priority_rank, candidate.updated_at, candidate.contract_id
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 4), 1), 25);
$function$;

REVOKE ALL ON FUNCTION public.contract_terms_scan_batch_candidates_v4(uuid,integer,uuid)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.contract_terms_scan_batch_candidates_v4(uuid,integer,uuid)
TO service_role;

CREATE OR REPLACE FUNCTION public.assert_direct_legal_contract_document_v1(
  p_company_id uuid,
  p_contract_id uuid,
  p_document_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_document public.contract_documents%ROWTYPE;
BEGIN
  SELECT document.*
  INTO v_document
  FROM public.contract_documents document
  WHERE document.id = p_document_id
    AND document.company_id = p_company_id
    AND document.contract_id = p_contract_id
    AND document.document_type IN ('signed_contract', 'signed_contract_image')
    AND NULLIF(BTRIM(document.file_path), '') IS NOT NULL;

  IF v_document.id IS NULL THEN
    RETURN jsonb_build_object('allowed', false, 'reason', 'document_not_directly_attached');
  END IF;
  IF v_document.legal_identity_match_status <> 'matched' THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'identity_not_matched',
      'status', v_document.legal_identity_match_status
    );
  END IF;
  IF EXISTS (
    SELECT 1
    FROM public.contract_documents other
    WHERE other.company_id = p_company_id
      AND other.id <> v_document.id
      AND other.file_path = v_document.file_path
      AND other.document_type IN ('signed_contract', 'signed_contract_image')
      AND other.contract_id <> p_contract_id
  ) THEN
    RETURN jsonb_build_object('allowed', false, 'reason', 'storage_file_reused_across_contracts');
  END IF;

  RETURN jsonb_build_object(
    'allowed', true,
    'reason', 'direct_identity_matched_document',
    'documentId', v_document.id,
    'contractId', v_document.contract_id,
    'filePath', v_document.file_path
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.assert_direct_legal_contract_document_v1(uuid,uuid,uuid)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assert_direct_legal_contract_document_v1(uuid,uuid,uuid)
TO service_role;

CREATE OR REPLACE FUNCTION public.get_agent_safety_inventory_v1()
RETURNS TABLE (
  agent_id text,
  display_name text,
  execution_mode text,
  risk_level text,
  conflict_group text,
  policy_enabled boolean,
  invocation_enabled boolean,
  cron_job_id bigint,
  cron_active boolean,
  schedule text,
  lease_company_id uuid,
  lease_owner_agent_id text,
  lease_expires_at timestamptz,
  last_safety_event_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT
    policy.agent_id,
    policy.display_name,
    policy.execution_mode,
    policy.risk_level,
    policy.conflict_group,
    policy.enabled AS policy_enabled,
    registry.enabled AS invocation_enabled,
    cron.jobid AS cron_job_id,
    cron.active AS cron_active,
    cron.schedule,
    lease.company_id AS lease_company_id,
    lease.agent_id AS lease_owner_agent_id,
    lease.expires_at AS lease_expires_at,
    (
      SELECT max(event.created_at)
      FROM public.agent_safety_events event
      WHERE event.agent_id = policy.agent_id
    ) AS last_safety_event_at
  FROM public.agent_safety_policies policy
  LEFT JOIN public.agent_invocation_registry registry
    ON registry.agent_id = policy.agent_id
  LEFT JOIN cron.job cron
    ON cron.jobname = policy.schedule_name
  LEFT JOIN public.agent_invocation_leases lease
    ON lease.conflict_group = policy.conflict_group
   AND lease.expires_at > now();
$function$;

REVOKE ALL ON FUNCTION public.get_agent_safety_inventory_v1()
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_agent_safety_inventory_v1()
TO service_role;

COMMENT ON TABLE public.agent_safety_policies IS
  'Fail-closed policy catalogue for autonomous and scheduled Fleetify agents.';
COMMENT ON FUNCTION public.assert_direct_legal_contract_document_v1(uuid,uuid,uuid) IS
  'Accepts only a directly attached, identity-matched signed contract whose storage object is not reused by another contract.';

COMMIT;
