version: '3.8'

services:
  # خدمة المستشار القانوني الذكي
  legal-ai:
    build: .
    container_name: fleetify-legal-ai
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - legal-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/legal-ai/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # خدمة Redis للتخزين المؤقت
  redis:
    image: redis:7-alpine
    container_name: fleetify-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - legal-ai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # خدمة Nginx للتوزيع والتحميل (اختيارية)
  nginx:
    image: nginx:alpine
    container_name: fleetify-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - legal-ai
    restart: unless-stopped
    networks:
      - legal-ai-network

# الشبكات
networks:
  legal-ai-network:
    driver: bridge

# الأحجام
volumes:
  redis_data:
    driver: local

