/**
 * Lawsuit Preparation Context Provider
 * موفر سياق تجهيز الدعوى
 */

import React, { createContext, useContext, useReducer, useCallback, useEffect, useMemo, useRef } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { invalidateContractDocumentDependents } from '@/utils/contractDocumentQueries';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useUnifiedCompanyAccess } from '@/hooks/useUnifiedCompanyAccess';
import { calculateDelinquencyAmounts } from '@/utils/calculateDelinquencyAmounts';
import {
  buildMemoDocumentData,
  generateDocument as generateDocumentUtil,
  isMemoSnapshotCurrent,
  prepareCurrentFilingState,
} from '../utils/documentGenerators';
import { openLegalCase, registerLegalCase } from '../utils/caseRegistration';
import { exportDocumentsAsZip } from '../utils/zipExport';
import {
  getEffectiveLegalIdentityMatchStatus,
  selectContractDocumentForIdentityScan,
  selectLegalContractDocument,
} from '../utils/contractDocumentSelection';
import { getCurrentLegalCase } from '../utils/taqadiFiling';
import {
  buildTaqadiFilingPayload,
  enqueueTaqadiFilingJob,
  getActiveTaqadiWorker,
} from '../utils/taqadiAutomation';
import {
  buildFactsAdditions,
  inferTaqadiIdType,
  type TaqadiNarrativeInput,
} from '../utils/taqadiNarrative';
import { buildLegalMemoClaimsText } from '@/utils/legal-memo-requests';
import {
  buildLegalEvidenceAnalysis,
  selectAutoAcceptable,
} from '../utils/legalEvidenceAutomation';
import { getFilingReadiness } from '../utils/filingReadiness';
import { getLawsuitClaimAmounts } from '../utils/claimAmounts';
import { loadLegalClaimProjection } from '../utils/legalClaimSources';
import {
  DEFAULT_DEFENDANT_SERVICE_ADDRESS,
  calculateRetentionClaim,
  evaluateLegalMemoReadiness,
  getVerifiedDamageNetFromCosts,
  resolveDefendantContact,
  resolveLegalPath,
} from '../utils/legalCaseWorkflow';
import {
  buildContractDocumentStoragePath,
  getLegalDocumentUploadRoute,
  validateLegalDocumentFile,
} from '../utils/documentUploadRouting';
import { lawsuitService } from '@/services/LawsuitService';
import {
  normalizeLegalContractDocumentIdentityRow,
  normalizeLegalIdentityMatchStatus,
  toLegalIdentityVerification,
  verifyLegalContractDocumentIdentity,
} from '@/services/legalContractIdentityVerifier';
import { formatCustomerName } from '@/utils/formatCustomerName';
import { renderOfficialInvoicePdfBlob } from '@/utils/renderOfficialInvoicePdf';
import { toast } from 'sonner';
import { isTrafficViolationsOnlyScope } from '@/types/legalClaimScope';

import { 
  lawsuitPreparationReducer, 
  createInitialState 
} from './reducer';
import type {
  LawsuitPreparationContextValue,
  DocumentsState,
  LitigationProfile,
  FormalNotice,
  DamageCost,
  LegalEvidenceProposal,
  LegalMemoSnapshot,
  LegalCaseSummary,
  ContractEvidenceDocument,
} from './types';

// ==========================================
// Context
// ==========================================

const LawsuitPreparationContext = createContext<LawsuitPreparationContextValue | null>(null);

function normalizeLegalEvidenceState(
  value: unknown,
): ContractEvidenceDocument['legal_evidence_state'] {
  return value === 'superseded' || value === 'quarantined' ? value : 'active';
}

// ==========================================
// Hook
// ==========================================

export function useLawsuitPreparationContext() {
  const context = useContext(LawsuitPreparationContext);
  if (!context) {
    throw new Error('useLawsuitPreparationContext must be used within LawsuitPreparationProvider');
  }
  return context;
}

// ==========================================
// Provider Props
// ==========================================

interface LawsuitPreparationProviderProps {
  children: React.ReactNode;
  contractId: string;
}

// ==========================================
// Provider Component
// ==========================================

export function LawsuitPreparationProvider({ 
  children, 
  contractId 
}: LawsuitPreparationProviderProps) {
  const { user } = useAuth();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { companyId, isAuthenticating, isInitializing } = useUnifiedCompanyAccess();
  const companyLoading = isAuthenticating || isInitializing;
  
  const [state, dispatch] = useReducer(
    lawsuitPreparationReducer, 
    createInitialState(contractId)
  );
  
  // Refs to store generated content for download
  const contentRefs = useRef<{
    memoHtml: string | null;
    claimsHtml: string | null;
    criminalComplaintHtml: string | null;
    violationsTransferHtml: string | null;
  }>({
    memoHtml: null,
    claimsHtml: null,
    criminalComplaintHtml: null,
    violationsTransferHtml: null,
  });
  const autoGeneratedForContractRef = useRef<string | null>(null);
  const autoAnalyzedForContractRef = useRef<string | null>(null);
  const autoRetentionEvidenceRef = useRef<string | null>(null);
  const autoFrozenSnapshotContractRef = useRef<string | null>(null);
  const isMountedRef = useRef(true);

  useEffect(() => () => {
    isMountedRef.current = false;
  }, []);
  
  // Update companyId in state when available
  useEffect(() => {
    if (companyId) {
      dispatch({ type: 'SET_COMPANY_ID', payload: companyId });
    }
  }, [companyId]);
  
  // ==========================================
  // Data Fetching
  // ==========================================
  
  // Fetch contract data
  // Distinct key: this query returns a composed {contract, customer, vehicle}
  // shape that must never be cached under the details-page 'contract-details'
  // prefix (whose rows carry nested joins and are read by other call sites).
  const { isLoading: contractLoading } = useQuery({
    queryKey: ['lawsuit-contract-details', contractId, companyId],
    staleTime: 0,
    queryFn: async () => {
      if (!companyId) throw new Error('معرف الشركة غير موجود');
      const { data: contract, error } = await supabase
        .from('contracts')
        .select('*')
        .eq('id', contractId)
        .eq('company_id', companyId)
        .single();
      
      if (error) throw error;
      if (!contract) throw new Error('لم يتم العثور على العقد');
      
      // Fetch customer
      let customer = null;
      if (contract.customer_id) {
        const { data: cust } = await supabase
          .from('customers')
          .select('id, first_name, first_name_ar, last_name, last_name_ar, customer_type, company_name, company_name_ar, national_id, nationality, phone, email, address, country')
          .eq('id', contract.customer_id)
          .eq('company_id', companyId)
          .single();
        customer = cust;
      }
      
      // Fetch vehicle
      let vehicle = null;
      if (contract.vehicle_id) {
        const { data: veh } = await supabase
          .from('vehicles')
          .select('make, model, year, plate_number, color, vin, status')
          .eq('id', contract.vehicle_id)
          .eq('company_id', companyId)
          .single();
        vehicle = veh;
      }
      
      dispatch({ 
        type: 'SET_CONTRACT_DATA', 
        payload: { contract, customer, vehicle } 
      });
      
      return { contract, customer, vehicle };
    },
    enabled: !!contractId && !!companyId,
  });
  
  // Fetch the canonical legal claim: invoices first, then legacy due schedules
  const { isLoading: invoicesLoading } = useQuery({
    queryKey: ['legal-claim-projection', contractId, companyId],
    queryFn: async () => {
      if (!companyId) return [];
      const projection = await loadLegalClaimProjection(contractId, companyId);
      dispatch({ type: 'SET_INVOICES', payload: projection.rows });
      dispatch({ type: 'SET_FINANCIAL_CLAIM_SOURCE', payload: projection.summary });
      return projection.rows;
    },
    enabled: !!contractId && !!companyId,
  });
  
  // Fetch reminder history (سجل الإعذار القانوني) for this contract
  useQuery({
    queryKey: ['contract-reminder-history', contractId, companyId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('reminder_history')
        .select('sent_at, reminder_type')
        .eq('contract_id', contractId)
        .eq('success', true)
        .order('sent_at', { ascending: false });

      if (error) throw error;

      const summary = {
        count: data?.length ?? 0,
        lastSentDate: data?.[0]?.sent_at ?? null,
        sendMethods: [...new Set(
          (data ?? [])
            .map((reminder) => reminder.reminder_type)
            .filter((type): type is string => Boolean(type)),
        )],
      };
      dispatch({ type: 'SET_PAYMENT_REMINDERS', payload: summary });
      return summary;
    },
    enabled: !!companyId && !!contractId,
  });

  // Fetch traffic violations
  const { isLoading: violationsLoading } = useQuery({
    queryKey: ['contract-traffic-violations', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];
      
      const { data, error } = await supabase
        .from('penalties')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .neq('payment_status', 'paid')
        .neq('status', 'cancelled')
        .order('penalty_date', { ascending: false });
      
      if (error) throw error;
      
      const normalizedViolations = (data || []).map((violation) => ({
        id: violation.id,
        violation_number: violation.penalty_number,
        violation_date: violation.penalty_date,
        violation_type: violation.violation_type,
        location: violation.location,
        fine_amount: violation.amount,
        total_amount: violation.amount,
        status: violation.status || 'pending',
      }));

      dispatch({ type: 'SET_VIOLATIONS', payload: normalizedViolations });
      return normalizedViolations;
    },
    enabled: !!contractId && !!companyId,
  });
  
  // Fetch company legal documents
  const { isLoading: companyDocumentsLoading } = useQuery({
    queryKey: ['company-legal-documents', companyId],
    queryFn: async () => {
      if (!companyId) return [];
      const docs = await lawsuitService.getCompanyLegalDocuments(companyId);
      dispatch({ type: 'SET_COMPANY_DOCUMENTS', payload: docs });
      return docs;
    },
    enabled: !!companyId,
  });
  
  // Fetch contract document (signed contract)
  const { isLoading: contractDocumentLoading } = useQuery({
    queryKey: ['contract-document', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) {
        console.log('[Contract Document] Missing contractId or companyId');
        return null;
      }
      
      console.log('[Contract Document] Fetching for contract:', contractId);
      
      const { data, error } = await supabase
        .from('contract_documents')
        .select('id, file_path, document_name, document_type, mime_type, legal_identity_match_status, legal_evidence_state, legal_identity_expected_name, legal_identity_extracted_name, legal_identity_expected_id, legal_identity_extracted_id, legal_identity_match_reason, legal_identity_checked_at')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .order('created_at', { ascending: false });
      
      if (error) {
        console.error('[Contract Document] Query error:', error);
        dispatch({
          type: 'UPLOAD_DOCUMENT_ERROR',
          payload: { docId: 'contract', error: 'فشل في جلب ملف العقد من قاعدة البيانات' }
        });
        return null;
      }
      
      dispatch({
        type: 'SET_CONTRACT_EVIDENCE_DOCUMENTS',
        payload: (data || []).map((document) => ({
          id: document.id,
          document_name: document.document_name,
          document_type: document.document_type,
          file_path: document.file_path,
          mime_type: document.mime_type,
          legal_identity_match_status: normalizeLegalIdentityMatchStatus(
            getEffectiveLegalIdentityMatchStatus(document),
          ),
          legal_identity_expected_id: document.legal_identity_expected_id,
          legal_identity_extracted_id: document.legal_identity_extracted_id,
          legal_evidence_state: normalizeLegalEvidenceState(
            document.legal_evidence_state,
          ),
        })),
      });

      let contractDocument = selectLegalContractDocument(data || []);

      if (!contractDocument) {
        const scanCandidate = selectContractDocumentForIdentityScan(data || []);
        if (scanCandidate) {
          try {
            const verifiedDocument = await verifyLegalContractDocumentIdentity(
              companyId,
              normalizeLegalContractDocumentIdentityRow(scanCandidate),
            );
            if (verifiedDocument.legal_identity_match_status === 'matched') {
              contractDocument = {
                ...scanCandidate,
                ...verifiedDocument,
              };
            }
          } catch (verificationError) {
            console.error('[Contract Document] Identity verification failed:', verificationError);
          }
        }
      }

      if (!contractDocument) {
        console.warn('[Contract Document] No identity-matched contract document found');
        dispatch({
          type: 'UPLOAD_DOCUMENT_ERROR',
          payload: {
            docId: 'contract',
            error: 'لا توجد نسخة عقد مطابقة لهوية المستأجر. سيبقى الرفع القانوني متوقفاً حتى اكتمال المطابقة.',
          }
        });
        return null;
      }
      
      console.log('[Contract Document] Found document:', contractDocument.document_name, 'at path:', contractDocument.file_path);

      const identityVerification = toLegalIdentityVerification(
        normalizeLegalContractDocumentIdentityRow(contractDocument),
      );

      const { data: signedUrlData, error: signedUrlError } = await supabase.storage
        .from('contract-documents')
        .createSignedUrl(contractDocument.file_path!, 3600);

      const publicUrl = signedUrlError
        ? supabase.storage.from('contract-documents').getPublicUrl(contractDocument.file_path!).data.publicUrl
        : null;
      const documentUrl = signedUrlData?.signedUrl || publicUrl;

      if (documentUrl) {
        dispatch({ 
          type: 'UPLOAD_DOCUMENT_SUCCESS', 
          payload: {
            docId: 'contract',
            url: documentUrl,
            sourceDocumentId: contractDocument.id,
            identityVerification,
          }
        });
      } else {
        console.error('[Contract Document] Failed to generate public URL');
        dispatch({
          type: 'UPLOAD_DOCUMENT_ERROR',
          payload: { docId: 'contract', error: 'فشل في توليد رابط الملف' }
        });
      }
      
      return contractDocument;
    },
    enabled: !!contractId && !!companyId,
  });

  const { isLoading: violationEvidenceLoading } = useQuery({
    queryKey: ['contract-violation-evidence-documents', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];

      const { data, error } = await supabase
        .from('contract_documents')
        .select('id, document_name, file_path, mime_type')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .eq('document_type', 'violations_proof')
        .order('created_at', { ascending: false });

      if (error) throw error;

      const evidenceDocuments = (await Promise.all((data || []).map(async (document) => {
        if (!document.file_path) return null;
        const { data: signedUrl, error: signedUrlError } = await supabase.storage
          .from('contract-documents')
          .createSignedUrl(document.file_path, 3600);
        if (signedUrlError || !signedUrl?.signedUrl) {
          console.error('[Violation Evidence] Failed to create signed URL:', signedUrlError);
          return null;
        }
        return {
          id: document.id,
          name: document.document_name,
          url: signedUrl.signedUrl,
          mimeType: document.mime_type,
        };
      }))).filter((document): document is NonNullable<typeof document> => Boolean(document));

      dispatch({ type: 'SET_VIOLATION_EVIDENCE_DOCUMENTS', payload: evidenceDocuments });
      return evidenceDocuments;
    },
    enabled: !!contractId && !!companyId,
  });

  // الملف التقاضي الموثق: استراتيجية الفسخ، الإنهاء، التسليم، الحيازة، وديعة الضمان، أجر المثل
  const { isLoading: litigationProfileLoading } = useQuery({
    queryKey: ['legal-case-litigation-profile', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return null;

      const { data, error } = await supabase
        .from('legal_case_litigation_profile')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .maybeSingle();

      if (error) throw error;

      dispatch({ type: 'SET_LITIGATION_PROFILE', payload: (data as LitigationProfile) ?? null });
      return (data as LitigationProfile) ?? null;
    },
    enabled: !!contractId && !!companyId,
  });

  // الإنذارات الكتابية الموثقة الوصول
  const { isLoading: formalNoticesLoading } = useQuery({
    queryKey: ['legal-case-formal-notices', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];

      const { data, error } = await supabase
        .from('legal_case_formal_notices')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .order('sent_on', { ascending: true });

      if (error) throw error;

      const notices = (data || []) as FormalNotice[];
      dispatch({ type: 'SET_FORMAL_NOTICES', payload: notices });
      return notices;
    },
    enabled: !!contractId && !!companyId,
  });

  // بنود مصاريف الأضرار بسند مستند
  const { isLoading: damageCostsLoading } = useQuery({
    queryKey: ['legal-case-damage-costs', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];

      const { data, error } = await supabase
        .from('legal_case_damage_costs')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .order('created_at', { ascending: true });

      if (error) throw error;

      const costs = (data || []) as DamageCost[];
      dispatch({ type: 'SET_DAMAGE_COSTS', payload: costs });
      return costs;
    },
    enabled: !!contractId && !!companyId,
  });

  const { isLoading: evidenceProposalsLoading } = useQuery({
    queryKey: ['legal-case-evidence-proposals', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];
      const { data, error } = await supabase
        .from('legal_case_evidence_proposals')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .eq('status', 'pending')
        .order('confidence', { ascending: false });
      if (error) throw error;
      const proposals = (data || []) as unknown as LegalEvidenceProposal[];
      dispatch({ type: 'SET_EVIDENCE_PROPOSALS', payload: proposals });
      return proposals;
    },
    enabled: !!contractId && !!companyId,
  });

  const { isLoading: memoSnapshotsLoading } = useQuery({
    queryKey: ['legal-case-memo-snapshots', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];
      const { data, error } = await supabase
        .from('legal_case_memo_snapshots')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .order('version', { ascending: false });
      if (error) throw error;
      const snapshots = (data || []) as unknown as LegalMemoSnapshot[];
      dispatch({ type: 'SET_MEMO_SNAPSHOTS', payload: snapshots });
      return snapshots;
    },
    enabled: !!contractId && !!companyId,
  });

  const { isLoading: legalCaseLoading } = useQuery({
    queryKey: ['lawsuit-legal-case', companyId, contractId],
    queryFn: async () => {
      if (!companyId || !contractId) return null;
      const row = await getCurrentLegalCase(companyId, contractId);
      const legalCase: LegalCaseSummary | null = row ? {
        id: row.id,
        case_number: row.case_number || '',
        case_reference: row.case_reference,
        filing_date: row.filing_date,
        case_status: row.case_status || 'draft',
        workflow_stage: row.workflow_stage || 'preparation',
        claim_scope: row.claim_scope || 'full_outstanding',
      } : null;
      dispatch({ type: 'SET_LEGAL_CASE', payload: legalCase });
      return legalCase;
    },
    enabled: !!companyId && !!contractId,
  });
  
  // ==========================================
  // Derived Data (Calculations & Taqadi Data)
  // ==========================================

  const trafficOnlyClaim = isTrafficViolationsOnlyScope(state.legalCase?.claim_scope);

  /** مكونات موثقة إضافية: مصاريف متحقق منها + وديعة ضمان مطبقة */
  const claimExtras = useMemo(() => {
    if (trafficOnlyClaim) {
      return {
        verifiedDamages: 0,
        securityDepositDeduction: 0,
        retentionCompensation: 0,
      };
    }
    const verifiedDamages = getVerifiedDamageNetFromCosts(state.damageCosts);
    const deposit = Number(state.litigationProfile?.security_deposit_amount || 0);
    const applyDeposit = Boolean(state.litigationProfile?.apply_security_deposit) && deposit > 0;
    const legalPath = resolveLegalPath(
      state.litigationProfile,
      state.contract?.end_date || null,
      state.formalNotices,
    );
    const retention = calculateRetentionClaim(state.litigationProfile, legalPath);
    return {
      verifiedDamages,
      securityDepositDeduction: applyDeposit ? deposit : 0,
      retentionCompensation: retention.amount,
    };
  }, [state.contract?.end_date, state.damageCosts, state.formalNotices, state.litigationProfile, trafficOnlyClaim]);

  useEffect(() => {
    if (state.overdueInvoices.length > 0 || state.trafficViolations.length > 0 || claimExtras.verifiedDamages > 0 || claimExtras.retentionCompensation > 0) {
      const contractualCompensation = !trafficOnlyClaim
        && state.litigationProfile?.contractual_compensation_enabled
        && state.litigationProfile.contractual_compensation_method
        && Number(state.litigationProfile.contractual_compensation_rate) > 0
        && state.litigationProfile.contractual_compensation_document_id
        && state.litigationProfile.contractual_compensation_clause_number?.trim()
        && state.litigationProfile.contractual_compensation_clause_text?.trim()
        ? {
            enabled: true,
            method: state.litigationProfile.contractual_compensation_method,
            rate: Number(state.litigationProfile.contractual_compensation_rate),
            cap: state.litigationProfile.contractual_compensation_cap,
          }
        : null;

      const calculations = calculateDelinquencyAmounts(
        (trafficOnlyClaim ? [] : state.overdueInvoices).map(inv => ({
          id: inv.id,
          invoice_number: inv.invoice_number || undefined,
          due_date: inv.due_date,
          total_amount: inv.total_amount || 0,
          paid_amount: inv.paid_amount || 0,
        })),
        (state.violationEvidenceDocuments.length > 0 ? state.trafficViolations : []).map(v => ({
          id: v.id,
          violation_number: v.violation_number || undefined,
          fine_amount: Number(v.fine_amount || 0),
          total_amount: Number(v.total_amount || 0),
          status: v.status,
        })),
        {
          contractualCompensation,
          documentedDamagesAmount: claimExtras.verifiedDamages,
        }
      );

      dispatch({
        type: 'UPDATE_CALCULATIONS',
        payload: {
          ...calculations,
          retentionCompensation: claimExtras.retentionCompensation,
          securityDepositDeduction: claimExtras.securityDepositDeduction,
          total: getLawsuitClaimAmounts(
            {
              ...calculations,
              retentionCompensation: claimExtras.retentionCompensation,
            },
            { securityDepositDeduction: claimExtras.securityDepositDeduction },
          ).cashClaimAmount,
          amountInWords: lawsuitService.convertAmountToWords(
            getLawsuitClaimAmounts({
              ...calculations,
              retentionCompensation: claimExtras.retentionCompensation,
            }, {
              securityDepositDeduction: claimExtras.securityDepositDeduction,
            }).cashClaimAmount
          ),
        }
      });
    }
  }, [
    claimExtras.retentionCompensation,
    claimExtras.securityDepositDeduction,
    claimExtras.verifiedDamages,
    state.litigationProfile,
    state.overdueInvoices,
    state.trafficViolations,
    state.violationEvidenceDocuments,
    trafficOnlyClaim,
  ]);
  
  useEffect(() => {
    if (state.contract && state.calculations && state.customer) {
      const customerName = formatCustomerName(state.customer, { preferArabic: true }) || 'غير محدد';
      const { taqadiClaimAmount } = getLawsuitClaimAmounts(state.calculations, {
        securityDepositDeduction: claimExtras.securityDepositDeduction,
      });
      
      let factsText = lawsuitService.generateFactsText(
        customerName,
        state.contract.start_date,
        `${state.vehicle?.make || ''} ${state.vehicle?.model || ''} ${state.vehicle?.year || ''}`,
        taqadiClaimAmount,
        state.legalCase?.claim_scope,
      );

      // الفروع الحتمية: سداد جزئي، مخالفات، إعذار قانوني، حيازة المركبة، انتهاء العقد
      const legalPath = resolveLegalPath(
        state.litigationProfile,
        state.contract.end_date,
        state.formalNotices,
      );
      const monetaryDelayDamage = state.damageCosts
        .filter((cost) => cost.cost_type === 'monetary_delay_damage' && cost.verified && cost.evidence_document_id)
        .reduce((sum, cost) => sum + Math.max(
          0,
          Number(cost.amount || 0)
            - Number(cost.depreciation_deduction || 0)
            - Number(cost.insurance_recovery || 0),
        ), 0);
      const narrativeInput: TaqadiNarrativeInput = {
        claimAmount: taqadiClaimAmount,
        violationsCount: state.calculations.violationsCount,
        violationsFines: state.calculations.violationsFines,
        paidTotal: trafficOnlyClaim
          ? 0
          : state.overdueInvoices.reduce(
              (sum, invoice) => sum + Number(invoice.paid_amount || 0),
              0,
            ),
        reminders: trafficOnlyClaim
          ? { count: 0, lastSentDate: null, sendMethods: [] }
          : state.paymentReminders,
        vehicleStatus: state.vehicle?.status ?? null,
        vehicleCustody: trafficOnlyClaim
          ? 'unknown'
          : state.litigationProfile?.vehicle_custody === 'with_defendant'
          ? 'with_defendant'
          : ['returned', 'recovered_by_company'].includes(state.litigationProfile?.vehicle_custody || '')
            ? 'returned'
            : 'unknown',
        contractEndDate: trafficOnlyClaim ? null : state.contract.end_date,
        contractStatus: trafficOnlyClaim ? null : state.contract.status ?? null,
        legalPath: trafficOnlyClaim ? undefined : legalPath.effectivePath,
        terminationDate: trafficOnlyClaim ? null : legalPath.effectiveTerminationDate,
        formalNoticeCount: trafficOnlyClaim ? 0 : state.formalNotices.filter(
          (notice) => notice.delivery_confirmed && Boolean(notice.delivered_on) && Boolean(notice.proof_document_id),
        ).length,
        retentionCompensation: trafficOnlyClaim ? 0 : state.calculations.retentionCompensation,
        documentedDamages: trafficOnlyClaim ? 0 : state.calculations.damagesFee,
        monetaryDelayDamage: trafficOnlyClaim ? 0 : monetaryDelayDamage,
        contractualCompensation: trafficOnlyClaim ? 0 : state.calculations.lateFees,
      };

      const additions = buildFactsAdditions(narrativeInput);
      if (additions.length > 0) {
        factsText += `\n\n${additions.join('\n\n')}`;
      }

      const claimsText = buildLegalMemoClaimsText(buildMemoDocumentData(state));
      
      // استخراج معلومات المدعى عليه
      const fullName = customerName;
      const defendantContact = resolveDefendantContact(
        state.litigationProfile,
        state.customer,
      );
      const nameParts = fullName.split(' ');
      const firstName = nameParts[0] || null;
      const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : null;
      const middleName = nameParts.length > 2 ? nameParts.slice(1, -1).join(' ') : null;
      
      const idType = inferTaqadiIdType(
        state.customer.national_id,
        state.customer.nationality || state.customer.country,
      );
      
      // معلومات السيارة
      const vehicleFullDesc = state.vehicle 
        ? `${state.vehicle.make || ''} ${state.vehicle.model || ''} ${state.vehicle.year || ''} - ${state.vehicle.plate_number || state.contract.license_plate || ''}`.trim()
        : state.contract.license_plate
          ? `المركبة ذات اللوحة ${state.contract.license_plate}`
          : 'غير محدد';
      
      dispatch({
        type: 'UPDATE_TAQADI_DATA',
        payload: {
          caseTitle: lawsuitService.generateCaseTitle(customerName, state.legalCase?.claim_scope),
          facts: factsText,
          claims: claimsText,
          amount: taqadiClaimAmount,
          amountInWords: lawsuitService.convertAmountToWords(taqadiClaimAmount),
          
          // بيانات المدعى عليه
          defendant: {
            fullName: fullName,
            firstName: firstName,
            middleName: middleName,
            lastName: lastName,
            idNumber: state.customer.national_id,
            idType: idType,
            nationality: state.customer.nationality || state.customer.country,
            phone: state.customer.phone,
            email: defendantContact.email,
            address: defendantContact.address,
          },
          
          // بيانات العقد
          contract: {
            contractNumber: state.contract.contract_number,
            startDate: state.contract.start_date,
            endDate: state.contract.end_date,
            monthlyAmount: state.contract.monthly_amount,
          },
          
          // بيانات السيارة
          vehicle: {
            make: state.vehicle?.make || null,
            model: state.vehicle?.model || null,
            year: state.vehicle?.year || null,
            plateNumber: state.vehicle?.plate_number || state.contract.license_plate || null,
            color: state.vehicle?.color || null,
            vin: state.vehicle?.vin || null,
            fullDescription: vehicleFullDesc,
          },
        },
      });
    }
  }, [
    claimExtras.securityDepositDeduction,
    state.calculations,
    state.contract,
    state.customer,
    state.damageCosts,
    state.formalNotices,
    state.litigationProfile,
    state.overdueInvoices,
    state.paymentReminders,
    state.vehicle,
    state.legalCase?.claim_scope,
    trafficOnlyClaim,
  ]);
  
  // Update loading state
  useEffect(() => {
    const isLoading = companyLoading || contractLoading || invoicesLoading || violationsLoading || companyDocumentsLoading || contractDocumentLoading || violationEvidenceLoading || litigationProfileLoading || evidenceProposalsLoading || formalNoticesLoading || damageCostsLoading || memoSnapshotsLoading || legalCaseLoading;
    dispatch({ type: 'SET_LOADING', payload: isLoading });
  }, [companyLoading, contractLoading, invoicesLoading, violationsLoading, companyDocumentsLoading, contractDocumentLoading, violationEvidenceLoading, litigationProfileLoading, evidenceProposalsLoading, formalNoticesLoading, damageCostsLoading, memoSnapshotsLoading, legalCaseLoading]);
  
  // ==========================================
  // Actions
  // ==========================================
  
  // دالة لتحميل الصور (اللوقو، التوقيع، الختم) كـ Base64
  const loadImageAsBase64 = async (path: string): Promise<string> => {
    try {
      const response = await fetch(path);
      const blob = await response.blob();
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch (error) {
      console.error(`Failed to load image ${path}:`, error);
      return '';
    }
  };

  // دالة لتضمين جميع الصور في HTML
  const embedImagesInHtml = async (html: string): Promise<string> => {
    try {
      // تحميل جميع الصور
      const [logoBase64, signatureBase64, stampBase64] = await Promise.all([
        loadImageAsBase64('/receipts/logo.png'),
        loadImageAsBase64('/receipts/signature.png'),
        loadImageAsBase64('/receipts/stamp.png'),
      ]);
      
      // استبدال جميع المسارات
      let result = html;
      
      if (logoBase64) {
        result = result
          .replace(/src="\/receipts\/logo\.png"/g, `src="${logoBase64}"`)
          .replace(/src='\/receipts\/logo\.png'/g, `src='${logoBase64}'`);
      }
      
      if (signatureBase64) {
        result = result
          .replace(/src="\/receipts\/signature\.png"/g, `src="${signatureBase64}"`)
          .replace(/src='\/receipts\/signature\.png'/g, `src='${signatureBase64}'`);
      }
      
      if (stampBase64) {
        result = result
          .replace(/src="\/receipts\/stamp\.png"/g, `src="${stampBase64}"`)
          .replace(/src='\/receipts\/stamp\.png'/g, `src='${stampBase64}'`);
      }
      
      return result;
    } catch (error) {
      console.error('Failed to embed images:', error);
      return html;
    }
  };

  const generateDocument = useCallback(async (docId: keyof DocumentsState) => {
    if (!isMountedRef.current) return;
    dispatch({ type: 'GENERATE_DOCUMENT_START', payload: { docId } });
    
    try {
      // Get current state for generation
      const currentState = state;
      
      // Generate document using utility
      const { html: originalHtml } = await generateDocumentUtil(docId, currentState);
      
      // تضمين اللوقو والتوقيع والختم في HTML
      const html = await embedImagesInHtml(originalHtml);
      
      // إنشاء URL جديد مع الصور المضمّنة
      const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
      const urlWithImages = URL.createObjectURL(blob);
      
      // Store HTML in refs for ZIP download
      if (docId === 'memo') contentRefs.current.memoHtml = html;
      if (docId === 'claims') contentRefs.current.claimsHtml = html;
      if (docId === 'criminalComplaint') contentRefs.current.criminalComplaintHtml = html;
      if (docId === 'violationsTransfer') contentRefs.current.violationsTransferHtml = html;
      
      if (!isMountedRef.current) return;
      dispatch({
        type: 'GENERATE_DOCUMENT_SUCCESS', 
        payload: { docId, url: urlWithImages, html } 
      });
    } catch (error) {
      if (!isMountedRef.current) return;
      dispatch({
        type: 'GENERATE_DOCUMENT_ERROR', 
        payload: { docId, error: error as Error } 
      });
    }
  }, [state]);
  
  const generateAllDocuments = useCallback(async () => {
    dispatch({ type: 'GENERATE_ALL_START' });
    
    try {
      const documentsToGenerate: (keyof DocumentsState)[] = ['memo', 'claims'];
      
      if ((state.calculations?.violationsCount || 0) > 0) {
        documentsToGenerate.push('violations', 'violationsTransfer');
      }
      
      documentsToGenerate.push('docsList');
      
      for (const docId of documentsToGenerate) {
        if (!isMountedRef.current) break;
        if (state.documents[docId].status !== 'ready') {
          await generateDocument(docId);
          if (!isMountedRef.current) break;
          // Small delay between generations
          await new Promise(resolve => setTimeout(resolve, 100));
        }
      }
    } finally {
      if (isMountedRef.current) {
        dispatch({ type: 'GENERATE_ALL_COMPLETE' });
      }
    }
  }, [state.documents, state.calculations?.violationsCount, generateDocument]);
  
  const uploadDocument = useCallback(async (docId: keyof DocumentsState, file: File) => {
    if (!companyId || !contractId) {
      toast.error('تعذر تحديد الشركة أو العقد');
      return;
    }
    
    dispatch({ type: 'UPLOAD_DOCUMENT_START', payload: { docId } });
    
    try {
      const route = getLegalDocumentUploadRoute(docId);
      if (!route) {
        throw new Error('هذا المستند يُنشأ من النظام ولا يقبل رفع ملف يدوي');
      }
      validateLegalDocumentFile(file, route);

      if (route.destination === 'company') {
        const uploadedDocument = await lawsuitService.uploadLegalDocument(
          companyId,
          route.documentType,
          file,
          undefined,
          `رُفع من حافظة تجهيز الدعوى للعقد ${state.contract?.contract_number || contractId}`,
          user?.id,
        );
        const nextCompanyDocuments = [
          ...state.companyDocuments.filter(
            (document) => document.document_type !== route.documentType,
          ),
          uploadedDocument,
        ];

        dispatch({ type: 'SET_COMPANY_DOCUMENTS', payload: nextCompanyDocuments });
        dispatch({
          type: 'UPLOAD_DOCUMENT_SUCCESS',
          payload: { docId, url: uploadedDocument.file_url },
        });
        queryClient.setQueryData(
          ['company-legal-documents', companyId],
          nextCompanyDocuments,
        );
      } else {
        const filePath = buildContractDocumentStoragePath({
          companyId,
          contractId,
          documentType: route.documentType,
          fileName: file.name,
        });
        const { error: uploadError } = await supabase.storage
          .from(route.bucket)
          .upload(filePath, file, {
            contentType: file.type || undefined,
            upsert: false,
          });

        if (uploadError) throw uploadError;

        const { data: savedDocument, error: dbError } = await supabase
          .from('contract_documents')
          .insert({
            contract_id: contractId,
            company_id: companyId,
            file_path: filePath,
            document_name: file.name,
            original_filename: file.name,
            document_type: route.documentType,
            mime_type: file.type || null,
            file_size: file.size,
            is_required: true,
            notes: `رُفع من حافظة تجهيز الدعوى: ${state.documents[docId].name}`,
            uploaded_by: user?.id || null,
          })
          .select('id, document_name, file_path, mime_type, legal_identity_match_status, legal_identity_expected_name, legal_identity_extracted_name, legal_identity_expected_id, legal_identity_extracted_id, legal_identity_match_reason, legal_identity_checked_at')
          .single();

        if (dbError || !savedDocument) {
          await supabase.storage.from(route.bucket).remove([filePath]);
          throw dbError || new Error('تعذر ربط الملف بالعقد');
        }

        const { data: signedUrlData, error: signedUrlError } = await supabase.storage
          .from(route.bucket)
          .createSignedUrl(filePath, 3600);
        if (signedUrlError || !signedUrlData?.signedUrl) {
          throw signedUrlError || new Error('تعذر إنشاء رابط معاينة الملف');
        }

        let identityVerification;
        if (docId === 'contract') {
          try {
            const verifiedDocument = await verifyLegalContractDocumentIdentity(
              companyId,
              normalizeLegalContractDocumentIdentityRow(savedDocument),
            );
            identityVerification = toLegalIdentityVerification(verifiedDocument);
          } catch (verificationError) {
            identityVerification = {
              status: 'failed' as const,
              expectedName: state.customer
                ? formatCustomerName(state.customer)
                : null,
              extractedName: null,
              expectedId: state.customer?.national_id || null,
              extractedId: null,
              reason: verificationError instanceof Error
                ? verificationError.message
                : 'تعذر فحص هوية المستأجر في نسخة العقد',
              checkedAt: new Date().toISOString(),
            };
          }
        }

        dispatch({
          type: 'UPLOAD_DOCUMENT_SUCCESS',
          payload: {
            docId,
            url: signedUrlData.signedUrl,
            sourceDocumentId: savedDocument.id,
            identityVerification,
          },
        });

        if (docId === 'violationsEvidence') {
          dispatch({
            type: 'SET_VIOLATION_EVIDENCE_DOCUMENTS',
            payload: [
              {
                id: savedDocument.id,
                name: savedDocument.document_name,
                url: signedUrlData.signedUrl,
                mimeType: savedDocument.mime_type,
              },
              ...state.violationEvidenceDocuments,
            ],
          });
        }

        await invalidateContractDocumentDependents(queryClient, companyId, contractId);
      }

      toast.success(`تم رفع ${state.documents[docId].name} وحفظه في مكانه الصحيح`);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'فشل رفع الملف';
      dispatch({
        type: 'UPLOAD_DOCUMENT_ERROR',
        payload: { docId, error: message },
      });
      toast.error(message);
    }
  }, [companyId, contractId, queryClient, state.companyDocuments, state.contract?.contract_number, state.customer, state.documents, state.violationEvidenceDocuments, user?.id]);

  const saveLitigationProfile = useCallback(async (
    changes: Partial<LitigationProfile>,
  ): Promise<LitigationProfile> => {
    if (!companyId || !contractId || !user?.id) {
      throw new Error('تعذر تحديد الشركة أو العقد أو المستخدم');
    }

    const current = state.litigationProfile;
    const payload = {
      ...(current || {}),
      ...changes,
      defendant_service_address: changes.defendant_service_address?.trim()
        || current?.defendant_service_address?.trim()
        || state.customer?.address?.trim()
        || DEFAULT_DEFENDANT_SERVICE_ADDRESS,
      defendant_contact_source: changes.defendant_contact_source
        || current?.defendant_contact_source
        || 'customer_record',
      id: current?.id,
      company_id: companyId,
      contract_id: contractId,
      created_by: user.id,
      approved_by: changes.legal_review_status === 'approved' ? user.id : null,
      approved_at: changes.legal_review_status === 'approved' ? new Date().toISOString() : null,
    };

    const { data, error } = await supabase
      .from('legal_case_litigation_profile')
      .upsert(payload, { onConflict: 'company_id,contract_id' })
      .select('*')
      .single();
    if (error) throw error;

    const saved = data as LitigationProfile;
    dispatch({ type: 'SET_LITIGATION_PROFILE', payload: saved });
    await queryClient.invalidateQueries({
      queryKey: ['legal-case-litigation-profile', contractId, companyId],
    });
    toast.success('تم حفظ الملف القانوني للقضية');
    return saved;
  }, [companyId, contractId, queryClient, state.customer?.address, state.litigationProfile, user?.id]);

  const saveFormalNotice = useCallback(async (
    notice: Partial<FormalNotice> & Pick<FormalNotice, 'notice_type' | 'sent_on' | 'delivery_method'>,
  ): Promise<FormalNotice> => {
    if (!companyId || !contractId || !user?.id) {
      throw new Error('تعذر تحديد الشركة أو العقد أو المستخدم');
    }
    if (notice.delivery_confirmed && (!notice.delivered_on || !notice.proof_document_id)) {
      throw new Error('إثبات الوصول وتاريخه مطلوبان عند تأكيد تسليم الإنذار');
    }

    const payload = {
      ...notice,
      company_id: companyId,
      contract_id: contractId,
      created_by: user.id,
    };
    const query = notice.id
      ? supabase
          .from('legal_case_formal_notices')
          .update(payload)
          .eq('id', notice.id)
          .eq('company_id', companyId)
          .eq('contract_id', contractId)
      : supabase.from('legal_case_formal_notices').insert(payload);
    const { data, error } = await query.select('*').single();
    if (error) throw error;

    const saved = data as FormalNotice;
    const next = notice.id
      ? state.formalNotices.map((item) => (item.id === saved.id ? saved : item))
      : [...state.formalNotices, saved];
    dispatch({ type: 'SET_FORMAL_NOTICES', payload: next });
    if (state.litigationProfile?.legal_review_status === 'approved') {
      dispatch({
        type: 'SET_LITIGATION_PROFILE',
        payload: { ...state.litigationProfile, legal_review_status: 'draft', approved_by: null, approved_at: null, approval_source: null, approval_job_id: null, approval_worker_id: null },
      });
    }
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['legal-case-formal-notices', contractId, companyId] }),
      queryClient.invalidateQueries({ queryKey: ['legal-case-litigation-profile', contractId, companyId] }),
    ]);
    toast.success('تم حفظ الإنذار الموثق');
    return saved;
  }, [companyId, contractId, queryClient, state.formalNotices, state.litigationProfile, user?.id]);

  const deleteFormalNotice = useCallback(async (noticeId: string): Promise<void> => {
    if (!companyId || !contractId) throw new Error('تعذر تحديد الشركة أو العقد');
    const { error } = await supabase
      .from('legal_case_formal_notices')
      .delete()
      .eq('id', noticeId)
      .eq('company_id', companyId)
      .eq('contract_id', contractId);
    if (error) throw error;
    dispatch({
      type: 'SET_FORMAL_NOTICES',
      payload: state.formalNotices.filter((notice) => notice.id !== noticeId),
    });
    if (state.litigationProfile?.legal_review_status === 'approved') {
      dispatch({ type: 'SET_LITIGATION_PROFILE', payload: { ...state.litigationProfile, legal_review_status: 'draft', approved_by: null, approved_at: null, approval_source: null, approval_job_id: null, approval_worker_id: null } });
    }
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['legal-case-formal-notices', contractId, companyId] }),
      queryClient.invalidateQueries({ queryKey: ['legal-case-litigation-profile', contractId, companyId] }),
    ]);
  }, [companyId, contractId, queryClient, state.formalNotices, state.litigationProfile]);

  const saveDamageCost = useCallback(async (
    cost: Partial<DamageCost> & Pick<DamageCost, 'cost_type' | 'description' | 'amount'>,
  ): Promise<DamageCost> => {
    if (!companyId || !contractId || !user?.id) {
      throw new Error('تعذر تحديد الشركة أو العقد أو المستخدم');
    }
    if (cost.verified && !cost.evidence_document_id) {
      throw new Error('لا يمكن اعتماد الضرر دون مستند مؤيد مرتبط بالعقد');
    }

    const payload = {
      ...cost,
      company_id: companyId,
      contract_id: contractId,
      created_by: user.id,
      depreciation_deduction: Math.max(0, Number(cost.depreciation_deduction || 0)),
      insurance_recovery: Math.max(0, Number(cost.insurance_recovery || 0)),
    };
    const query = cost.id
      ? supabase
          .from('legal_case_damage_costs')
          .update(payload)
          .eq('id', cost.id)
          .eq('company_id', companyId)
          .eq('contract_id', contractId)
      : supabase.from('legal_case_damage_costs').insert(payload);
    const { data, error } = await query.select('*').single();
    if (error) throw error;

    const saved = data as DamageCost;
    const next = cost.id
      ? state.damageCosts.map((item) => (item.id === saved.id ? saved : item))
      : [...state.damageCosts, saved];
    dispatch({ type: 'SET_DAMAGE_COSTS', payload: next });
    if (state.litigationProfile?.legal_review_status === 'approved') {
      dispatch({ type: 'SET_LITIGATION_PROFILE', payload: { ...state.litigationProfile, legal_review_status: 'draft', approved_by: null, approved_at: null, approval_source: null, approval_job_id: null, approval_worker_id: null } });
    }
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['legal-case-damage-costs', contractId, companyId] }),
      queryClient.invalidateQueries({ queryKey: ['legal-case-litigation-profile', contractId, companyId] }),
    ]);
    toast.success('تم حفظ بند الضرر والمستند المؤيد');
    return saved;
  }, [companyId, contractId, queryClient, state.damageCosts, state.litigationProfile, user?.id]);

  const deleteDamageCost = useCallback(async (costId: string): Promise<void> => {
    if (!companyId || !contractId) throw new Error('تعذر تحديد الشركة أو العقد');
    const { error } = await supabase
      .from('legal_case_damage_costs')
      .delete()
      .eq('id', costId)
      .eq('company_id', companyId)
      .eq('contract_id', contractId);
    if (error) throw error;
    dispatch({
      type: 'SET_DAMAGE_COSTS',
      payload: state.damageCosts.filter((cost) => cost.id !== costId),
    });
    if (state.litigationProfile?.legal_review_status === 'approved') {
      dispatch({ type: 'SET_LITIGATION_PROFILE', payload: { ...state.litigationProfile, legal_review_status: 'draft', approved_by: null, approved_at: null, approval_source: null, approval_job_id: null, approval_worker_id: null } });
    }
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['legal-case-damage-costs', contractId, companyId] }),
      queryClient.invalidateQueries({ queryKey: ['legal-case-litigation-profile', contractId, companyId] }),
    ]);
  }, [companyId, contractId, queryClient, state.damageCosts, state.litigationProfile]);

  const freezeMemoSnapshot = useCallback(async () => {
    if (!companyId || !contractId || !state.contract || !user?.id) {
      throw new Error('بيانات القضية غير مكتملة');
    }
    const readiness = evaluateLegalMemoReadiness(state);
    if (readiness.status === 'not_ready') {
      throw new Error(`لا يمكن تثبيت المذكرة قبل معالجة: ${readiness.issues.join('، ')}`);
    }

    const legalCase = await getCurrentLegalCase(companyId, contractId);
    const now = new Date();
    const filedOn = legalCase?.filing_date?.slice(0, 10) || null;
    const memoPayload = {
      ...buildMemoDocumentData(state),
      caseNumber: legalCase?.case_number || undefined,
      filingDate: filedOn || undefined,
    };

    const { data, error } = await supabase
      .rpc('freeze_legal_case_memo_snapshot', {
        p_company_id: companyId,
        p_contract_id: contractId,
        p_case_id: legalCase?.id || null,
        p_facts_as_of_date: now.toISOString().slice(0, 10),
        p_filing_date: filedOn,
        p_legal_path: readiness.legalPath.effectivePath,
        p_readiness_status: ['ready', 'approved'].includes(readiness.status)
          ? 'ready'
          : 'ready_with_reservations',
        p_readiness_issues: [...readiness.issues, ...readiness.warnings],
        p_payload: JSON.parse(JSON.stringify(memoPayload)),
        p_template_version: 'INVESTMENT_COURT_MEMO_V2',
        p_approve: false,
      });
    if (error) throw error;
    const snapshot = data as unknown as LegalMemoSnapshot;
    dispatch({ type: 'SET_MEMO_SNAPSHOTS', payload: [snapshot, ...state.memoSnapshots] });
    await queryClient.invalidateQueries({
      queryKey: ['legal-case-memo-snapshots', contractId, companyId],
    });
    toast.success('تم تثبيت نسخة المذكرة لمراجعة وكيل تقاضي');
    return snapshot;
  }, [companyId, contractId, queryClient, state, user?.id]);

  const uploadEvidenceDocument = useCallback(async (
    file: File,
    documentType: string,
    documentName?: string,
  ) => {
    if (!companyId || !contractId || !user?.id) {
      throw new Error('تعذر تحديد الشركة أو العقد أو المستخدم');
    }
    validateLegalDocumentFile(file);
    const filePath = buildContractDocumentStoragePath({
      companyId,
      contractId,
      documentType,
      fileName: file.name,
    });
    const { error: uploadError } = await supabase.storage
      .from('contract-documents')
      .upload(filePath, file, { upsert: false, contentType: file.type || undefined });
    if (uploadError) throw uploadError;

    const { data, error } = await supabase
      .from('contract_documents')
      .insert({
        company_id: companyId,
        contract_id: contractId,
        document_name: documentName?.trim() || file.name,
        document_type: documentType,
        file_path: filePath,
        file_size: file.size,
        mime_type: file.type || null,
        original_filename: file.name,
        uploaded_by: user.id,
        is_required: false,
      })
      .select('id, document_name, document_type, file_path, mime_type, legal_identity_match_status, legal_evidence_state')
      .single();
    if (error) {
      await supabase.storage.from('contract-documents').remove([filePath]);
      throw error;
    }

    const evidenceDocument: ContractEvidenceDocument = {
      ...data,
      legal_identity_match_status: normalizeLegalIdentityMatchStatus(
        data.legal_identity_match_status,
      ),
      legal_evidence_state: normalizeLegalEvidenceState(data.legal_evidence_state),
    };
    dispatch({
      type: 'SET_CONTRACT_EVIDENCE_DOCUMENTS',
      payload: [evidenceDocument, ...state.contractEvidenceDocuments.filter((doc) => doc.id !== data.id)],
    });
    await queryClient.invalidateQueries({ queryKey: ['contract-document', contractId, companyId] });
    toast.success('تم رفع مستند الإثبات وربطه بالعقد');
    return evidenceDocument;
  }, [companyId, contractId, queryClient, state.contractEvidenceDocuments, user?.id]);

  const analyzeLegalEvidence = useCallback(async () => {
    if (!companyId || !contractId || !user?.id) {
      throw new Error('تعذر تحديد الشركة أو العقد أو المستخدم');
    }

    const [returnResult, pricingResult, templateResult] = await Promise.all([
      supabase
        .from('contract_vehicle_returns')
        .select('id, return_date, status, notes')
        .eq('company_id', companyId)
        .eq('contract_id', contractId)
        .eq('status', 'approved')
        .order('return_date', { ascending: false })
        .limit(1)
        .maybeSingle(),
      state.contract?.vehicle_id
        ? supabase
            .from('vehicle_pricing')
            .select('id, daily_rate, security_deposit, effective_from')
            .eq('vehicle_id', state.contract.vehicle_id)
            .or(`effective_to.is.null,effective_to.gte.${new Date().toISOString().slice(0, 10)}`)
            .order('effective_from', { ascending: false })
            .limit(1)
            .maybeSingle()
        : Promise.resolve({ data: null, error: null }),
      // قالب العقد الافتراضي للشركة عبر company_settings → contract_templates
      supabase
        .from('company_settings')
        .select('default_contract_template_id')
        .eq('company_id', companyId)
        .maybeSingle()
        .then(async ({ data: settings }) => {
          const templateId = settings?.default_contract_template_id;
          if (!templateId) return { data: null, error: null };
          return supabase
            .from('contract_templates')
            .select('id, late_fee_terms_ar, termination_terms_ar, legal_clauses_ar')
            .eq('id', templateId)
            .eq('company_id', companyId)
            .maybeSingle();
        }),
    ]);
    if (returnResult.error) throw returnResult.error;
    if (pricingResult.error) throw pricingResult.error;
    if (templateResult.error) throw templateResult.error;

    const templateRow = templateResult.data as {
      id: string;
      late_fee_terms_ar: string | null;
      termination_terms_ar: string | null;
      legal_clauses_ar: unknown;
    } | null;

    const analysis = buildLegalEvidenceAnalysis(state, {
      vehicleReturn: returnResult.data,
      vehiclePricing: pricingResult.data,
      contractTemplate: templateRow
        ? {
            id: templateRow.id,
            lateFeeTermsAr: templateRow.late_fee_terms_ar,
            terminationTermsAr: templateRow.termination_terms_ar,
            legalClausesAr: templateRow.legal_clauses_ar,
          }
        : null,
    });

    const automaticPatch = analysis.automatic.reduce<Partial<LitigationProfile>>(
      (patch, candidate) => ({ ...patch, ...candidate.patch }),
      {},
    );

    // القبول التلقائي: مقترحات review بثقة عالية وسند مستند مرفق — تُطبَّق فوراً
    // وتُخزَّن كقرارات مقبولة موثقة في نفس جدول المقترحات.
    const autoAcceptedCandidates = selectAutoAcceptable(analysis.review);
    const autoAcceptPatch = autoAcceptedCandidates.reduce<Partial<LitigationProfile>>(
      (patch, candidate) => ({ ...patch, ...candidate.patch }),
      {},
    );
    const mergedPatch = { ...automaticPatch, ...autoAcceptPatch };
    if (Object.keys(mergedPatch).length > 0) {
      await saveLitigationProfile({ ...mergedPatch, legal_review_status: 'draft' });
    }

    const proposalRowFor = (candidate: (typeof analysis.review)[number], accepted: boolean) => ({
      company_id: companyId,
      contract_id: contractId,
      field_key: candidate.fieldKey,
      field_label: candidate.label,
      value_label: candidate.valueLabel,
      proposed_patch: JSON.parse(JSON.stringify(candidate.patch)),
      current_value: state.litigationProfile
        ? JSON.parse(JSON.stringify(state.litigationProfile))
        : null,
      automation_level: candidate.level,
      source_kind: candidate.sourceKind,
      source_ref: candidate.sourceRef,
      source_label: candidate.sourceLabel,
      source_document_id: candidate.sourceDocumentId,
      confidence: candidate.confidence,
      reason: accepted
        ? `${candidate.reason} — اعتُمد تلقائياً لاكتمال سنده المستندي.`
        : candidate.reason,
      status: accepted ? 'accepted' : 'pending',
      reviewed_by: accepted ? user.id : null,
      reviewed_at: accepted ? new Date().toISOString() : null,
      applied_at: accepted ? new Date().toISOString() : null,
      created_by: user.id,
    });

    const autoAcceptedRows = autoAcceptedCandidates.map((candidate) => proposalRowFor(candidate, true));
    const pendingRows = analysis.review
      .filter((candidate) => !autoAcceptedCandidates.includes(candidate))
      .filter((candidate) => !state.evidenceProposals.some((existing) => (
        existing.field_key === candidate.fieldKey
        && existing.source_kind === candidate.sourceKind
        && existing.source_ref === candidate.sourceRef
        && existing.status !== 'pending'
      )))
      .map((candidate) => proposalRowFor(candidate, false));

    const rowsToUpsert = [...autoAcceptedRows, ...pendingRows];
    if (rowsToUpsert.length > 0) {
      const { error } = await supabase
        .from('legal_case_evidence_proposals')
        .upsert(rowsToUpsert, {
          onConflict: 'company_id,contract_id,field_key,source_kind,source_ref',
        });
      if (error) throw error;
    }

    const { data: proposals, error: proposalsError } = await supabase
      .from('legal_case_evidence_proposals')
      .select('*')
      .eq('company_id', companyId)
      .eq('contract_id', contractId)
      .eq('status', 'pending')
      .order('confidence', { ascending: false });
    if (proposalsError) throw proposalsError;
    dispatch({
      type: 'SET_EVIDENCE_PROPOSALS',
      payload: (proposals || []) as unknown as LegalEvidenceProposal[],
    });
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['legal-case-evidence-proposals', contractId, companyId] }),
      queryClient.invalidateQueries({ queryKey: ['legal-case-litigation-profile', contractId, companyId] }),
    ]);
    toast.success(
      autoAcceptedRows.length > 0
        ? `تم التحقق من ${analysis.automatic.length} مصادر واعتماد ${autoAcceptedRows.length} مقترحات تلقائياً، وتجهيز ${pendingRows.length} مقترحات للمراجعة`
        : `تم التحقق من ${analysis.automatic.length} مصادر مؤكدة وتجهيز ${pendingRows.length} مقترحات للمراجعة`,
    );
    return analysis;
  }, [companyId, contractId, queryClient, saveLitigationProfile, state, user?.id]);

  const reviewEvidenceProposal = useCallback(async (
    proposalId: string,
    decision: 'accept' | 'reject',
  ) => {
    if (!companyId || !contractId || !user?.id) {
      throw new Error('تعذر تحديد الشركة أو العقد أو المستخدم');
    }
    const proposal = state.evidenceProposals.find((item) => item.id === proposalId);
    if (!proposal || proposal.status !== 'pending') {
      throw new Error('المقترح غير موجود أو تمت مراجعته مسبقاً');
    }

    if (decision === 'accept') {
      await saveLitigationProfile({
        ...proposal.proposed_patch,
        legal_review_status: 'draft',
      });
    }

    const reviewedAt = new Date().toISOString();
    const { error } = await supabase
      .from('legal_case_evidence_proposals')
      .update({
        status: decision === 'accept' ? 'accepted' : 'rejected',
        reviewed_by: user.id,
        reviewed_at: reviewedAt,
        applied_at: decision === 'accept' ? reviewedAt : null,
      })
      .eq('id', proposalId)
      .eq('company_id', companyId)
      .eq('contract_id', contractId)
      .eq('status', 'pending');
    if (error) throw error;

    dispatch({
      type: 'SET_EVIDENCE_PROPOSALS',
      payload: state.evidenceProposals.filter((item) => item.id !== proposalId),
    });
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['legal-case-evidence-proposals', contractId, companyId] }),
      queryClient.invalidateQueries({ queryKey: ['legal-case-litigation-profile', contractId, companyId] }),
    ]);
    toast.success(decision === 'accept' ? 'تم اعتماد المقترح وتطبيقه' : 'تم رفض المقترح مع حفظ القرار');
  }, [companyId, contractId, queryClient, saveLitigationProfile, state.evidenceProposals, user?.id]);
  
  const registerCase = useCallback(async () => {
    if (!user?.id) {
      throw new Error('المستخدم غير مسجل الدخول');
    }
    
    dispatch({ type: 'REGISTER_CASE_START' });
    
    try {
      const result = await registerLegalCase(state, user.id);
      
      dispatch({ type: 'REGISTER_CASE_COMPLETE' });
      await queryClient.invalidateQueries({
        queryKey: ['lawsuit-legal-case', companyId, contractId],
      });
      toast.success('تم تسجيل القضية وربطها بملف التجهيز');
      
      return result;
    } catch (error) {
      dispatch({ type: 'REGISTER_CASE_ERROR', payload: error as Error });
      throw error;
    }
  }, [state, user, queryClient, companyId, contractId]);
  
  /**
   * توليد HTML للفاتورة
   */
  const generateInvoiceHtml = async (invoice: any, customer: any, contract: any): Promise<string> => {
    const totalAmount = Number(invoice.total_amount) || 0;
    const paidAmount = Number(invoice.paid_amount) || 0;
    const remainingAmount = totalAmount - paidAmount;
    
    const customerName = customer 
      ? formatCustomerName(customer)
      : 'غير محدد';
    
    const formattedDate = invoice.invoice_date 
      ? new Date(invoice.invoice_date).toLocaleDateString('ar-QA')
      : new Date().toLocaleDateString('ar-QA');
    
    return `
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
  <meta charset="UTF-8">
  <title>فاتورة ${invoice.invoice_number}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Arial', 'Tahoma', sans-serif;
      background: #fff;
      padding: 20px;
      direction: rtl;
    }
    .invoice-container {
      max-width: 210mm;
      margin: 0 auto;
      background: #fff;
      border: 2px solid #1a5490;
      border-radius: 8px;
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #1a5490 0%, #2196F3 100%);
      color: white;
      padding: 30px;
      text-align: center;
    }
    .header h1 {
      font-size: 28px;
      margin-bottom: 10px;
    }
    .header p {
      font-size: 14px;
      opacity: 0.9;
    }
    .content {
      padding: 30px;
    }
    .info-row {
      display: flex;
      justify-content: space-between;
      padding: 12px;
      border-bottom: 1px solid #e0e0e0;
    }
    .info-label {
      font-weight: bold;
      color: #1a5490;
    }
    .amount-box {
      background: #f5f5f5;
      border: 2px solid #1a5490;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
      text-align: center;
    }
    .amount-box .label {
      font-size: 14px;
      color: #666;
      margin-bottom: 10px;
    }
    .amount-box .value {
      font-size: 32px;
      font-weight: bold;
      color: #1a5490;
    }
    .status-badge {
      display: inline-block;
      padding: 8px 16px;
      border-radius: 20px;
      font-weight: bold;
      font-size: 14px;
    }
    .status-unpaid {
      background: #ffebee;
      color: #c62828;
    }
    .footer {
      background: #f5f5f5;
      padding: 20px;
      text-align: center;
      border-top: 2px solid #1a5490;
    }
  </style>
</head>
<body>
  <div class="invoice-container">
    <div class="header">
      <h1>فاتورة مستحقة</h1>
      <p>شركة العراف لتأجير السيارات</p>
      <p>Al-Araf Car Rental</p>
    </div>
    
    <div class="content">
      <div class="info-row">
        <span class="info-label">رقم الفاتورة:</span>
        <span>${invoice.invoice_number || '-'}</span>
      </div>
      <div class="info-row">
        <span class="info-label">تاريخ الفاتورة:</span>
        <span>${formattedDate}</span>
      </div>
      <div class="info-row">
        <span class="info-label">اسم العميل:</span>
        <span>${customerName}</span>
      </div>
      <div class="info-row">
        <span class="info-label">رقم العقد:</span>
        <span>${contract?.contract_number || '-'}</span>
      </div>
      <div class="info-row">
        <span class="info-label">الوصف:</span>
        <span>${invoice.description || 'فاتورة إيجار شهري'}</span>
      </div>
      
      <div class="amount-box">
        <div class="label">المبلغ الإجمالي</div>
        <div class="value">${totalAmount.toLocaleString('en-US')} ر.ق</div>
      </div>
      
      ${paidAmount > 0 ? `
      <div class="info-row">
        <span class="info-label">المبلغ المدفوع:</span>
        <span style="color: #4caf50; font-weight: bold;">${paidAmount.toLocaleString('en-US')} ر.ق</span>
      </div>
      ` : ''}
      
      ${remainingAmount > 0 ? `
      <div class="info-row">
        <span class="info-label">المبلغ المتبقي:</span>
        <span style="color: #c62828; font-weight: bold;">${remainingAmount.toLocaleString('en-US')} ر.ق</span>
      </div>
      ` : ''}
      
      <div style="text-align: center; margin-top: 20px;">
        <span class="status-badge status-unpaid">مستحقة الدفع</span>
      </div>
    </div>
    
    <div class="footer">
      <p style="color: #666; font-size: 12px;">
        أم صلال محمد – الشارع التجاري – مبنى (79) – الطابق الأول – مكتب (2)
      </p>
      <p style="color: #666; font-size: 12px; margin-top: 5px;">
        هاتف: +974 4444 4444 | البريد الإلكتروني: khamis-1992@hotmail.com
      </p>
    </div>
  </div>
</body>
</html>
    `;
  };
  
  /**
   * تحميل جميع الفواتير المستحقة كملف ZIP
   */
  const downloadInvoicesAsZip = useCallback(async () => {
    try {
      if (state.overdueInvoices.length === 0) {
        toast.error('لا توجد فواتير مستحقة');
        return;
      }
      
      dispatch({ type: 'SET_DOWNLOADING_INVOICES', payload: true });
      const containsScheduleClaims = state.overdueInvoices.some(
        (invoice) => invoice.source === 'payment_schedule',
      );
      toast.info(containsScheduleClaims
        ? 'جاري تجهيز مستندات الاستحقاق...'
        : 'جاري تجهيز الفواتير...');
      
      // Dynamic import for heavy libraries
      const [{ default: JSZip }] = await Promise.all([
        import('jszip'),
      ]);
      
      const zip = new JSZip();
      const invoicesFolder = zip.folder(containsScheduleClaims ? 'مستندات_الاستحقاق' : 'الفواتير');
      
      if (!invoicesFolder) {
        throw new Error('فشل في إنشاء مجلد الفواتير');
      }
      
      // توليد PDF لكل فاتورة
      for (let i = 0; i < state.overdueInvoices.length; i++) {
        const invoice = state.overdueInvoices[i];
        
        toast.info(`جاري معالجة مستند الاستحقاق ${i + 1} من ${state.overdueInvoices.length}...`);
        
        const customerName = formatCustomerName(state.customer) || undefined;
        const pdfBlob = await renderOfficialInvoicePdfBlob(invoice, customerName);
        const filePrefix = invoice.source === 'payment_schedule' ? 'استحقاق_تعاقدي' : 'فاتورة';
        const fileName = `${filePrefix}_${invoice.invoice_number || i + 1}.pdf`;
        invoicesFolder.file(fileName, pdfBlob);
      }
      
      // Generate ZIP
      toast.info('جاري ضغط الفواتير...');
      const zipBlob = await zip.generateAsync({ type: 'blob' });
      
      // Download
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${containsScheduleClaims ? 'مستندات_استحقاق' : 'فواتير'}_${state.contract?.contract_number || 'العقد'}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.success(`تم تحميل ${state.overdueInvoices.length} مستند استحقاق بنجاح`);
    } catch (error: any) {
      console.error('Error downloading invoices:', error);
      toast.error(`خطأ في تحميل الفواتير: ${error.message}`);
    } finally {
      dispatch({ type: 'SET_DOWNLOADING_INVOICES', payload: false });
    }
  }, [state.overdueInvoices, state.customer, state.contract]);
  
  const downloadAllAsZip = useCallback(async () => {
    dispatch({ type: 'DOWNLOAD_ZIP_START' });
    
    try {
      await exportDocumentsAsZip(state, contentRefs.current);
    } finally {
      dispatch({ type: 'DOWNLOAD_ZIP_COMPLETE' });
    }
  }, [state]);
  
  const sendToLawsuitData = useCallback(async () => {
    dispatch({ type: 'SEND_TO_LAWSUIT_DATA_START' });
    
    try {
      if (!state.taqadiData || !companyId || !state.contract) return;
      
      const customer = state.customer;
      const defendantContact = resolveDefendantContact(
        state.litigationProfile,
        state.customer,
      );
      const fullName = formatCustomerName(customer, { preferArabic: true });
      const nameParts = fullName.split(' ');
      
      const lawsuitRecord = {
        company_id: companyId,
        case_title: state.taqadiData.caseTitle,
        facts: state.taqadiData.facts,
        requests: state.taqadiData.claims,
        claim_amount: state.taqadiData.amount,
        claim_amount_words: state.taqadiData.amountInWords,
        defendant_first_name: nameParts[0] || '',
        defendant_middle_name: nameParts.length > 2 ? nameParts.slice(1, -1).join(' ') : null,
        defendant_last_name: nameParts.length > 1 ? nameParts[nameParts.length - 1] : '',
        defendant_nationality: customer?.nationality || customer?.country || null,
        defendant_id_number: customer?.national_id || null,
        defendant_address: defendantContact.address || null,
        defendant_phone: customer?.phone || null,
        defendant_email: defendantContact.email || null,
        contract_id: contractId,
        customer_id: customer?.id || null,
      };
      
      const { error } = await supabase
        .from('lawsuit_templates')
        .insert([lawsuitRecord]);
      
      if (error) throw error;
      
    } finally {
      dispatch({ type: 'SEND_TO_LAWSUIT_DATA_COMPLETE' });
    }
  }, [state.taqadiData, state.contract, state.customer, state.litigationProfile, companyId, contractId]);
  
  const startTaqadiAutomation = useCallback(async () => {
    dispatch({ type: 'TAQADI_AUTOMATION_START' });

    try {
      if (!companyId || !user?.id) {
        throw new Error('تعذر تحديد الشركة أو المستخدم');
      }

      const filingReadiness = getFilingReadiness(state);
      if (!filingReadiness.canStartFiling) {
        throw new Error(
          `ملف الدعوى غير جاهز لبدء الإجراءات: ${filingReadiness.missingReasons.join('، ')}`,
        );
      }

      // Freeze a current draft for the worker to review. Approval is performed
      // later by the trusted Taqadi worker after matching the live portal
      // review; the user is never asked to approve this snapshot.
      let filingBaseState = state;
      if (!state.memoSnapshots.some((snapshot) => isMemoSnapshotCurrent(state, snapshot))) {
        const snapshot = await freezeMemoSnapshot();
        filingBaseState = {
          ...state,
          memoSnapshots: [snapshot, ...state.memoSnapshots],
        };
      }

      let legalCase = await getCurrentLegalCase(companyId, contractId);
      if (!legalCase) {
        const registered = await registerLegalCase(state, user.id, {
          preparationOnly: true,
        });
        legalCase = {
          id: registered.caseId,
          case_number: registered.caseNumber,
          case_status: 'pending',
          workflow_stage: 'preparation',
          case_reference: null,
          court_fees: null,
          filing_date: null,
          created_at: null,
          claim_scope: state.legalCase?.claim_scope ?? 'full_outstanding',
        };
      }
      const currentStage = legalCase.workflow_stage || 'preparation';
      if (['closed', 'cancelled'].includes(currentStage)) {
        throw new Error('القضية مغلقة أو ملغاة. أعد فتحها قبل إرسالها إلى تقاضي');
      }
      if (!['preparation', 'filed'].includes(currentStage)) {
        throw new Error('القضية تجاوزت مرحلة الرفع ولا يمكن إرسالها إلى تقاضي مرة أخرى');
      }
      if (currentStage === 'filed' && legalCase.case_reference) {
        throw new Error(`الدعوى مرفوعة مسبقًا في تقاضي بالمرجع ${legalCase.case_reference}`);
      }

      dispatch({
        type: 'TAQADI_AUTOMATION_STATUS',
        payload: 'جاري فحص الحزمة وإضافتها إلى طابور تقاضي...',
      });
      dispatch({
        type: 'TAQADI_AUTOMATION_STATUS',
        payload: 'جاري إعادة توليد الحزمة من النسخة التي سيراجعها الوكيل...',
      });
      const filingState = await prepareCurrentFilingState(filingBaseState);
      const payload = buildTaqadiFilingPayload(filingState, window.location.href);
      const job = await enqueueTaqadiFilingJob({
        companyId,
        legalCaseId: legalCase.id,
        payload,
      });

      await Promise.all([
        queryClient.invalidateQueries({
          queryKey: ['taqadi-filing-job', companyId, legalCase.id],
        }),
        queryClient.invalidateQueries({ queryKey: ['lawsuit-legal-case', companyId, contractId] }),
        queryClient.invalidateQueries({ queryKey: ['legal-case-workflow', companyId, legalCase.id] }),
        queryClient.invalidateQueries({ queryKey: ['legal-cases'] }),
      ]);

      dispatch({
        type: 'TAQADI_AUTOMATION_STATUS',
        payload: `تمت إضافة الدعوى إلى طابور الرفع. رقم العملية: ${job.id}`,
      });
      toast.success('تمت إضافة الدعوى إلى طابور تقاضي');
    } catch (error: any) {
      dispatch({
        type: 'TAQADI_AUTOMATION_STATUS',
        payload: `خطأ: ${error?.message || 'تعذر إضافة الدعوى إلى الطابور'}`,
      });
      toast.error(error?.message || 'تعذر إضافة الدعوى إلى الطابور');
    } finally {
      dispatch({ type: 'TAQADI_AUTOMATION_STOP' });
    }
  }, [
    companyId,
    contractId,
    freezeMemoSnapshot,
    queryClient,
    state,
    user?.id,
  ]);
  
  const stopTaqadiAutomation = useCallback(() => {
    dispatch({ type: 'TAQADI_AUTOMATION_STOP' });
  }, []);
  
  const checkTaqadiServer = useCallback(async () => {
    try {
      const worker = await getActiveTaqadiWorker();
      const heartbeatAge = worker
        ? Date.now() - new Date(worker.heartbeat_at).getTime()
        : Number.POSITIVE_INFINITY;
      const isRunning = heartbeatAge < 45_000 && worker?.status !== 'offline';
      dispatch({ type: 'SET_TAQADI_SERVER_STATUS', payload: isRunning });
      return isRunning;
    } catch {
      dispatch({ type: 'SET_TAQADI_SERVER_STATUS', payload: false });
      return false;
    }
  }, []);
  
  const copyToClipboard = useCallback(async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text);
      dispatch({ type: 'SET_COPIED_FIELD', payload: field });
      setTimeout(() => {
        dispatch({ type: 'SET_COPIED_FIELD', payload: null });
      }, 2000);
    } catch {
      console.error('Failed to copy');
    }
  }, []);
  
  const toggleTaqadiData = useCallback(() => {
    dispatch({ type: 'TOGGLE_TAQADI_DATA' });
  }, []);
  
  const setIncludeCriminalComplaint = useCallback((value: boolean) => {
    dispatch({ type: 'SET_INCLUDE_CRIMINAL_COMPLAINT', payload: value });
  }, []);
  
  const setIncludeViolationsTransfer = useCallback((value: boolean) => {
    dispatch({ type: 'SET_INCLUDE_VIOLATIONS_TRANSFER', payload: value });
  }, []);
  
  const downloadMemoPdf = useCallback(async () => {
    try {
      const memoHtml = contentRefs.current.memoHtml;
      if (!memoHtml) {
        toast.error('يجب توليد المذكرة الشارحة أولاً');
        return;
      }
      
      // Dynamic import for heavy libraries
      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ]);
      
      // Create iframe for rendering
      const iframe = document.createElement('iframe');
      iframe.style.position = 'absolute';
      iframe.style.left = '-9999px';
      iframe.style.width = '794px';
      document.body.appendChild(iframe);
      
      const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
      if (!iframeDoc) {
        document.body.removeChild(iframe);
        toast.error('فشل في إنشاء PDF');
        return;
      }
      
      // Write HTML to iframe
      iframeDoc.open();
      iframeDoc.write(memoHtml);
      iframeDoc.close();
      
      // Wait for rendering
      await new Promise(resolve => setTimeout(resolve, 800));
      
      toast.info('جاري تحويل المذكرة إلى PDF...');
      
      // Capture canvas
      const canvas = await html2canvas(iframeDoc.body, {
        scale: 1.5,
        useCORS: true,
        allowTaint: true,
        logging: false,
        backgroundColor: '#ffffff',
        width: 794,
      });
      
      // Create PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
        compress: true,
      });
      
      const imgData = canvas.toDataURL('image/jpeg', 0.85);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = pdfWidth / imgWidth;
      const contentHeight = imgHeight * ratio;
      
      // Add pages if content is long
      let heightLeft = contentHeight;
      let position = 0;
      let pageCount = 0;
      
      while (heightLeft > 0 && pageCount < 10) {
        if (pageCount > 0) pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, position, pdfWidth, contentHeight, undefined, 'FAST');
        heightLeft -= pdfHeight;
        position -= pdfHeight;
        pageCount++;
      }
      
      // Cleanup
      document.body.removeChild(iframe);
      
      // Download
      const customerName = formatCustomerName(state.customer) || 'عميل';
      const fileName = `المذكرة_الشارحة_${customerName}_${state.contract?.contract_number || ''}.pdf`;
      pdf.save(fileName);
      
      toast.success('تم تحميل المذكرة بصيغة PDF');
    } catch (error) {
      console.error('Error downloading memo as PDF:', error);
      toast.error('فشل في تحميل المذكرة بصيغة PDF');
    }
  }, [state.customer, state.contract]);
  
  const downloadMemoDocx = useCallback(async () => {
    try {
      const memoHtml = contentRefs.current.memoHtml;
      if (!memoHtml) {
        toast.error('يجب توليد المذكرة الشارحة أولاً');
        return;
      }
      
      toast.info('جاري تجهيز المذكرة بصيغة Word...');
      
      const { dynamicImportWithRetry } = await import('@/utils/lazyWithRetry');
      const { downloadHtmlAsDocx } = await dynamicImportWithRetry(() => import('@/utils/document-export'));
      
      // Prepare filename
      const customerName = formatCustomerName(state.customer) || 'عميل';
      const fileName = `المذكرة_الشارحة_${customerName}_${state.contract?.contract_number || ''}.docx`;
      
      // Download using the utility function
      await downloadHtmlAsDocx(memoHtml, fileName);
      
      toast.success('تم تحميل المذكرة بصيغة Word بنفس تنسيق المعاينة');
    } catch (error) {
      console.error('Error downloading memo as Word:', error);
      toast.error(`فشل في تحميل المذكرة بصيغة Word: ${error instanceof Error ? error.message : 'خطأ غير معروف'}`);
    }
  }, [state.customer, state.contract]);
  
  const markCaseAsOpenedLegacy = useCallback(async () => {
    if (!user?.id || !companyId || !state.contract || !state.customer) {
      toast.error('بيانات غير كاملة');
      throw new Error('بيانات غير كاملة');
    }
    
    dispatch({ type: 'MARK_CASE_OPENED_START' });
    
    try {
      const contract = state.contract;
      const customer = state.customer;
      const delinquencyData = state.calculations;
      
      // 1. Update contract status to under_legal_procedure
      const { error: contractError } = await supabase
        .from('contracts')
        .update({ status: 'under_legal_procedure' })
        .eq('id', contract.id);
      
      if (contractError) throw contractError;
      
      // 2. Create legal case record
      const customerName = formatCustomerName(customer);
      const caseTitle = `قضية تحصيل مستحقات - ${customerName}`;
      
      const { data: legalCase, error: caseError } = await supabase
        .from('legal_cases')
        .insert({
          company_id: companyId,
          contract_id: contract.id,
          client_id: customer.id,
          client_name: customerName,
          client_phone: customer.phone,
          client_email: customer.email,
          case_number: `LC-${Date.now()}`,
          case_title: caseTitle,
          case_title_ar: caseTitle,
          case_type: 'collection',
          case_status: 'open',
          case_value: delinquencyData?.total || 0,
          priority: 'high',
          filing_date: new Date().toISOString(),
          created_by: user.id,
        })
        .select()
        .single();
      
      if (caseError) throw caseError;
      
      dispatch({ type: 'MARK_CASE_OPENED_COMPLETE' });
      
      toast.success('تم فتح القضية بنجاح! سيتم نقلك إلى صفحة القضايا...');
      
      // Navigate to cases page
      setTimeout(() => {
        navigate('/legal/cases?view=cases');
      }, 1500);
      
      return legalCase;
    } catch (error: any) {
      dispatch({ type: 'MARK_CASE_OPENED_ERROR', payload: error as Error });
      toast.error(`خطأ في فتح القضية: ${error.message}`);
      throw error;
    }
  }, [state, user, companyId, navigate]);
  
  void markCaseAsOpenedLegacy;

  const markCaseAsOpened = useCallback(async () => {
    if (!user?.id || !companyId || !state.contract || !state.customer) {
      toast.error('Legal case data is incomplete');
      throw new Error('Legal case data is incomplete');
    }

    dispatch({ type: 'MARK_CASE_OPENED_START' });
    try {
      const legalCase = await openLegalCase(state, user.id);
      await Promise.all([
        queryClient.invalidateQueries({
          queryKey: ['lawsuit-legal-case', companyId, state.contractId],
        }),
        queryClient.invalidateQueries({
          queryKey: ['legal-case-workflow', companyId, legalCase.caseId],
        }),
        queryClient.invalidateQueries({ queryKey: ['legal-cases'] }),
        queryClient.invalidateQueries({ queryKey: ['legal-case-stats'] }),
      ]);
      dispatch({ type: 'MARK_CASE_OPENED_COMPLETE' });
      toast.success('تم فتح القضية وتحديث حالتها بنجاح');

      // أرشفة الحزمة النهائية تلقائياً في سجل القضية (بدون حاجة لتحميل يدوي)
      void (async () => {
        try {
          const { buildDocumentsZipBlob } = await import('../utils/zipExport');
          const { blob, fileName } = await buildDocumentsZipBlob(state, contentRefs.current);
          const archivePath = `legal-packages/${companyId}/${state.contractId}/${Date.now()}_${fileName}`;
          const { error: uploadError } = await supabase.storage
            .from('contract-documents')
            .upload(archivePath, blob, { contentType: 'application/zip' });
          if (uploadError) throw uploadError;
          const { error: insertError } = await supabase.from('lawsuit_documents').insert({
            company_id: companyId,
            contract_id: state.contractId!,
            legal_case_id: legalCase.caseId,
            document_type: 'filing_package',
            document_name: `حزمة رفع الدعوى - ${fileName}`,
            file_url: archivePath,
            created_by: user.id,
          });
          if (insertError) throw insertError;
        } catch {
          // الأرشفة ثانوية؛ لا تُعطل مسار فتح القضية
        }
      })();

      setTimeout(() => navigate('/legal/cases?view=cases'), 1500);
      return legalCase;
    } catch (error) {
      dispatch({ type: 'MARK_CASE_OPENED_ERROR', payload: error as Error });
      toast.error(error instanceof Error ? error.message : 'Failed to open the legal case');
      throw error;
    }
  }, [state, user, companyId, navigate, queryClient]);

  // Check Taqadi server on mount
  useEffect(() => {
    checkTaqadiServer();
  }, [checkTaqadiServer]);

  useEffect(() => {
    const canPrepareDocuments =
      !state.ui.isLoading &&
      !state.ui.isGeneratingAll &&
      Boolean(state.contract && state.customer && state.calculations && state.taqadiData);

    if (!canPrepareDocuments || !state.contractId) return;
    if (autoGeneratedForContractRef.current === state.contractId) return;

    const generatedDocs = ['memo', 'claims', 'docsList'] as const;
    const hasPendingGeneratedDocs = generatedDocs.some((docId) =>
      ['pending', 'error'].includes(state.documents[docId].status)
    );

    if (!hasPendingGeneratedDocs) {
      autoGeneratedForContractRef.current = state.contractId;
      return;
    }

    autoGeneratedForContractRef.current = state.contractId;
    void generateAllDocuments();
  }, [
    state.ui.isLoading,
    state.ui.isGeneratingAll,
    state.contract,
    state.customer,
    state.calculations,
    state.taqadiData,
    state.contractId,
    state.documents.memo.status,
    state.documents.claims.status,
    state.documents.docsList.status,
    state.documents,
    generateAllDocuments,
  ]);

  // ==========================================
  // التشغيل التلقائي لمحلل الأدلة — بلا زر يدوي
  // ==========================================

  // 1) توليد مستند لقطة قائمة أسعار المركبة عند غياب سند أجرة المثل، ليصبح الاقتراح قابلاً للاعتماد التلقائي
  useEffect(() => {
    if (state.ui.isLoading || !state.contractId || !user?.id) return;
    if (!state.contract?.vehicle_id) return;
    if (state.litigationProfile?.retention_daily_rate) return;
    if (state.contractEvidenceDocuments.some((document) => document.document_type === 'retention_rate_evidence')) return;
    if (autoRetentionEvidenceRef.current === state.contractId) return;
    autoRetentionEvidenceRef.current = state.contractId;

    const vehicleId = state.contract.vehicle_id;
    void (async () => {
      const { data: pricing } = await supabase
        .from('vehicle_pricing')
        .select('id, daily_rate, effective_from')
        .eq('vehicle_id', vehicleId)
        .order('effective_from', { ascending: false })
        .limit(1)
        .maybeSingle();
      if (!pricing || Number(pricing.daily_rate) <= 0) return;

      const html = `<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="UTF-8"></head><body style="font-family: sans-serif; padding: 40px;">
<h2>لقطة قائمة أسعار الشركة</h2>
<p>المركبة: ${state.vehicle?.make || ''} ${state.vehicle?.model || ''} ${state.vehicle?.year || ''} - لوحة ${state.vehicle?.plate_number || '-'}</p>
<p>الأجرة اليومية المعتمدة: <strong>${Number(pricing.daily_rate).toLocaleString('en-US')} ريال قطري</strong></p>
<p>قائمة الأسعار رقم: ${pricing.id} — سارية من: ${pricing.effective_from || 'غير محدد'}</p>
<p>تاريخ اللقطة: ${new Date().toLocaleDateString('en-GB')} — مولَّدة آلياً من نظام الأسعار المعتمد.</p>
</body></html>`;
      const file = new File(
        [html],
        `لقطة-قائمة-أسعار-${state.vehicle?.plate_number || vehicleId}.html`,
        { type: 'text/html' },
      );
      await uploadEvidenceDocument(file, 'retention_rate_evidence', file.name);
    })().catch(() => {
      autoRetentionEvidenceRef.current = null;
    });
  }, [
    state.ui.isLoading,
    state.contractId,
    state.contract?.vehicle_id,
    state.vehicle,
    state.litigationProfile?.retention_daily_rate,
    state.contractEvidenceDocuments,
    user?.id,
    uploadEvidenceDocument,
  ]);

  // 2) تشغيل محلل الأدلة تلقائياً بعد انتقال المستندات — بلا زر يدوي
  useEffect(() => {
    if (state.ui.isLoading || !state.contractId || !state.contract || !state.customer || !user?.id) return;
    if (autoAnalyzedForContractRef.current === state.contractId) return;

    autoAnalyzedForContractRef.current = state.contractId;
    void analyzeLegalEvidence().catch(() => {
      autoAnalyzedForContractRef.current = null;
    });
  }, [
    state.ui.isLoading,
    state.contractId,
    state.contract,
    state.customer,
    state.contractEvidenceDocuments,
    user?.id,
    analyzeLegalEvidence,
  ]);

  // 3) تثبيت مسودة لقطة المذكرة تلقائياً؛ وكيل تقاضي يعتمدها بعد مطابقة شاشة المراجعة
  useEffect(() => {
    if (state.ui.isLoading || !state.contractId || !state.contract || !state.calculations || !state.taqadiData) return;
    if (autoFrozenSnapshotContractRef.current === state.contractId) return;
    if (getFilingReadiness(state).legalStatus.issues.length > 0) return;
    if (state.memoSnapshots.some((snapshot) => isMemoSnapshotCurrent(state, snapshot))) return;

    autoFrozenSnapshotContractRef.current = state.contractId;
    void freezeMemoSnapshot()
      .then(() => toast.success('ثُبِّتت مسودة المذكرة تلقائياً'))
      .catch(() => {
        autoFrozenSnapshotContractRef.current = null;
      });
  }, [
    state.ui.isLoading,
    state.contractId,
    state.contract,
    state.calculations,
    state.taqadiData,
    state.memoSnapshots,
    state,
    freezeMemoSnapshot,
  ]);
  
  // ==========================================
  // Context Value
  // ==========================================
  
  const value: LawsuitPreparationContextValue = {
    state,
    dispatch,
    actions: {
      generateDocument,
      generateAllDocuments,
      uploadDocument,
      registerCase: async () => { await registerCase(); },
      downloadAllAsZip,
      downloadInvoicesAsZip,
      sendToLawsuitData,
      startTaqadiAutomation,
      stopTaqadiAutomation,
      checkTaqadiServer,
      copyToClipboard,
      toggleTaqadiData,
      setIncludeCriminalComplaint,
      setIncludeViolationsTransfer,
      markCaseAsOpened: async () => { await markCaseAsOpened(); },
      saveLitigationProfile,
      saveFormalNotice,
      deleteFormalNotice,
      saveDamageCost,
      deleteDamageCost,
      freezeMemoSnapshot,
      uploadEvidenceDocument,
      analyzeLegalEvidence,
      reviewEvidenceProposal,
      downloadMemoPdf,
      downloadMemoDocx,
    },
  };
  
  return (
    <LawsuitPreparationContext.Provider value={value}>
      {children}
    </LawsuitPreparationContext.Provider>
  );
}

export default LawsuitPreparationProvider;
