/**
 * Lawsuit Preparation Context Provider
 * موفر سياق تجهيز الدعوى
 */

import React, { createContext, useContext, useReducer, useCallback, useEffect, useRef } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useUnifiedCompanyAccess } from '@/hooks/useUnifiedCompanyAccess';
import { calculateDelinquencyAmounts } from '@/utils/calculateDelinquencyAmounts';
import { generateDocument as generateDocumentUtil } from '../utils/documentGenerators';
import { openLegalCase, registerLegalCase } from '../utils/caseRegistration';
import { exportDocumentsAsZip } from '../utils/zipExport';
import { selectLegalContractDocument } from '../utils/contractDocumentSelection';
import { getCurrentLegalCase } from '../utils/taqadiFiling';
import {
  buildTaqadiFilingPayload,
  enqueueTaqadiFilingJob,
  getActiveTaqadiWorker,
} from '../utils/taqadiAutomation';
import {
  TAQADI_DEFAULT_DEFENDANT_ADDRESS,
  TAQADI_DEFAULT_DEFENDANT_EMAIL,
} from '../utils/taqadiDefaults';
import {
  buildFactsAdditions,
  buildTaqadiClaims,
  type TaqadiNarrativeInput,
} from '../utils/taqadiNarrative';
import { getLawsuitClaimAmounts } from '../utils/claimAmounts';
import {
  buildContractDocumentStoragePath,
  getLegalDocumentUploadRoute,
  validateLegalDocumentFile,
} from '../utils/documentUploadRouting';
import { lawsuitService } from '@/services/LawsuitService';
import { formatCustomerName } from '@/utils/formatCustomerName';
import { renderOfficialInvoicePdfBlob } from '@/utils/renderOfficialInvoicePdf';
import { toast } from 'sonner';

import { useFleetifyTranslation } from "@/hooks/useTranslation";
import { 
  lawsuitPreparationReducer, 
  createInitialState 
} from './reducer';
import type { 
  LawsuitPreparationContextValue, 
  LawsuitPreparationState,
  DocumentsState 
} from './types';

// ==========================================
// Context
// ==========================================

const LawsuitPreparationContext = createContext<LawsuitPreparationContextValue | null>(null);

// ==========================================
// Hook
// ==========================================

export function useLawsuitPreparationContext() {
  const { t } = useFleetifyTranslation("ui");
  const context = useContext(LawsuitPreparationContext);
  if (!context) {
    throw new Error('useLawsuitPreparationContext must be used within LawsuitPreparationProvider');
  }
  return context;
}

// ==========================================
// Provider Props
// ==========================================

interface LawsuitPreparationProviderProps {
  children: React.ReactNode;
  contractId: string;
}

// ==========================================
// Provider Component
// ==========================================

export function LawsuitPreparationProvider({ 
  children, 
  contractId 
}: LawsuitPreparationProviderProps) {
  const { user } = useAuth();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { companyId, isAuthenticating, isInitializing } = useUnifiedCompanyAccess();
  const companyLoading = isAuthenticating || isInitializing;
  
  const [state, dispatch] = useReducer(
    lawsuitPreparationReducer, 
    createInitialState(contractId)
  );
  
  // Refs to store generated content for download
  const contentRefs = useRef<{
    memoHtml: string | null;
    claimsHtml: string | null;
    criminalComplaintHtml: string | null;
    violationsTransferHtml: string | null;
  }>({
    memoHtml: null,
    claimsHtml: null,
    criminalComplaintHtml: null,
    violationsTransferHtml: null,
  });
  const autoGeneratedForContractRef = useRef<string | null>(null);
  const isMountedRef = useRef(true);

  useEffect(() => () => {
    isMountedRef.current = false;
  }, []);
  
  // Update companyId in state when available
  useEffect(() => {
    if (companyId) {
      dispatch({ type: 'SET_COMPANY_ID', payload: companyId });
    }
  }, [companyId]);
  
  // ==========================================
  // Data Fetching
  // ==========================================
  
  // Fetch contract data
  const { isLoading: contractLoading } = useQuery({
    queryKey: ['contract-details', contractId, companyId],
    staleTime: 0,
    queryFn: async () => {
      if (!companyId) throw new Error('معرف الشركة غير موجود');
      const { data: contract, error } = await supabase
        .from('contracts')
        .select('*')
        .eq('id', contractId)
        .eq('company_id', companyId)
        .single();
      
      if (error) throw error;
      if (!contract) throw new Error('لم يتم العثور على العقد');
      
      // Fetch customer
      let customer = null;
      if (contract.customer_id) {
        const { data: cust } = await supabase
          .from('customers')
          .select('id, first_name, first_name_ar, last_name, last_name_ar, customer_type, company_name, company_name_ar, national_id, nationality, phone, email, address, country')
          .eq('id', contract.customer_id)
          .eq('company_id', companyId)
          .single();
        customer = cust;
      }
      
      // Fetch vehicle
      let vehicle = null;
      if (contract.vehicle_id) {
        const { data: veh } = await supabase
          .from('vehicles')
          .select('make, model, year, plate_number, color, vin, status')
          .eq('id', contract.vehicle_id)
          .eq('company_id', companyId)
          .single();
        vehicle = veh;
      }
      
      dispatch({ 
        type: 'SET_CONTRACT_DATA', 
        payload: { contract, customer, vehicle } 
      });
      
      return { contract, customer, vehicle };
    },
    enabled: !!contractId && !!companyId,
  });
  
  // Fetch overdue invoices
  const { isLoading: invoicesLoading } = useQuery({
    queryKey: ['overdue-invoices', contractId, companyId],
    queryFn: async () => {
      if (!companyId) return [];
      const { data, error } = await supabase
        .from('invoices')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .lt('due_date', new Date().toISOString().split('T')[0]);
      
      if (error) throw error;
      
      const filtered = (data || [])
        .filter((inv) => Boolean(inv.due_date) && Number(inv.total_amount || 0) - Number(inv.paid_amount || 0) > 0)
        .map((inv) => ({
          id: inv.id,
          invoice_number: inv.invoice_number,
          due_date: inv.due_date!,
          total_amount: Number(inv.total_amount || 0),
          paid_amount: Number(inv.paid_amount || 0),
        }));
      
      dispatch({ type: 'SET_INVOICES', payload: filtered });
      return filtered;
    },
    enabled: !!contractId && !!companyId,
  });
  
  // Fetch reminder history (سجل الإعذار القانوني) for this contract
  useQuery({
    queryKey: ['contract-reminder-history', contractId, companyId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('reminder_history')
        .select('sent_at, reminder_type')
        .eq('contract_id', contractId)
        .eq('success', true)
        .order('sent_at', { ascending: false });

      if (error) throw error;

      const summary = {
        count: data?.length ?? 0,
        lastSentDate: data?.[0]?.sent_at ?? null,
        sendMethods: [...new Set(
          (data ?? [])
            .map((reminder) => reminder.reminder_type)
            .filter((type): type is string => Boolean(type)),
        )],
      };
      dispatch({ type: 'SET_PAYMENT_REMINDERS', payload: summary });
      return summary;
    },
    enabled: !!companyId && !!contractId,
  });

  // Fetch traffic violations
  const { isLoading: violationsLoading } = useQuery({
    queryKey: ['contract-traffic-violations', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];
      
      const { data, error } = await supabase
        .from('penalties')
        .select('*')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .neq('payment_status', 'paid')
        .neq('status', 'cancelled')
        .order('penalty_date', { ascending: false });
      
      if (error) throw error;
      
      const normalizedViolations = (data || []).map((violation) => ({
        id: violation.id,
        violation_number: violation.penalty_number,
        violation_date: violation.penalty_date,
        violation_type: violation.violation_type,
        location: violation.location,
        fine_amount: violation.amount,
        total_amount: violation.amount,
        status: violation.status || 'pending',
      }));

      dispatch({ type: 'SET_VIOLATIONS', payload: normalizedViolations });
      return normalizedViolations;
    },
    enabled: !!contractId && !!companyId,
  });
  
  // Fetch company legal documents
  const { isLoading: companyDocumentsLoading } = useQuery({
    queryKey: ['company-legal-documents', companyId],
    queryFn: async () => {
      if (!companyId) return [];
      const docs = await lawsuitService.getCompanyLegalDocuments(companyId);
      dispatch({ type: 'SET_COMPANY_DOCUMENTS', payload: docs });
      return docs;
    },
    enabled: !!companyId,
  });
  
  // Fetch contract document (signed contract)
  const { isLoading: contractDocumentLoading } = useQuery({
    queryKey: ['contract-document', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) {
        console.log('[Contract Document] Missing contractId or companyId');
        return null;
      }
      
      console.log('[Contract Document] Fetching for contract:', contractId);
      
      const { data, error } = await supabase
        .from('contract_documents')
        .select('id, file_path, document_name, document_type, mime_type')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .order('created_at', { ascending: false });
      
      if (error) {
        console.error('[Contract Document] Query error:', error);
        dispatch({
          type: 'UPLOAD_DOCUMENT_ERROR',
          payload: { docId: 'contract', error: 'فشل في جلب ملف العقد من قاعدة البيانات' }
        });
        return null;
      }
      
      const contractDocument = selectLegalContractDocument(data || []);

      if (!contractDocument) {
        console.warn('[Contract Document] No contract document found');
        dispatch({
          type: 'UPLOAD_DOCUMENT_ERROR',
          payload: { docId: 'contract', error: 'لم يتم العثور على ملف العقد. يرجى رفع ملف العقد الموقع.' }
        });
        return null;
      }
      
      console.log('[Contract Document] Found document:', contractDocument.document_name, 'at path:', contractDocument.file_path);

      const { data: signedUrlData, error: signedUrlError } = await supabase.storage
        .from('contract-documents')
        .createSignedUrl(contractDocument.file_path!, 3600);

      const publicUrl = signedUrlError
        ? supabase.storage.from('contract-documents').getPublicUrl(contractDocument.file_path!).data.publicUrl
        : null;
      const documentUrl = signedUrlData?.signedUrl || publicUrl;

      if (documentUrl) {
        dispatch({ 
          type: 'UPLOAD_DOCUMENT_SUCCESS', 
          payload: { docId: 'contract', url: documentUrl }
        });
      } else {
        console.error('[Contract Document] Failed to generate public URL');
        dispatch({
          type: 'UPLOAD_DOCUMENT_ERROR',
          payload: { docId: 'contract', error: 'فشل في توليد رابط الملف' }
        });
      }
      
      return contractDocument;
    },
    enabled: !!contractId && !!companyId,
  });

  const { isLoading: violationEvidenceLoading } = useQuery({
    queryKey: ['contract-violation-evidence-documents', contractId, companyId],
    queryFn: async () => {
      if (!contractId || !companyId) return [];

      const { data, error } = await supabase
        .from('contract_documents')
        .select('id, document_name, file_path, mime_type')
        .eq('contract_id', contractId)
        .eq('company_id', companyId)
        .eq('document_type', 'violations_proof')
        .order('created_at', { ascending: false });

      if (error) throw error;

      const evidenceDocuments = (await Promise.all((data || []).map(async (document) => {
        if (!document.file_path) return null;
        const { data: signedUrl, error: signedUrlError } = await supabase.storage
          .from('contract-documents')
          .createSignedUrl(document.file_path, 3600);
        if (signedUrlError || !signedUrl?.signedUrl) {
          console.error('[Violation Evidence] Failed to create signed URL:', signedUrlError);
          return null;
        }
        return {
          id: document.id,
          name: document.document_name,
          url: signedUrl.signedUrl,
          mimeType: document.mime_type,
        };
      }))).filter((document): document is NonNullable<typeof document> => Boolean(document));

      dispatch({ type: 'SET_VIOLATION_EVIDENCE_DOCUMENTS', payload: evidenceDocuments });
      return evidenceDocuments;
    },
    enabled: !!contractId && !!companyId,
  });
  
  // ==========================================
  // Derived Data (Calculations & Taqadi Data)
  // ==========================================
  
  useEffect(() => {
    if (state.overdueInvoices.length > 0 || state.trafficViolations.length > 0) {
      const calculations = calculateDelinquencyAmounts(
        state.overdueInvoices.map(inv => ({
          id: inv.id,
          invoice_number: inv.invoice_number || undefined,
          due_date: inv.due_date,
          total_amount: inv.total_amount || 0,
          paid_amount: inv.paid_amount || 0,
        })),
        state.trafficViolations.map(v => ({
          id: v.id,
          violation_number: v.violation_number || undefined,
          fine_amount: Number(v.fine_amount || 0),
          total_amount: Number(v.total_amount || 0),
          status: v.status,
        })),
        { includeDamagesFee: true }
      );
      
      dispatch({ 
        type: 'UPDATE_CALCULATIONS', 
        payload: {
          ...calculations,
          amountInWords: lawsuitService.convertAmountToWords(calculations.total),
        } 
      });
    }
  }, [state.overdueInvoices, state.trafficViolations]);
  
  useEffect(() => {
    if (state.contract && state.calculations && state.customer) {
      const customerName = formatCustomerName(state.customer, { preferArabic: true }) || 'غير محدد';
      const { cashClaimAmount, taqadiClaimAmount } = getLawsuitClaimAmounts(state.calculations);
      
      let factsText = lawsuitService.generateFactsText(
        customerName,
        state.contract.start_date,
        `${state.vehicle?.make || ''} ${state.vehicle?.model || ''} ${state.vehicle?.year || ''}`,
        cashClaimAmount
      );

      // الفروع الحتمية: سداد جزئي، مخالفات، إعذار قانوني، حيازة المركبة، انتهاء العقد
      const narrativeInput: TaqadiNarrativeInput = {
        claimAmount: cashClaimAmount,
        violationsCount: state.calculations.violationsCount,
        violationsFines: state.calculations.violationsFines,
        paidTotal: state.overdueInvoices.reduce(
          (sum, invoice) => sum + Number(invoice.paid_amount || 0),
          0,
        ),
        reminders: state.paymentReminders,
        vehicleStatus: state.vehicle?.status ?? null,
        contractEndDate: state.contract.end_date,
        contractStatus: state.contract.status ?? null,
      };

      const additions = buildFactsAdditions(narrativeInput);
      if (additions.length > 0) {
        factsText += `\n\n${additions.join('\n\n')}`;
      }

      const claimsText = buildTaqadiClaims(narrativeInput);
      
      // استخراج معلومات المدعى عليه
      const fullName = customerName;
      const nameParts = fullName.split(' ');
      const firstName = nameParts[0] || null;
      const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : null;
      const middleName = nameParts.length > 2 ? nameParts.slice(1, -1).join(' ') : null;
      
      // تحديد نوع الهوية
      let idType = 'بطاقة شخصية';
      if (state.customer.nationality === 'Qatar' || state.customer.nationality === 'قطر') {
        idType = 'بطاقة قطرية';
      } else if (
        state.customer.national_id
        && state.customer.national_id.replace(/\D/g, '').length === 11
      ) {
        idType = 'رخصة مقيم';
      }
      
      // معلومات السيارة
      const vehicleFullDesc = state.vehicle 
        ? `${state.vehicle.make || ''} ${state.vehicle.model || ''} ${state.vehicle.year || ''} - ${state.vehicle.plate_number || ''}`.trim()
        : 'غير محدد';
      
      dispatch({
        type: 'UPDATE_TAQADI_DATA',
        payload: {
          caseTitle: lawsuitService.generateCaseTitle(customerName),
          facts: factsText,
          claims: claimsText,
          amount: taqadiClaimAmount,
          amountInWords: lawsuitService.convertAmountToWords(taqadiClaimAmount),
          
          // بيانات المدعى عليه
          defendant: {
            fullName: fullName,
            firstName: firstName,
            middleName: middleName,
            lastName: lastName,
            idNumber: state.customer.national_id,
            idType: idType,
            nationality: state.customer.nationality || state.customer.country,
            phone: state.customer.phone,
            email: TAQADI_DEFAULT_DEFENDANT_EMAIL,
            address: TAQADI_DEFAULT_DEFENDANT_ADDRESS,
          },
          
          // بيانات العقد
          contract: {
            contractNumber: state.contract.contract_number,
            startDate: state.contract.start_date,
            endDate: state.contract.end_date,
            monthlyAmount: state.contract.monthly_amount,
          },
          
          // بيانات السيارة
          vehicle: {
            make: state.vehicle?.make || null,
            model: state.vehicle?.model || null,
            year: state.vehicle?.year || null,
            plateNumber: state.vehicle?.plate_number || null,
            color: state.vehicle?.color || null,
            vin: state.vehicle?.vin || null,
            fullDescription: vehicleFullDesc,
          },
        },
      });
    }
  }, [state.contract, state.calculations, state.customer, state.vehicle, state.overdueInvoices, state.paymentReminders]);
  
  // Update loading state
  useEffect(() => {
    const isLoading = companyLoading || contractLoading || invoicesLoading || violationsLoading || companyDocumentsLoading || contractDocumentLoading || violationEvidenceLoading;
    dispatch({ type: 'SET_LOADING', payload: isLoading });
  }, [companyLoading, contractLoading, invoicesLoading, violationsLoading, companyDocumentsLoading, contractDocumentLoading, violationEvidenceLoading]);
  
  // ==========================================
  // Actions
  // ==========================================
  
  // دالة لتحميل الصور (اللوقو، التوقيع، الختم) كـ Base64
  const loadImageAsBase64 = async (path: string): Promise<string> => {
    try {
      const response = await fetch(path);
      const blob = await response.blob();
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch (error) {
      console.error(`Failed to load image ${path}:`, error);
      return '';
    }
  };

  // دالة لتضمين جميع الصور في HTML
  const embedImagesInHtml = async (html: string): Promise<string> => {
    try {
      // تحميل جميع الصور
      const [logoBase64, signatureBase64, stampBase64] = await Promise.all([
        loadImageAsBase64('/receipts/logo.png'),
        loadImageAsBase64('/receipts/signature.png'),
        loadImageAsBase64('/receipts/stamp.png'),
      ]);
      
      // استبدال جميع المسارات
      let result = html;
      
      if (logoBase64) {
        result = result
          .replace(/src="\/receipts\/logo\.png"/g, `src="${logoBase64}"`)
          .replace(/src='\/receipts\/logo\.png'/g, `src='${logoBase64}'`);
      }
      
      if (signatureBase64) {
        result = result
          .replace(/src="\/receipts\/signature\.png"/g, `src="${signatureBase64}"`)
          .replace(/src='\/receipts\/signature\.png'/g, `src='${signatureBase64}'`);
      }
      
      if (stampBase64) {
        result = result
          .replace(/src="\/receipts\/stamp\.png"/g, `src="${stampBase64}"`)
          .replace(/src='\/receipts\/stamp\.png'/g, `src='${stampBase64}'`);
      }
      
      return result;
    } catch (error) {
      console.error('Failed to embed images:', error);
      return html;
    }
  };

  const generateDocument = useCallback(async (docId: keyof DocumentsState) => {
    if (!isMountedRef.current) return;
    dispatch({ type: 'GENERATE_DOCUMENT_START', payload: { docId } });
    
    try {
      // Get current state for generation
      const currentState = state;
      
      // Generate document using utility
      const { url, html: originalHtml } = await generateDocumentUtil(docId, currentState);
      
      // تضمين اللوقو والتوقيع والختم في HTML
      const html = await embedImagesInHtml(originalHtml);
      
      // إنشاء URL جديد مع الصور المضمّنة
      const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
      const urlWithImages = URL.createObjectURL(blob);
      
      // Store HTML in refs for ZIP download
      if (docId === 'memo') contentRefs.current.memoHtml = html;
      if (docId === 'claims') contentRefs.current.claimsHtml = html;
      if (docId === 'criminalComplaint') contentRefs.current.criminalComplaintHtml = html;
      if (docId === 'violationsTransfer') contentRefs.current.violationsTransferHtml = html;
      
      if (!isMountedRef.current) return;
      dispatch({
        type: 'GENERATE_DOCUMENT_SUCCESS', 
        payload: { docId, url: urlWithImages, html } 
      });
    } catch (error) {
      if (!isMountedRef.current) return;
      dispatch({
        type: 'GENERATE_DOCUMENT_ERROR', 
        payload: { docId, error: error as Error } 
      });
    }
  }, [state]);
  
  const generateAllDocuments = useCallback(async () => {
    dispatch({ type: 'GENERATE_ALL_START' });
    
    try {
      const documentsToGenerate: (keyof DocumentsState)[] = ['memo', 'claims'];
      
      if (state.trafficViolations.length > 0) {
        documentsToGenerate.push('violations', 'violationsTransfer');
      }
      
      documentsToGenerate.push('criminalComplaint', 'docsList');
      
      for (const docId of documentsToGenerate) {
        if (!isMountedRef.current) break;
        if (state.documents[docId].status !== 'ready') {
          await generateDocument(docId);
          if (!isMountedRef.current) break;
          // Small delay between generations
          await new Promise(resolve => setTimeout(resolve, 100));
        }
      }
    } finally {
      if (isMountedRef.current) {
        dispatch({ type: 'GENERATE_ALL_COMPLETE' });
      }
    }
  }, [state.documents, state.trafficViolations, generateDocument]);
  
  const uploadDocument = useCallback(async (docId: keyof DocumentsState, file: File) => {
    if (!companyId || !contractId) {
      toast.error('تعذر تحديد الشركة أو العقد');
      return;
    }
    
    dispatch({ type: 'UPLOAD_DOCUMENT_START', payload: { docId } });
    
    try {
      const route = getLegalDocumentUploadRoute(docId);
      if (!route) {
        throw new Error('هذا المستند يُنشأ من النظام ولا يقبل رفع ملف يدوي');
      }
      validateLegalDocumentFile(file, route);

      if (route.destination === 'company') {
        const uploadedDocument = await lawsuitService.uploadLegalDocument(
          companyId,
          route.documentType,
          file,
          undefined,
          `رُفع من حافظة تجهيز الدعوى للعقد ${state.contract?.contract_number || contractId}`,
          user?.id,
        );
        const nextCompanyDocuments = [
          ...state.companyDocuments.filter(
            (document) => document.document_type !== route.documentType,
          ),
          uploadedDocument,
        ];

        dispatch({ type: 'SET_COMPANY_DOCUMENTS', payload: nextCompanyDocuments });
        dispatch({
          type: 'UPLOAD_DOCUMENT_SUCCESS',
          payload: { docId, url: uploadedDocument.file_url },
        });
        queryClient.setQueryData(
          ['company-legal-documents', companyId],
          nextCompanyDocuments,
        );
      } else {
        const filePath = buildContractDocumentStoragePath({
          companyId,
          contractId,
          documentType: route.documentType,
          fileName: file.name,
        });
        const { error: uploadError } = await supabase.storage
          .from(route.bucket)
          .upload(filePath, file, {
            contentType: file.type || undefined,
            upsert: false,
          });

        if (uploadError) throw uploadError;

        const { data: savedDocument, error: dbError } = await supabase
          .from('contract_documents')
          .insert({
            contract_id: contractId,
            company_id: companyId,
            file_path: filePath,
            document_name: file.name,
            original_filename: file.name,
            document_type: route.documentType,
            mime_type: file.type || null,
            file_size: file.size,
            is_required: true,
            notes: `رُفع من حافظة تجهيز الدعوى: ${state.documents[docId].name}`,
            uploaded_by: user?.id || null,
          })
          .select('id, document_name, mime_type')
          .single();

        if (dbError || !savedDocument) {
          await supabase.storage.from(route.bucket).remove([filePath]);
          throw dbError || new Error('تعذر ربط الملف بالعقد');
        }

        const { data: signedUrlData, error: signedUrlError } = await supabase.storage
          .from(route.bucket)
          .createSignedUrl(filePath, 3600);
        if (signedUrlError || !signedUrlData?.signedUrl) {
          throw signedUrlError || new Error('تعذر إنشاء رابط معاينة الملف');
        }

        dispatch({
          type: 'UPLOAD_DOCUMENT_SUCCESS',
          payload: { docId, url: signedUrlData.signedUrl },
        });

        if (docId === 'violationsEvidence') {
          dispatch({
            type: 'SET_VIOLATION_EVIDENCE_DOCUMENTS',
            payload: [
              {
                id: savedDocument.id,
                name: savedDocument.document_name,
                url: signedUrlData.signedUrl,
                mimeType: savedDocument.mime_type,
              },
              ...state.violationEvidenceDocuments,
            ],
          });
        }

        await Promise.all([
          queryClient.invalidateQueries({
            queryKey: ['contract-document', contractId, companyId],
          }),
          queryClient.invalidateQueries({
            queryKey: ['contract-violation-evidence-documents', contractId, companyId],
          }),
          queryClient.invalidateQueries({ queryKey: ['contract-documents', contractId] }),
        ]);
      }

      toast.success(`تم رفع ${state.documents[docId].name} وحفظه في مكانه الصحيح`);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'فشل رفع الملف';
      dispatch({
        type: 'UPLOAD_DOCUMENT_ERROR',
        payload: { docId, error: message },
      });
      toast.error(message);
    }
  }, [companyId, contractId, queryClient, state.companyDocuments, state.contract?.contract_number, state.documents, state.violationEvidenceDocuments, user?.id]);
  
  const registerCase = useCallback(async () => {
    if (!user?.id) {
      throw new Error('المستخدم غير مسجل الدخول');
    }
    
    dispatch({ type: 'REGISTER_CASE_START' });
    
    try {
      const result = await registerLegalCase(state, user.id);
      
      dispatch({ type: 'REGISTER_CASE_COMPLETE' });
      await queryClient.invalidateQueries({
        queryKey: ['lawsuit-legal-case', companyId, contractId],
      });
      toast.success('تم تسجيل القضية وربطها بملف التجهيز');
      
      return result;
    } catch (error) {
      dispatch({ type: 'REGISTER_CASE_ERROR', payload: error as Error });
      throw error;
    }
  }, [state, user, queryClient, companyId, contractId]);
  
  /**
   * توليد HTML للفاتورة
   */
  const generateInvoiceHtml = async (invoice: any, customer: any, contract: any): Promise<string> => {
    const totalAmount = Number(invoice.total_amount) || 0;
    const paidAmount = Number(invoice.paid_amount) || 0;
    const remainingAmount = totalAmount - paidAmount;
    
    const customerName = customer 
      ? formatCustomerName(customer)
      : 'غير محدد';
    
    const formattedDate = invoice.invoice_date 
      ? new Date(invoice.invoice_date).toLocaleDateString('ar-QA')
      : new Date().toLocaleDateString('ar-QA');
    
    return `
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
  <meta charset="UTF-8">
  <title>فاتورة ${invoice.invoice_number}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Arial', 'Tahoma', sans-serif;
      background: #fff;
      padding: 20px;
      direction: rtl;
    }
    .invoice-container {
      max-width: 210mm;
      margin: 0 auto;
      background: #fff;
      border: 2px solid #1a5490;
      border-radius: 8px;
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #1a5490 0%, #2196F3 100%);
      color: white;
      padding: 30px;
      text-align: center;
    }
    .header h1 {
      font-size: 28px;
      margin-bottom: 10px;
    }
    .header p {
      font-size: 14px;
      opacity: 0.9;
    }
    .content {
      padding: 30px;
    }
    .info-row {
      display: flex;
      justify-content: space-between;
      padding: 12px;
      border-bottom: 1px solid #e0e0e0;
    }
    .info-label {
      font-weight: bold;
      color: #1a5490;
    }
    .amount-box {
      background: #f5f5f5;
      border: 2px solid #1a5490;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
      text-align: center;
    }
    .amount-box .label {
      font-size: 14px;
      color: #666;
      margin-bottom: 10px;
    }
    .amount-box .value {
      font-size: 32px;
      font-weight: bold;
      color: #1a5490;
    }
    .status-badge {
      display: inline-block;
      padding: 8px 16px;
      border-radius: 20px;
      font-weight: bold;
      font-size: 14px;
    }
    .status-unpaid {
      background: #ffebee;
      color: #c62828;
    }
    .footer {
      background: #f5f5f5;
      padding: 20px;
      text-align: center;
      border-top: 2px solid #1a5490;
    }
  </style>
</head>
<body>
  <div class="invoice-container">
    <div class="header">
      <h1>فاتورة مستحقة</h1>
      <p>شركة العراف لتأجير السيارات</p>
      <p>{t("alarafCarRentalCompany")}</p>
    </div>
    
    <div class="content">
      <div class="info-row">
        <span class="info-label">رقم الفاتورة:</span>
        <span>${invoice.invoice_number || '-'}</span>
      </div>
      <div class="info-row">
        <span class="info-label">تاريخ الفاتورة:</span>
        <span>${formattedDate}</span>
      </div>
      <div class="info-row">
        <span class="info-label">اسم العميل:</span>
        <span>${customerName}</span>
      </div>
      <div class="info-row">
        <span class="info-label">رقم العقد:</span>
        <span>${contract?.contract_number || '-'}</span>
      </div>
      <div class="info-row">
        <span class="info-label">الوصف:</span>
        <span>${invoice.description || 'فاتورة إيجار شهري'}</span>
      </div>
      
      <div class="amount-box">
        <div class="label">المبلغ الإجمالي</div>
        <div class="value">${totalAmount.toLocaleString('en-US')} ر.ق</div>
      </div>
      
      ${paidAmount > 0 ? `
      <div class="info-row">
        <span class="info-label">المبلغ المدفوع:</span>
        <span style="color: #4caf50; font-weight: bold;">${paidAmount.toLocaleString('en-US')} ر.ق</span>
      </div>
      ` : ''}
      
      ${remainingAmount > 0 ? `
      <div class="info-row">
        <span class="info-label">المبلغ المتبقي:</span>
        <span style="color: #c62828; font-weight: bold;">${remainingAmount.toLocaleString('en-US')} ر.ق</span>
      </div>
      ` : ''}
      
      <div style="text-align: center; margin-top: 20px;">
        <span class="status-badge status-unpaid">مستحقة الدفع</span>
      </div>
    </div>
    
    <div class="footer">
      <p style="color: #666; font-size: 12px;">
        أم صلال محمد – الشارع التجاري – مبنى (79) – الطابق الأول – مكتب (2)
      </p>
      <p style="color: #666; font-size: 12px; margin-top: 5px;">
        هاتف: +974 4444 4444 | البريد الإلكتروني: info@alaraf.qa
      </p>
    </div>
  </div>
</body>
</html>
    `;
  };
  
  /**
   * تحميل جميع الفواتير المستحقة كملف ZIP
   */
  const downloadInvoicesAsZip = useCallback(async () => {
    try {
      if (state.overdueInvoices.length === 0) {
        toast.error('لا توجد فواتير مستحقة');
        return;
      }
      
      dispatch({ type: 'SET_DOWNLOADING_INVOICES', payload: true });
      toast.info('جاري تجهيز الفواتير...');
      
      // Dynamic import for heavy libraries
      const [{ default: JSZip }] = await Promise.all([
        import('jszip'),
      ]);
      
      const zip = new JSZip();
      const invoicesFolder = zip.folder('invoices');
      
      if (!invoicesFolder) {
        throw new Error('فشل في إنشاء مجلد الفواتير');
      }
      
      // توليد PDF لكل فاتورة
      for (let i = 0; i < state.overdueInvoices.length; i++) {
        const invoice = state.overdueInvoices[i];
        
        toast.info(`جاري معالجة الفاتورة ${i + 1} من ${state.overdueInvoices.length}...`);
        
        const customerName = formatCustomerName(state.customer) || undefined;
        const pdfBlob = await renderOfficialInvoicePdfBlob(invoice, customerName);
        const fileName = `فاتورة_${invoice.invoice_number || i + 1}.pdf`;
        invoicesFolder.file(fileName, pdfBlob);
      }
      
      // Generate ZIP
      toast.info('جاري ضغط الفواتير...');
      const zipBlob = await zip.generateAsync({ type: 'blob' });
      
      // Download
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `فواتير_${state.contract?.contract_number || 'العقد'}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.success(`تم تحميل ${state.overdueInvoices.length} فاتورة بنجاح`);
    } catch (error: any) {
      console.error('Error downloading invoices:', error);
      toast.error(`خطأ في تحميل الفواتير: ${error.message}`);
    } finally {
      dispatch({ type: 'SET_DOWNLOADING_INVOICES', payload: false });
    }
  }, [state.overdueInvoices, state.customer, state.contract]);
  
  const downloadAllAsZip = useCallback(async () => {
    dispatch({ type: 'DOWNLOAD_ZIP_START' });
    
    try {
      await exportDocumentsAsZip(state, contentRefs.current);
    } finally {
      dispatch({ type: 'DOWNLOAD_ZIP_COMPLETE' });
    }
  }, [state]);
  
  const sendToLawsuitData = useCallback(async () => {
    dispatch({ type: 'SEND_TO_LAWSUIT_DATA_START' });
    
    try {
      if (!state.taqadiData || !companyId || !state.contract) return;
      
      const customer = state.customer;
      const fullName = formatCustomerName(customer, { preferArabic: true });
      const nameParts = fullName.split(' ');
      
      const lawsuitRecord = {
        company_id: companyId,
        case_title: state.taqadiData.caseTitle,
        facts: state.taqadiData.facts,
        requests: state.taqadiData.claims,
        claim_amount: state.taqadiData.amount,
        claim_amount_words: state.taqadiData.amountInWords,
        defendant_first_name: nameParts[0] || '',
        defendant_middle_name: nameParts.length > 2 ? nameParts.slice(1, -1).join(' ') : null,
        defendant_last_name: nameParts.length > 1 ? nameParts[nameParts.length - 1] : '',
        defendant_nationality: customer?.nationality || customer?.country || null,
        defendant_id_number: customer?.national_id || null,
        defendant_address: TAQADI_DEFAULT_DEFENDANT_ADDRESS,
        defendant_phone: customer?.phone || null,
        defendant_email: TAQADI_DEFAULT_DEFENDANT_EMAIL,
        contract_id: contractId,
        customer_id: customer?.id || null,
      };
      
      const { error } = await supabase
        .from('lawsuit_templates')
        .insert([lawsuitRecord]);
      
      if (error) throw error;
      
    } finally {
      dispatch({ type: 'SEND_TO_LAWSUIT_DATA_COMPLETE' });
    }
  }, [state.taqadiData, state.contract, state.customer, companyId, contractId]);
  
  const startTaqadiAutomation = useCallback(async () => {
    dispatch({ type: 'TAQADI_AUTOMATION_START' });

    try {
      if (!companyId || !user?.id) {
        throw new Error('تعذر تحديد الشركة أو المستخدم');
      }

      let legalCase = await getCurrentLegalCase(companyId, contractId);
      if (!legalCase) {
        const registered = await registerLegalCase(state, user.id);
        legalCase = {
          id: registered.caseId,
          case_number: registered.caseNumber,
          case_status: 'pending',
          workflow_stage: 'preparation',
          case_reference: null,
          court_fees: null,
          filing_date: null,
          created_at: null,
        };
      }
      const currentStage = legalCase.workflow_stage || 'preparation';
      if (['closed', 'cancelled'].includes(currentStage)) {
        throw new Error('القضية مغلقة أو ملغاة. أعد فتحها قبل إرسالها إلى تقاضي');
      }
      if (!['preparation', 'filed'].includes(currentStage)) {
        throw new Error('القضية تجاوزت مرحلة الرفع ولا يمكن إرسالها إلى تقاضي مرة أخرى');
      }
      if (currentStage === 'filed' && legalCase.case_reference) {
        throw new Error(`الدعوى مرفوعة مسبقًا في تقاضي بالمرجع ${legalCase.case_reference}`);
      }

      dispatch({
        type: 'TAQADI_AUTOMATION_STATUS',
        payload: 'جاري فحص الحزمة وإضافتها إلى طابور تقاضي...',
      });
      const payload = buildTaqadiFilingPayload(state, window.location.href);
      const job = await enqueueTaqadiFilingJob({
        companyId,
        legalCaseId: legalCase.id,
        payload,
      });

      await Promise.all([
        queryClient.invalidateQueries({
          queryKey: ['taqadi-filing-job', companyId, legalCase.id],
        }),
        queryClient.invalidateQueries({ queryKey: ['lawsuit-legal-case', companyId, contractId] }),
        queryClient.invalidateQueries({ queryKey: ['legal-case-workflow', companyId, legalCase.id] }),
        queryClient.invalidateQueries({ queryKey: ['legal-cases'] }),
      ]);

      dispatch({
        type: 'TAQADI_AUTOMATION_STATUS',
        payload: `تمت إضافة الدعوى إلى طابور الرفع. رقم العملية: ${job.id}`,
      });
      toast.success('تمت إضافة الدعوى إلى طابور تقاضي');
    } catch (error: any) {
      dispatch({
        type: 'TAQADI_AUTOMATION_STATUS',
        payload: `خطأ: ${error?.message || 'تعذر إضافة الدعوى إلى الطابور'}`,
      });
      toast.error(error?.message || 'تعذر إضافة الدعوى إلى الطابور');
    } finally {
      dispatch({ type: 'TAQADI_AUTOMATION_STOP' });
    }
  }, [
    companyId,
    contractId,
    queryClient,
    state,
    user?.id,
  ]);
  
  const stopTaqadiAutomation = useCallback(() => {
    dispatch({ type: 'TAQADI_AUTOMATION_STOP' });
  }, []);
  
  const checkTaqadiServer = useCallback(async () => {
    try {
      const worker = await getActiveTaqadiWorker();
      const heartbeatAge = worker
        ? Date.now() - new Date(worker.heartbeat_at).getTime()
        : Number.POSITIVE_INFINITY;
      const isRunning = heartbeatAge < 45_000 && worker?.status !== 'offline';
      dispatch({ type: 'SET_TAQADI_SERVER_STATUS', payload: isRunning });
      return isRunning;
    } catch {
      dispatch({ type: 'SET_TAQADI_SERVER_STATUS', payload: false });
      return false;
    }
  }, []);
  
  const copyToClipboard = useCallback(async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text);
      dispatch({ type: 'SET_COPIED_FIELD', payload: field });
      setTimeout(() => {
        dispatch({ type: 'SET_COPIED_FIELD', payload: null });
      }, 2000);
    } catch {
      console.error('Failed to copy');
    }
  }, []);
  
  const toggleTaqadiData = useCallback(() => {
    dispatch({ type: 'TOGGLE_TAQADI_DATA' });
  }, []);
  
  const setIncludeCriminalComplaint = useCallback((value: boolean) => {
    dispatch({ type: 'SET_INCLUDE_CRIMINAL_COMPLAINT', payload: value });
  }, []);
  
  const setIncludeViolationsTransfer = useCallback((value: boolean) => {
    dispatch({ type: 'SET_INCLUDE_VIOLATIONS_TRANSFER', payload: value });
  }, []);
  
  const downloadMemoPdf = useCallback(async () => {
    try {
      const memoHtml = contentRefs.current.memoHtml;
      if (!memoHtml) {
        toast.error('يجب توليد المذكرة الشارحة أولاً');
        return;
      }
      
      // Dynamic import for heavy libraries
      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ]);
      
      // Create iframe for rendering
      const iframe = document.createElement('iframe');
      iframe.style.position = 'absolute';
      iframe.style.left = '-9999px';
      iframe.style.width = '794px';
      document.body.appendChild(iframe);
      
      const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
      if (!iframeDoc) {
        document.body.removeChild(iframe);
        toast.error('فشل في إنشاء PDF');
        return;
      }
      
      // Write HTML to iframe
      iframeDoc.open();
      iframeDoc.write(memoHtml);
      iframeDoc.close();
      
      // Wait for rendering
      await new Promise(resolve => setTimeout(resolve, 800));
      
      toast.info('جاري تحويل المذكرة إلى PDF...');
      
      // Capture canvas
      const canvas = await html2canvas(iframeDoc.body, {
        scale: 1.5,
        useCORS: true,
        allowTaint: true,
        logging: false,
        backgroundColor: '#ffffff',
        width: 794,
      });
      
      // Create PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
        compress: true,
      });
      
      const imgData = canvas.toDataURL('image/jpeg', 0.85);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = pdfWidth / imgWidth;
      const contentHeight = imgHeight * ratio;
      
      // Add pages if content is long
      let heightLeft = contentHeight;
      let position = 0;
      let pageCount = 0;
      
      while (heightLeft > 0 && pageCount < 10) {
        if (pageCount > 0) pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, position, pdfWidth, contentHeight, undefined, 'FAST');
        heightLeft -= pdfHeight;
        position -= pdfHeight;
        pageCount++;
      }
      
      // Cleanup
      document.body.removeChild(iframe);
      
      // Download
      const customerName = formatCustomerName(state.customer) || 'عميل';
      const fileName = `المذكرة_الشارحة_${customerName}_${state.contract?.contract_number || ''}.pdf`;
      pdf.save(fileName);
      
      toast.success('تم تحميل المذكرة بصيغة PDF');
    } catch (error) {
      console.error('Error downloading memo as PDF:', error);
      toast.error('فشل في تحميل المذكرة بصيغة PDF');
    }
  }, [state.customer, state.contract]);
  
  const downloadMemoDocx = useCallback(async () => {
    try {
      const memoHtml = contentRefs.current.memoHtml;
      if (!memoHtml) {
        toast.error('يجب توليد المذكرة الشارحة أولاً');
        return;
      }
      
      toast.info('جاري تجهيز المذكرة بصيغة Word...');
      
      const { dynamicImportWithRetry } = await import('@/utils/lazyWithRetry');
      const { downloadHtmlAsDocx } = await dynamicImportWithRetry(() => import('@/utils/document-export'));
      
      // Prepare filename
      const customerName = formatCustomerName(state.customer) || 'عميل';
      const fileName = `المذكرة_الشارحة_${customerName}_${state.contract?.contract_number || ''}.docx`;
      
      // Download using the utility function
      await downloadHtmlAsDocx(memoHtml, fileName);
      
      toast.success('تم تحميل المذكرة بصيغة Word بنفس تنسيق المعاينة');
    } catch (error) {
      console.error('Error downloading memo as Word:', error);
      toast.error(`فشل في تحميل المذكرة بصيغة Word: ${error instanceof Error ? error.message : 'خطأ غير معروف'}`);
    }
  }, [state.customer, state.contract]);
  
  const markCaseAsOpenedLegacy = useCallback(async () => {
    if (!user?.id || !companyId || !state.contract || !state.customer) {
      toast.error('بيانات غير كاملة');
      throw new Error('بيانات غير كاملة');
    }
    
    dispatch({ type: 'MARK_CASE_OPENED_START' });
    
    try {
      const contract = state.contract;
      const customer = state.customer;
      const delinquencyData = state.calculations;
      
      // 1. Update contract status to under_legal_procedure
      const { error: contractError } = await supabase
        .from('contracts')
        .update({ status: 'under_legal_procedure' })
        .eq('id', contract.id);
      
      if (contractError) throw contractError;
      
      // 2. Create legal case record
      const customerName = formatCustomerName(customer);
      const caseTitle = `قضية تحصيل مستحقات - ${customerName}`;
      
      const { data: legalCase, error: caseError } = await supabase
        .from('legal_cases')
        .insert({
          company_id: companyId,
          contract_id: contract.id,
          client_id: customer.id,
          client_name: customerName,
          client_phone: customer.phone,
          client_email: customer.email,
          case_number: `LC-${Date.now()}`,
          case_title: caseTitle,
          case_title_ar: caseTitle,
          case_type: 'collection',
          case_status: 'open',
          case_value: delinquencyData?.total || 0,
          priority: 'high',
          filing_date: new Date().toISOString(),
          created_by: user.id,
        })
        .select()
        .single();
      
      if (caseError) throw caseError;
      
      dispatch({ type: 'MARK_CASE_OPENED_COMPLETE' });
      
      toast.success('تم فتح القضية بنجاح! سيتم نقلك إلى صفحة القضايا...');
      
      // Navigate to cases page
      setTimeout(() => {
        navigate('/legal/cases?view=cases');
      }, 1500);
      
      return legalCase;
    } catch (error: any) {
      dispatch({ type: 'MARK_CASE_OPENED_ERROR', payload: error as Error });
      toast.error(`خطأ في فتح القضية: ${error.message}`);
      throw error;
    }
  }, [state, user, companyId, navigate]);
  
  void markCaseAsOpenedLegacy;

  const markCaseAsOpened = useCallback(async () => {
    if (!user?.id || !companyId || !state.contract || !state.customer) {
      toast.error('Legal case data is incomplete');
      throw new Error('Legal case data is incomplete');
    }

    dispatch({ type: 'MARK_CASE_OPENED_START' });
    try {
      const legalCase = await openLegalCase(state, user.id);
      await Promise.all([
        queryClient.invalidateQueries({
          queryKey: ['lawsuit-legal-case', companyId, state.contractId],
        }),
        queryClient.invalidateQueries({
          queryKey: ['legal-case-workflow', companyId, legalCase.caseId],
        }),
        queryClient.invalidateQueries({ queryKey: ['legal-cases'] }),
        queryClient.invalidateQueries({ queryKey: ['legal-case-stats'] }),
      ]);
      dispatch({ type: 'MARK_CASE_OPENED_COMPLETE' });
      toast.success('تم فتح القضية وتحديث حالتها بنجاح');
      setTimeout(() => navigate('/legal/cases?view=cases'), 1500);
      return legalCase;
    } catch (error) {
      dispatch({ type: 'MARK_CASE_OPENED_ERROR', payload: error as Error });
      toast.error(error instanceof Error ? error.message : 'Failed to open the legal case');
      throw error;
    }
  }, [state, user, companyId, navigate, queryClient]);

  // Check Taqadi server on mount
  useEffect(() => {
    checkTaqadiServer();
  }, [checkTaqadiServer]);

  useEffect(() => {
    const canPrepareDocuments =
      !state.ui.isLoading &&
      !state.ui.isGeneratingAll &&
      Boolean(state.contract && state.customer && state.calculations && state.taqadiData);

    if (!canPrepareDocuments || !state.contractId) return;
    if (autoGeneratedForContractRef.current === state.contractId) return;

    const generatedDocs = ['memo', 'claims', 'docsList'] as const;
    const hasPendingGeneratedDocs = generatedDocs.some((docId) =>
      ['pending', 'error'].includes(state.documents[docId].status)
    );

    if (!hasPendingGeneratedDocs) {
      autoGeneratedForContractRef.current = state.contractId;
      return;
    }

    autoGeneratedForContractRef.current = state.contractId;
    void generateAllDocuments();
  }, [
    state.ui.isLoading,
    state.ui.isGeneratingAll,
    state.contract,
    state.customer,
    state.calculations,
    state.taqadiData,
    state.contractId,
    state.documents.memo.status,
    state.documents.claims.status,
    state.documents.docsList.status,
    generateAllDocuments,
  ]);
  
  // ==========================================
  // Context Value
  // ==========================================
  
  const value: LawsuitPreparationContextValue = {
    state,
    dispatch,
    actions: {
      generateDocument,
      generateAllDocuments,
      uploadDocument,
      registerCase: async () => { await registerCase(); },
      downloadAllAsZip,
      downloadInvoicesAsZip,
      sendToLawsuitData,
      startTaqadiAutomation,
      stopTaqadiAutomation,
      checkTaqadiServer,
      copyToClipboard,
      toggleTaqadiData,
      setIncludeCriminalComplaint,
      setIncludeViolationsTransfer,
      markCaseAsOpened: async () => { await markCaseAsOpened(); },
      downloadMemoPdf,
      downloadMemoDocx,
    },
  };
  
  return (
    <LawsuitPreparationContext.Provider value={value}>
      {children}
    </LawsuitPreparationContext.Provider>
  );
}

export default LawsuitPreparationProvider;
