-- Replace the shared contract-scanner secret with one Vault identity per
-- scheduled agent. Plaintext values never leave Vault except in the outbound
-- pg_net request to the matching Edge Function.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault;

CREATE TABLE IF NOT EXISTS public.agent_invocation_registry (
  agent_id text PRIMARY KEY,
  vault_secret_name text NOT NULL UNIQUE,
  allowed_company_id uuid NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.agent_invocation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id text NOT NULL REFERENCES public.agent_invocation_registry(agent_id) ON DELETE RESTRICT,
  company_id uuid NULL REFERENCES public.companies(id) ON DELETE SET NULL,
  request_id text NULL,
  invoked_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_invocation_events_agent_time
  ON public.agent_invocation_events(agent_id, invoked_at DESC);

ALTER TABLE public.agent_invocation_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_invocation_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.agent_invocation_registry FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.agent_invocation_events FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.agent_invocation_registry TO service_role;
GRANT SELECT, INSERT ON TABLE public.agent_invocation_events TO service_role;

DO $identities$
DECLARE
  v_identity record;
BEGIN
  FOR v_identity IN
    SELECT *
    FROM (VALUES
      ('violation-inbox-processor', 'agent_secret_violation_inbox', '24bc0b21-4e2d-4413-9842-31719a3669f4'::uuid),
      ('nightly-ops-auditor', 'agent_secret_nightly_ops', '24bc0b21-4e2d-4413-9842-31719a3669f4'::uuid),
      ('smart-contract-assigner', 'agent_secret_smart_contract_assigner', '24bc0b21-4e2d-4413-9842-31719a3669f4'::uuid),
      ('customer-duplicate-detector', 'agent_secret_customer_duplicate_detector', '24bc0b21-4e2d-4413-9842-31719a3669f4'::uuid),
      ('contract-id-scanner', 'agent_secret_contract_id_scanner', '24bc0b21-4e2d-4413-9842-31719a3669f4'::uuid),
      ('customer-proposal-ai-reviewer', 'agent_secret_customer_proposal_reviewer', '24bc0b21-4e2d-4413-9842-31719a3669f4'::uuid),
      ('contract-terms-scanner', 'agent_secret_contract_terms_scanner', '24bc0b21-4e2d-4413-9842-31719a3669f4'::uuid)
    ) AS identities(agent_id, secret_name, allowed_company_id)
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM vault.secrets secret WHERE secret.name = v_identity.secret_name
    ) THEN
      PERFORM vault.create_secret(
        pg_catalog.encode(extensions.gen_random_bytes(32), 'hex'),
        v_identity.secret_name,
        'Dedicated scheduled identity for ' || v_identity.agent_id
      );
    END IF;

    INSERT INTO public.agent_invocation_registry (
      agent_id,
      vault_secret_name,
      allowed_company_id,
      enabled,
      updated_at
    ) VALUES (
      v_identity.agent_id,
      v_identity.secret_name,
      v_identity.allowed_company_id,
      true,
      now()
    )
    ON CONFLICT (agent_id) DO UPDATE
    SET vault_secret_name = EXCLUDED.vault_secret_name,
        allowed_company_id = EXCLUDED.allowed_company_id,
        enabled = true,
        updated_at = now();
  END LOOP;
END;
$identities$;

CREATE OR REPLACE FUNCTION public.verify_scheduled_agent_invocation_v1(
  p_agent_id text,
  p_company_id uuid,
  p_supplied_secret text,
  p_request_id text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_registry public.agent_invocation_registry%ROWTYPE;
  v_expected_secret text;
BEGIN
  IF NULLIF(p_agent_id, '') IS NULL
     OR NULLIF(p_supplied_secret, '') IS NULL
     OR pg_catalog.length(p_supplied_secret) < 32 THEN
    RETURN false;
  END IF;

  SELECT registry.*
  INTO v_registry
  FROM public.agent_invocation_registry registry
  WHERE registry.agent_id = p_agent_id
    AND registry.enabled = true;

  IF v_registry.agent_id IS NOT NULL THEN
    SELECT secret.decrypted_secret
    INTO v_expected_secret
    FROM vault.decrypted_secrets secret
    WHERE secret.name = v_registry.vault_secret_name;
  END IF;

  IF v_registry.agent_id IS NULL OR v_expected_secret IS NULL THEN
    RETURN false;
  END IF;

  IF v_registry.allowed_company_id IS NOT NULL
     AND p_company_id IS DISTINCT FROM v_registry.allowed_company_id THEN
    RETURN false;
  END IF;

  -- The same company control used by the system-audit worker is the global
  -- operational gate for every scheduled writer/reviewer in this cutover.
  -- No control row means enabled for backward compatibility; an explicit
  -- disable, pause or kill switch prevents the invocation before any work.
  IF p_company_id IS NOT NULL AND EXISTS (
    SELECT 1
    FROM public.system_agent_controls control
    WHERE control.company_id = p_company_id
      AND (
        NOT control.enabled
        OR control.paused
        OR control.kill_switch
      )
  ) THEN
    RETURN false;
  END IF;

  IF extensions.digest(pg_catalog.convert_to(p_supplied_secret, 'UTF8'), 'sha256')
     IS DISTINCT FROM
     extensions.digest(pg_catalog.convert_to(v_expected_secret, 'UTF8'), 'sha256') THEN
    RETURN false;
  END IF;

  INSERT INTO public.agent_invocation_events (
    agent_id,
    company_id,
    request_id
  ) VALUES (
    p_agent_id,
    p_company_id,
    NULLIF(pg_catalog.left(COALESCE(p_request_id, ''), 200), '')
  );

  RETURN true;
END;
$function$;

REVOKE ALL ON FUNCTION public.verify_scheduled_agent_invocation_v1(text,uuid,text,text)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_scheduled_agent_invocation_v1(text,uuid,text,text)
TO service_role;

CREATE OR REPLACE FUNCTION public.contract_terms_scan_batch_candidates_v2(
  p_company_id uuid,
  p_limit integer DEFAULT 4
)
RETURNS TABLE (
  contract_id uuid,
  company_id uuid,
  document_id uuid,
  contract_number text,
  contract_amount numeric,
  expected_amount numeric
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT
    contract.id,
    contract.company_id,
    document.id,
    contract.contract_number,
    contract.contract_amount,
    round(contract.monthly_amount * GREATEST(1, (
      (EXTRACT(YEAR FROM date_trunc('month', contract.end_date))
        - EXTRACT(YEAR FROM date_trunc('month', contract.start_date))) * 12
      + EXTRACT(MONTH FROM date_trunc('month', contract.end_date))
      - EXTRACT(MONTH FROM date_trunc('month', contract.start_date))
      + 1
    )::integer), 2)
  FROM public.contracts contract
  JOIN LATERAL (
    SELECT doc.id
    FROM public.contract_documents doc
    WHERE doc.contract_id = contract.id
      AND doc.company_id = contract.company_id
      AND doc.document_type IN ('signed_contract', 'signed_contract_image')
      AND doc.file_path IS NOT NULL
    ORDER BY doc.created_at DESC
    LIMIT 1
  ) document ON true
  WHERE contract.company_id = p_company_id
    AND contract.status IN ('active', 'under_legal_procedure')
    AND COALESCE(contract.monthly_amount, 0) > 0
    AND contract.start_date IS NOT NULL
    AND contract.end_date IS NOT NULL
    AND contract.end_date >= contract.start_date
    AND abs(contract.contract_amount - round(
      contract.monthly_amount * GREATEST(1, (
        (EXTRACT(YEAR FROM date_trunc('month', contract.end_date))
          - EXTRACT(YEAR FROM date_trunc('month', contract.start_date))) * 12
        + EXTRACT(MONTH FROM date_trunc('month', contract.end_date))
        - EXTRACT(MONTH FROM date_trunc('month', contract.start_date))
        + 1
      )::integer), 2
    )) > 1
    AND NOT EXISTS (
      SELECT 1
      FROM public.contract_terms_scan_proposals proposal
      WHERE proposal.contract_id = contract.id
        AND proposal.status = 'pending'
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.contract_terms_scan_proposals proposal
      WHERE proposal.contract_id = contract.id
        AND proposal.status = 'applied'
        AND proposal.created_at > now() - interval '30 days'
    )
  ORDER BY contract.updated_at ASC, contract.id
  LIMIT GREATEST(COALESCE(p_limit, 4), 1);
$function$;

REVOKE ALL ON FUNCTION public.contract_terms_scan_batch_candidates_v2(uuid,integer)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.contract_terms_scan_batch_candidates_v2(uuid,integer)
TO service_role;

DO $preflight$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM vault.decrypted_secrets WHERE name = 'supabase_project_url'
  ) THEN
    RAISE EXCEPTION 'Vault secret supabase_project_url is required';
  END IF;
END;
$preflight$;

SELECT cron.unschedule(job.jobid)
FROM cron.job job
WHERE job.jobname IN (
  'violation-inbox-processor',
  'nightly-ops-auditor',
  'smart-contract-assigner',
  'customer-duplicate-detector',
  'contract-id-scanner',
  'customer-proposal-ai-reviewer',
  'nightly-contract-terms-scan'
);

SELECT cron.schedule(
  'violation-inbox-processor',
  '*/15 * * * *',
  $command$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_project_url' LIMIT 1) || '/functions/v1/violation-inbox-processor',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-id', 'violation-inbox-processor',
      'x-agent-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'agent_secret_violation_inbox' LIMIT 1)
    ),
    body := jsonb_build_object('companyId', '24bc0b21-4e2d-4413-9842-31719a3669f4', 'limit', 5)
  );
  $command$
);

SELECT cron.schedule(
  'nightly-ops-auditor',
  '30 2 * * *',
  $command$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_project_url' LIMIT 1) || '/functions/v1/nightly-ops-auditor',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-id', 'nightly-ops-auditor',
      'x-agent-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'agent_secret_nightly_ops' LIMIT 1)
    ),
    body := jsonb_build_object('companyId', '24bc0b21-4e2d-4413-9842-31719a3669f4')
  );
  $command$
);

SELECT cron.schedule(
  'smart-contract-assigner',
  '0,30 * * * *',
  $command$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_project_url' LIMIT 1) || '/functions/v1/smart-contract-assigner',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-id', 'smart-contract-assigner',
      'x-agent-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'agent_secret_smart_contract_assigner' LIMIT 1)
    ),
    body := jsonb_build_object(
      'companyId', '24bc0b21-4e2d-4413-9842-31719a3669f4',
      'mode', CASE WHEN EXTRACT(HOUR FROM now()) = 3 THEN 'rebalance' ELSE 'assign_new' END
    )
  );
  $command$
);

SELECT cron.schedule(
  'customer-duplicate-detector',
  '0 4 * * *',
  $command$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_project_url' LIMIT 1) || '/functions/v1/customer-duplicate-detector',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-id', 'customer-duplicate-detector',
      'x-agent-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'agent_secret_customer_duplicate_detector' LIMIT 1)
    ),
    body := jsonb_build_object('companyId', '24bc0b21-4e2d-4413-9842-31719a3669f4')
  );
  $command$
);

SELECT cron.schedule(
  'contract-id-scanner',
  '*/15 * * * *',
  $command$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_project_url' LIMIT 1) || '/functions/v1/contract-id-scanner',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-id', 'contract-id-scanner',
      'x-agent-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'agent_secret_contract_id_scanner' LIMIT 1)
    ),
    body := jsonb_build_object(
      'mode', 'batch',
      'companyId', '24bc0b21-4e2d-4413-9842-31719a3669f4',
      'limit', 10
    )
  );
  $command$
);

SELECT cron.schedule(
  'customer-proposal-ai-reviewer',
  '*/15 * * * *',
  $command$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_project_url' LIMIT 1) || '/functions/v1/customer-proposal-ai-reviewer',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-id', 'customer-proposal-ai-reviewer',
      'x-agent-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'agent_secret_customer_proposal_reviewer' LIMIT 1)
    ),
    body := jsonb_build_object(
      'mode', 'batch',
      'companyId', '24bc0b21-4e2d-4413-9842-31719a3669f4',
      'limit', 25
    )
  );
  $command$
);

SELECT cron.schedule(
  'nightly-contract-terms-scan',
  '10 3 * * *',
  $command$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_project_url' LIMIT 1) || '/functions/v1/contract-terms-scanner',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-agent-id', 'contract-terms-scanner',
      'x-agent-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'agent_secret_contract_terms_scanner' LIMIT 1)
    ),
    body := jsonb_build_object(
      'mode', 'batch',
      'companyId', '24bc0b21-4e2d-4413-9842-31719a3669f4',
      'maxDocuments', 4,
      'autoApply', false
    ),
    timeout_milliseconds := 120000
  );
  $command$
);

COMMIT;

;
