-- Durable queue and audit trail for filing legal cases in Taqadi through a
-- trusted local Playwright worker.

CREATE TABLE IF NOT EXISTS public.taqadi_filing_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  legal_case_id uuid NOT NULL REFERENCES public.legal_cases(id) ON DELETE CASCADE,
  contract_id uuid NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'queued' CHECK (
    status IN (
      'queued',
      'validating',
      'waiting_login',
      'filling_case',
      'validating_parties',
      'uploading_documents',
      'reviewing',
      'submitting',
      'filed',
      'needs_human',
      'failed',
      'cancelled'
    )
  ),
  current_step text NOT NULL DEFAULT 'queued',
  progress integer NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb,
  error_code text,
  error_message text,
  idempotency_key text NOT NULL,
  automation_version text NOT NULL DEFAULT 'taqadi-v1',
  final_approval boolean NOT NULL DEFAULT true,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  max_attempts integer NOT NULL DEFAULT 3 CHECK (max_attempts BETWEEN 1 AND 10),
  locked_by text,
  locked_at timestamptz,
  heartbeat_at timestamptz,
  requested_by uuid NOT NULL,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, idempotency_key)
);
CREATE TABLE IF NOT EXISTS public.taqadi_filing_job_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  job_id uuid NOT NULL REFERENCES public.taqadi_filing_jobs(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  step text,
  status text,
  message text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.taqadi_filing_artifacts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  job_id uuid NOT NULL REFERENCES public.taqadi_filing_jobs(id) ON DELETE CASCADE,
  artifact_type text NOT NULL CHECK (
    artifact_type IN ('screenshot', 'receipt', 'submission_summary', 'error_snapshot')
  ),
  storage_path text NOT NULL,
  file_name text NOT NULL,
  mime_type text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.taqadi_automation_workers (
  worker_id text PRIMARY KEY,
  status text NOT NULL DEFAULT 'offline' CHECK (
    status IN ('idle', 'busy', 'waiting_login', 'error', 'offline')
  ),
  version text NOT NULL,
  current_job_id uuid REFERENCES public.taqadi_filing_jobs(id) ON DELETE SET NULL,
  hostname text,
  last_error text,
  started_at timestamptz NOT NULL DEFAULT now(),
  heartbeat_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_taqadi_filing_jobs_queue
  ON public.taqadi_filing_jobs(status, created_at)
  WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS idx_taqadi_filing_jobs_case
  ON public.taqadi_filing_jobs(company_id, legal_case_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_taqadi_filing_jobs_contract
  ON public.taqadi_filing_jobs(company_id, contract_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_taqadi_filing_jobs_active_case
  ON public.taqadi_filing_jobs(company_id, legal_case_id)
  WHERE status NOT IN ('filed', 'failed', 'cancelled');
CREATE INDEX IF NOT EXISTS idx_taqadi_filing_events_job
  ON public.taqadi_filing_job_events(job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_taqadi_filing_artifacts_job
  ON public.taqadi_filing_artifacts(job_id, created_at);
ALTER TABLE public.taqadi_filing_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.taqadi_filing_job_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.taqadi_filing_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.taqadi_automation_workers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS taqadi_filing_jobs_company_read ON public.taqadi_filing_jobs;
CREATE POLICY taqadi_filing_jobs_company_read
ON public.taqadi_filing_jobs
FOR SELECT
TO authenticated
USING (company_id = public.get_user_company_id());
DROP POLICY IF EXISTS taqadi_filing_events_company_read ON public.taqadi_filing_job_events;
CREATE POLICY taqadi_filing_events_company_read
ON public.taqadi_filing_job_events
FOR SELECT
TO authenticated
USING (company_id = public.get_user_company_id());
DROP POLICY IF EXISTS taqadi_filing_artifacts_company_read ON public.taqadi_filing_artifacts;
CREATE POLICY taqadi_filing_artifacts_company_read
ON public.taqadi_filing_artifacts
FOR SELECT
TO authenticated
USING (company_id = public.get_user_company_id());
DROP POLICY IF EXISTS taqadi_automation_workers_authenticated_read ON public.taqadi_automation_workers;
CREATE POLICY taqadi_automation_workers_authenticated_read
ON public.taqadi_automation_workers
FOR SELECT
TO authenticated
USING (true);
CREATE OR REPLACE FUNCTION public.validate_taqadi_filing_payload_v1(
  p_company_id uuid,
  p_contract_id uuid,
  p_payload jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_missing text[] := ARRAY[]::text[];
  v_violation_count integer := 0;
  v_document jsonb;
  v_documents jsonb := COALESCE(p_payload -> 'documents', '[]'::jsonb);
  v_required_document_keys text[] := ARRAY[
    'memo',
    'claims',
    'docsList',
    'contract',
    'commercialRegister',
    'ibanCertificate',
    'representativeId'
  ];
  v_key text;
BEGIN
  IF NOT public.can_prepare_contract_for_legal_v1(p_company_id, p_contract_id) THEN
    RAISE EXCEPTION 'You are not authorized to prepare this contract for filing'
      USING ERRCODE = '42501';
  END IF;

  IF jsonb_typeof(v_documents) IS DISTINCT FROM 'array' THEN
    v_missing := array_append(v_missing, 'documents');
    v_documents := '[]'::jsonb;
  END IF;

  IF NULLIF(BTRIM(COALESCE(p_payload #>> '{case,title}', '')), '') IS NULL THEN
    v_missing := array_append(v_missing, 'case.title');
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_payload #>> '{case,facts}', '')), '') IS NULL THEN
    v_missing := array_append(v_missing, 'case.facts');
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_payload #>> '{case,claims}', '')), '') IS NULL THEN
    v_missing := array_append(v_missing, 'case.claims');
  END IF;
  IF COALESCE(NULLIF(p_payload #>> '{case,amount}', '')::numeric, 0) <= 0 THEN
    v_missing := array_append(v_missing, 'case.amount');
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_payload #>> '{defendant,fullName}', '')), '') IS NULL THEN
    v_missing := array_append(v_missing, 'defendant.fullName');
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_payload #>> '{defendant,idNumber}', '')), '') IS NULL THEN
    v_missing := array_append(v_missing, 'defendant.idNumber');
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_payload #>> '{defendant,nationality}', '')), '') IS NULL THEN
    v_missing := array_append(v_missing, 'defendant.nationality');
  END IF;

  FOREACH v_key IN ARRAY v_required_document_keys LOOP
    SELECT document
    INTO v_document
    FROM jsonb_array_elements(v_documents) document
    WHERE document ->> 'key' = v_key
      AND COALESCE((document ->> 'ready')::boolean, false)
      AND (
        NULLIF(document ->> 'url', '') IS NOT NULL
        OR NULLIF(document ->> 'htmlContent', '') IS NOT NULL
      )
    LIMIT 1;

    IF v_document IS NULL THEN
      v_missing := array_append(v_missing, 'documents.' || v_key);
    END IF;
    v_document := NULL;
  END LOOP;

  SELECT COUNT(*)
  INTO v_violation_count
  FROM public.penalties penalty
  WHERE penalty.company_id = p_company_id
    AND penalty.contract_id = p_contract_id
    AND lower(COALESCE(penalty.status, '')) NOT IN ('cancelled', 'canceled', 'deleted')
    AND lower(COALESCE(penalty.payment_status, '')) <> 'paid';

  IF v_violation_count > 0 AND NOT EXISTS (
    SELECT 1
    FROM jsonb_array_elements(v_documents) document
    WHERE document ->> 'key' = 'violations'
      AND COALESCE((document ->> 'ready')::boolean, false)
      AND (
        NULLIF(document ->> 'url', '') IS NOT NULL
        OR NULLIF(document ->> 'htmlContent', '') IS NOT NULL
      )
  ) THEN
    v_missing := array_append(v_missing, 'documents.violations');
  END IF;

  IF v_violation_count > 0 AND NOT EXISTS (
    SELECT 1
    FROM jsonb_array_elements(v_documents) document
    WHERE document ->> 'key' = 'violationsEvidence'
      AND COALESCE((document ->> 'ready')::boolean, false)
      AND NULLIF(document ->> 'url', '') IS NOT NULL
  ) THEN
    v_missing := array_append(v_missing, 'documents.violationsEvidence');
  END IF;

  RETURN jsonb_build_object(
    'ready', cardinality(v_missing) = 0,
    'missing', to_jsonb(v_missing),
    'violation_count', v_violation_count
  );
END;
$$;
CREATE OR REPLACE FUNCTION public.enqueue_taqadi_filing_job_v1(
  p_company_id uuid,
  p_legal_case_id uuid,
  p_payload jsonb,
  p_idempotency_key text,
  p_final_approval boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_case public.legal_cases%ROWTYPE;
  v_job public.taqadi_filing_jobs%ROWTYPE;
  v_validation jsonb;
  v_actor uuid := auth.uid();
BEGIN
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'Authentication is required' USING ERRCODE = '42501';
  END IF;
  IF public.get_user_company_id() IS DISTINCT FROM p_company_id THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE = '42501';
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_idempotency_key, '')), '') IS NULL THEN
    RAISE EXCEPTION 'An idempotency key is required' USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_case
  FROM public.legal_cases legal_case
  WHERE legal_case.id = p_legal_case_id
    AND legal_case.company_id = p_company_id
  FOR UPDATE;

  IF NOT FOUND OR v_case.contract_id IS NULL THEN
    RAISE EXCEPTION 'Legal case or its contract was not found' USING ERRCODE = 'P0001';
  END IF;
  IF v_case.workflow_stage <> 'preparation' THEN
    RAISE EXCEPTION 'Only cases in preparation can be queued for filing'
      USING ERRCODE = 'P0001';
  END IF;
  IF NULLIF(BTRIM(COALESCE(v_case.case_reference, '')), '') IS NOT NULL THEN
    RAISE EXCEPTION 'The case already has a Taqadi reference'
      USING ERRCODE = 'P0001';
  END IF;

  v_validation := public.validate_taqadi_filing_payload_v1(
    p_company_id,
    v_case.contract_id,
    p_payload
  );
  IF COALESCE((v_validation ->> 'ready')::boolean, false) = false THEN
    RAISE EXCEPTION 'Filing package is incomplete: %', v_validation -> 'missing'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_job
  FROM public.taqadi_filing_jobs job
  WHERE job.company_id = p_company_id
    AND job.idempotency_key = BTRIM(p_idempotency_key)
  LIMIT 1;

  IF FOUND THEN
    RETURN to_jsonb(v_job);
  END IF;

  SELECT *
  INTO v_job
  FROM public.taqadi_filing_jobs job
  WHERE job.company_id = p_company_id
    AND job.legal_case_id = p_legal_case_id
    AND job.status NOT IN ('filed', 'failed', 'cancelled')
  ORDER BY job.created_at DESC
  LIMIT 1;

  IF FOUND THEN
    RETURN to_jsonb(v_job);
  END IF;

  INSERT INTO public.taqadi_filing_jobs (
    company_id,
    legal_case_id,
    contract_id,
    payload,
    idempotency_key,
    final_approval,
    requested_by
  )
  VALUES (
    p_company_id,
    p_legal_case_id,
    v_case.contract_id,
    p_payload || jsonb_build_object(
      'validation', v_validation,
      'queuedAt', now(),
      'legalCaseNumber', v_case.case_number
    ),
    BTRIM(p_idempotency_key),
    COALESCE(p_final_approval, true),
    v_actor
  )
  RETURNING * INTO v_job;

  INSERT INTO public.taqadi_filing_job_events (
    company_id, job_id, event_type, step, status, message, details
  )
  VALUES (
    p_company_id,
    v_job.id,
    'queued',
    'queued',
    'queued',
    'تمت إضافة الدعوى إلى طابور الرفع في تقاضي',
    v_validation
  );

  RETURN to_jsonb(v_job);
END;
$$;
CREATE OR REPLACE FUNCTION public.retry_taqadi_filing_job_v1(
  p_company_id uuid,
  p_job_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_job public.taqadi_filing_jobs%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL OR public.get_user_company_id() IS DISTINCT FROM p_company_id THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE = '42501';
  END IF;

  SELECT *
  INTO v_job
  FROM public.taqadi_filing_jobs job
  WHERE job.id = p_job_id
    AND job.company_id = p_company_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Filing job was not found' USING ERRCODE = 'P0001';
  END IF;
  IF v_job.status NOT IN ('failed', 'needs_human', 'waiting_login') THEN
    RAISE EXCEPTION 'Only stopped filing jobs can be retried' USING ERRCODE = 'P0001';
  END IF;
  IF v_job.error_code = 'SUBMISSION_UNCERTAIN' THEN
    RAISE EXCEPTION 'Submission result must be verified in Taqadi before retrying'
      USING ERRCODE = 'P0001';
  END IF;
  IF v_job.attempt_count >= v_job.max_attempts THEN
    RAISE EXCEPTION 'Maximum filing attempts reached' USING ERRCODE = 'P0001';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM public.legal_cases legal_case
    WHERE legal_case.id = v_job.legal_case_id
      AND NULLIF(BTRIM(COALESCE(legal_case.case_reference, '')), '') IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'The case already has a Taqadi reference' USING ERRCODE = 'P0001';
  END IF;

  UPDATE public.taqadi_filing_jobs
  SET
    status = 'queued',
    current_step = 'queued',
    progress = 0,
    error_code = NULL,
    error_message = NULL,
    locked_by = NULL,
    locked_at = NULL,
    heartbeat_at = NULL,
    completed_at = NULL,
    updated_at = now()
  WHERE id = p_job_id
  RETURNING * INTO v_job;

  INSERT INTO public.taqadi_filing_job_events (
    company_id, job_id, event_type, step, status, message
  ) VALUES (
    p_company_id, p_job_id, 'retry_requested', 'queued', 'queued',
    'تمت إعادة الدعوى إلى طابور الرفع'
  );

  RETURN to_jsonb(v_job);
END;
$$;
CREATE OR REPLACE FUNCTION public.cancel_taqadi_filing_job_v1(
  p_company_id uuid,
  p_job_id uuid,
  p_reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_job public.taqadi_filing_jobs%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL OR public.get_user_company_id() IS DISTINCT FROM p_company_id THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE = '42501';
  END IF;

  UPDATE public.taqadi_filing_jobs job
  SET
    status = 'cancelled',
    current_step = 'cancelled',
    error_message = NULLIF(BTRIM(COALESCE(p_reason, '')), ''),
    completed_at = now(),
    updated_at = now()
  WHERE job.id = p_job_id
    AND job.company_id = p_company_id
    AND job.status IN ('queued', 'waiting_login', 'needs_human', 'failed')
  RETURNING * INTO v_job;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'This filing job cannot be cancelled at its current step'
      USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.taqadi_filing_job_events (
    company_id, job_id, event_type, step, status, message
  ) VALUES (
    p_company_id, p_job_id, 'cancelled', 'cancelled', 'cancelled',
    COALESCE(NULLIF(BTRIM(p_reason), ''), 'تم إلغاء عملية الرفع')
  );

  RETURN to_jsonb(v_job);
END;
$$;
CREATE OR REPLACE FUNCTION public.claim_next_taqadi_filing_job_v1(
  p_worker_id text,
  p_worker_version text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_job public.taqadi_filing_jobs%ROWTYPE;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Only a trusted automation worker may claim filing jobs'
      USING ERRCODE = '42501';
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_worker_id, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Worker identifier is required' USING ERRCODE = 'P0001';
  END IF;

  WITH candidate AS (
    SELECT job.id
    FROM public.taqadi_filing_jobs job
    WHERE job.status = 'queued'
      AND job.attempt_count < job.max_attempts
    ORDER BY job.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
  )
  UPDATE public.taqadi_filing_jobs job
  SET
    status = 'validating',
    current_step = 'preflight',
    progress = 2,
    attempt_count = job.attempt_count + 1,
    locked_by = BTRIM(p_worker_id),
    locked_at = now(),
    heartbeat_at = now(),
    started_at = COALESCE(job.started_at, now()),
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
  FROM candidate
  WHERE job.id = candidate.id
  RETURNING job.* INTO v_job;

  INSERT INTO public.taqadi_automation_workers (
    worker_id, status, version, current_job_id, heartbeat_at
  )
  VALUES (
    BTRIM(p_worker_id),
    CASE WHEN v_job.id IS NULL THEN 'idle' ELSE 'busy' END,
    COALESCE(NULLIF(BTRIM(p_worker_version), ''), 'unknown'),
    v_job.id,
    now()
  )
  ON CONFLICT (worker_id) DO UPDATE SET
    status = EXCLUDED.status,
    version = EXCLUDED.version,
    current_job_id = EXCLUDED.current_job_id,
    heartbeat_at = now(),
    last_error = NULL;

  IF v_job.id IS NULL THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.taqadi_filing_job_events (
    company_id, job_id, event_type, step, status, message,
    details
  ) VALUES (
    v_job.company_id, v_job.id, 'claimed', 'preflight', 'validating',
    'بدأ وكيل تقاضي معالجة الدعوى',
    jsonb_build_object('worker_id', p_worker_id, 'worker_version', p_worker_version)
  );

  RETURN to_jsonb(v_job);
END;
$$;
CREATE OR REPLACE FUNCTION public.update_taqadi_filing_job_v1(
  p_job_id uuid,
  p_worker_id text,
  p_status text,
  p_step text,
  p_progress integer,
  p_message text DEFAULT NULL,
  p_details jsonb DEFAULT '{}'::jsonb,
  p_error_code text DEFAULT NULL,
  p_error_message text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_job public.taqadi_filing_jobs%ROWTYPE;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Only a trusted automation worker may update filing jobs'
      USING ERRCODE = '42501';
  END IF;
  IF p_status NOT IN (
    'validating', 'waiting_login', 'filling_case', 'validating_parties',
    'uploading_documents', 'reviewing', 'submitting', 'needs_human',
    'failed'
  ) THEN
    RAISE EXCEPTION 'Invalid filing job status' USING ERRCODE = 'P0001';
  END IF;

  UPDATE public.taqadi_filing_jobs job
  SET
    status = p_status,
    current_step = COALESCE(NULLIF(BTRIM(p_step), ''), job.current_step),
    progress = LEAST(99, GREATEST(0, COALESCE(p_progress, job.progress))),
    heartbeat_at = now(),
    error_code = NULLIF(BTRIM(COALESCE(p_error_code, '')), ''),
    error_message = NULLIF(BTRIM(COALESCE(p_error_message, '')), ''),
    completed_at = CASE WHEN p_status IN ('failed', 'needs_human') THEN now() ELSE NULL END,
    updated_at = now()
  WHERE job.id = p_job_id
    AND job.locked_by = BTRIM(p_worker_id)
    AND job.status NOT IN ('filed', 'cancelled')
  RETURNING * INTO v_job;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Filing job lock was lost' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.taqadi_filing_job_events (
    company_id, job_id, event_type, step, status, message, details
  ) VALUES (
    v_job.company_id,
    v_job.id,
    CASE WHEN p_status IN ('failed', 'needs_human') THEN p_status ELSE 'progress' END,
    v_job.current_step,
    v_job.status,
    p_message,
    COALESCE(p_details, '{}'::jsonb)
  );

  UPDATE public.taqadi_automation_workers
  SET
    status = CASE
      WHEN p_status = 'waiting_login' THEN 'waiting_login'
      WHEN p_status IN ('failed', 'needs_human') THEN 'error'
      ELSE 'busy'
    END,
    current_job_id = CASE WHEN p_status IN ('failed', 'needs_human') THEN NULL ELSE p_job_id END,
    heartbeat_at = now(),
    last_error = CASE
      WHEN p_status IN ('failed', 'needs_human') THEN COALESCE(p_error_message, p_message)
      ELSE NULL
    END
  WHERE worker_id = BTRIM(p_worker_id);

  RETURN to_jsonb(v_job);
END;
$$;
CREATE OR REPLACE FUNCTION public.complete_taqadi_filing_job_v1(
  p_job_id uuid,
  p_worker_id text,
  p_case_number text,
  p_reference_number text,
  p_court_fees numeric DEFAULT NULL,
  p_result jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_job public.taqadi_filing_jobs%ROWTYPE;
  v_case public.legal_cases%ROWTYPE;
  v_reference text := COALESCE(
    NULLIF(BTRIM(COALESCE(p_reference_number, '')), ''),
    NULLIF(BTRIM(COALESCE(p_case_number, '')), '')
  );
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Only a trusted automation worker may complete filing jobs'
      USING ERRCODE = '42501';
  END IF;
  IF v_reference IS NULL THEN
    RAISE EXCEPTION 'A Taqadi case or reference number is required'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_job
  FROM public.taqadi_filing_jobs job
  WHERE job.id = p_job_id
    AND job.locked_by = BTRIM(p_worker_id)
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Filing job lock was lost' USING ERRCODE = 'P0001';
  END IF;
  IF v_job.status = 'filed' THEN
    RETURN to_jsonb(v_job);
  END IF;
  IF v_job.status <> 'submitting' THEN
    RAISE EXCEPTION 'The filing job is not at the submission step'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_case
  FROM public.legal_cases legal_case
  WHERE legal_case.id = v_job.legal_case_id
    AND legal_case.company_id = v_job.company_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Legal case was not found' USING ERRCODE = 'P0001';
  END IF;

  IF v_case.workflow_stage = 'preparation' THEN
    PERFORM public.transition_legal_case_workflow_v1(
      v_job.company_id,
      v_job.legal_case_id,
      'filed',
      'تم رفع الدعوى واعتمادها آليًا عبر نظام تقاضي',
      v_job.requested_by
    );
  ELSIF v_case.workflow_stage <> 'filed' THEN
    RAISE EXCEPTION 'Legal case is no longer at a filing stage'
      USING ERRCODE = 'P0001';
  END IF;

  UPDATE public.legal_cases
  SET
    case_reference = v_reference,
    court_fees = COALESCE(p_court_fees, court_fees),
    filing_date = COALESCE(filing_date, CURRENT_DATE),
    updated_at = now()
  WHERE id = v_job.legal_case_id
    AND company_id = v_job.company_id;

  UPDATE public.lawsuit_preparations
  SET
    status = 'registered',
    taqadi_case_number = COALESCE(
      NULLIF(BTRIM(COALESCE(p_case_number, '')), ''),
      taqadi_case_number
    ),
    taqadi_reference_number = v_reference,
    submitted_at = COALESCE(submitted_at, now()),
    registered_at = COALESCE(registered_at, now()),
    updated_at = now()
  WHERE company_id = v_job.company_id
    AND (
      legal_case_id = v_job.legal_case_id
      OR contract_id = v_job.contract_id
    );

  UPDATE public.taqadi_filing_jobs
  SET
    status = 'filed',
    current_step = 'completed',
    progress = 100,
    result = COALESCE(p_result, '{}'::jsonb) || jsonb_build_object(
      'caseNumber', NULLIF(BTRIM(COALESCE(p_case_number, '')), ''),
      'referenceNumber', v_reference,
      'courtFees', p_court_fees,
      'filedAt', now()
    ),
    error_code = NULL,
    error_message = NULL,
    heartbeat_at = now(),
    completed_at = now(),
    updated_at = now()
  WHERE id = v_job.id
  RETURNING * INTO v_job;

  INSERT INTO public.taqadi_filing_job_events (
    company_id, job_id, event_type, step, status, message, details
  ) VALUES (
    v_job.company_id, v_job.id, 'filed', 'completed', 'filed',
    'تم رفع الدعوى واعتمادها وتحديث حالتها تلقائيًا',
    v_job.result
  );

  UPDATE public.taqadi_automation_workers
  SET
    status = 'idle',
    current_job_id = NULL,
    heartbeat_at = now(),
    last_error = NULL
  WHERE worker_id = BTRIM(p_worker_id);

  RETURN to_jsonb(v_job);
END;
$$;
CREATE OR REPLACE FUNCTION public.heartbeat_taqadi_worker_v1(
  p_worker_id text,
  p_version text,
  p_status text DEFAULT 'idle',
  p_current_job_id uuid DEFAULT NULL,
  p_hostname text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Only a trusted automation worker may send heartbeats'
      USING ERRCODE = '42501';
  END IF;
  IF p_status NOT IN ('idle', 'busy', 'waiting_login', 'error', 'offline') THEN
    RAISE EXCEPTION 'Invalid worker status' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.taqadi_automation_workers (
    worker_id, status, version, current_job_id, hostname, heartbeat_at, metadata
  ) VALUES (
    BTRIM(p_worker_id), p_status, p_version, p_current_job_id,
    p_hostname, now(), COALESCE(p_metadata, '{}'::jsonb)
  )
  ON CONFLICT (worker_id) DO UPDATE SET
    status = EXCLUDED.status,
    version = EXCLUDED.version,
    current_job_id = EXCLUDED.current_job_id,
    hostname = EXCLUDED.hostname,
    heartbeat_at = now(),
    metadata = EXCLUDED.metadata,
    last_error = CASE WHEN EXCLUDED.status = 'error'
      THEN public.taqadi_automation_workers.last_error ELSE NULL END;
END;
$$;
REVOKE ALL ON FUNCTION public.validate_taqadi_filing_payload_v1(uuid, uuid, jsonb)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.enqueue_taqadi_filing_job_v1(uuid, uuid, jsonb, text, boolean)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.retry_taqadi_filing_job_v1(uuid, uuid)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.cancel_taqadi_filing_job_v1(uuid, uuid, text)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.claim_next_taqadi_filing_job_v1(text, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_taqadi_filing_job_v1(uuid, text, text, text, integer, text, jsonb, text, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_taqadi_filing_job_v1(uuid, text, text, text, numeric, jsonb)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.heartbeat_taqadi_worker_v1(text, text, text, uuid, text, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_taqadi_filing_payload_v1(uuid, uuid, jsonb)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_taqadi_filing_job_v1(uuid, uuid, jsonb, text, boolean)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.retry_taqadi_filing_job_v1(uuid, uuid)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.cancel_taqadi_filing_job_v1(uuid, uuid, text)
  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.claim_next_taqadi_filing_job_v1(text, text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.update_taqadi_filing_job_v1(uuid, text, text, text, integer, text, jsonb, text, text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_taqadi_filing_job_v1(uuid, text, text, text, numeric, jsonb)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.heartbeat_taqadi_worker_v1(text, text, text, uuid, text, jsonb)
  TO service_role;
INSERT INTO storage.buckets (id, name, public)
VALUES ('taqadi-automation-artifacts', 'taqadi-automation-artifacts', false)
ON CONFLICT (id) DO UPDATE SET public = false;
COMMENT ON TABLE public.taqadi_filing_jobs IS
  'Durable queue for filing prepared legal cases in Taqadi through a trusted local browser worker.';
COMMENT ON COLUMN public.taqadi_filing_jobs.payload IS
  'Immutable filing snapshot containing case data, parties, classification, and document sources.';
COMMENT ON COLUMN public.taqadi_filing_jobs.idempotency_key IS
  'Prevents duplicate external filing when a request or worker is retried.';
