export { default as MissingDataWarnings } from './MissingDataWarnings';
export { default as PersonalInfoTab } from './PersonalInfoTab';
export { default as PhoneNumbersTab } from './PhoneNumbersTab';
export { default as ContractsTab } from './ContractsTab';
export { default as VehiclesTab } from './VehiclesTab';
export { default as InvoicesTab } from './InvoicesTab';
export { default as PaymentsTab } from './PaymentsTab';
export { default as NotesTab } from './NotesTab';
export { default as ViolationsTab } from './ViolationsTab';
export { default as ActivityTab } from './ActivityTab';
export { default as DocumentCard } from './DocumentCard';
export type { CustomerDocument } from './types';
