#!/usr/bin/env node

/**
 * Vercel Build Script
 * Ensures environment variables are properly set for Vercel builds
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

console.log('🚀 Starting Vercel build process...');

// Validate required environment variables
const requiredEnvVars = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY',
  'VITE_ENCRYPTION_SECRET'
];

const missingVars = requiredEnvVars.filter(varName => !process.env[varName]);

if (missingVars.length > 0) {
  console.error('❌ Missing required environment variables:');
  missingVars.forEach(varName => {
    console.error(`   - ${varName}`);
  });
  console.error('\nPlease set these environment variables in your Vercel dashboard:');
  console.error('1. Go to Project Settings > Environment Variables');
  console.error('2. Add the missing variables with their appropriate values');
  process.exit(1);
}

console.log('✅ All required environment variables are present');

// Set additional environment variables for build
process.env.NODE_ENV = 'production';
process.env.BUILD_TIME = new Date().toISOString();
process.env.BUILD_ID = `vercel_${Date.now()}`;

// Create a temporary .env file for the build process
const envContent = `
# Generated by Vercel build script
NODE_ENV=${process.env.NODE_ENV}
VITE_SUPABASE_URL=${process.env.VITE_SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${process.env.VITE_SUPABASE_ANON_KEY}
VITE_ENCRYPTION_SECRET=${process.env.VITE_ENCRYPTION_SECRET}
VITE_APP_VERSION=${process.env.VITE_APP_VERSION || '1.0.0'}
VITE_API_TIMEOUT=${process.env.VITE_API_TIMEOUT || '30000'}
VITE_ENABLE_ANALYTICS=${process.env.VITE_ENABLE_ANALYTICS || 'true'}
VITE_API_PERFORMANCE_OPTIMIZATIONS=${process.env.VITE_API_PERFORMANCE_OPTIMIZATIONS || 'true'}
VITE_PERFORMANCE_MONITORING_ENABLED=${process.env.VITE_PERFORMANCE_MONITORING_ENABLED || 'true'}
VITE_MONITORING_ENABLED=${process.env.VITE_MONITORING_ENABLED || 'true'}
BUILD_TIME=${process.env.BUILD_TIME}
BUILD_ID=${process.env.BUILD_ID}
BUILD_VERSION=${process.env.BUILD_VERSION || '1.0.0'}
`;

const envPath = path.join(process.cwd(), '.env.build');
fs.writeFileSync(envPath, envContent);

try {
  console.log('📦 Running TypeScript compilation...');
  execSync('tsc', { stdio: 'inherit' });

  console.log('🏗️ Running Vite build...');
  execSync('vite build --mode production', { stdio: 'inherit' });

  console.log('✅ Build completed successfully!');
} catch (error) {
  console.error('❌ Build failed:', error.message);
  process.exit(1);
} finally {
  // Clean up temporary environment file
  if (fs.existsSync(envPath)) {
    fs.unlinkSync(envPath);
  }
}