BEGIN;
DROP FUNCTION IF EXISTS public.save_vehicle_reservation_v2(uuid, uuid, uuid, uuid, text, date, date, text, text, uuid);
DROP TRIGGER IF EXISTS trg_enforce_reservation_rental_eligibility ON public.vehicle_reservations;
DROP TRIGGER IF EXISTS trg_enforce_contract_rental_eligibility ON public.contracts;
DROP FUNCTION IF EXISTS public.trg_enforce_rental_eligibility();
DROP TRIGGER IF EXISTS trg_block_contract_close_with_unpaid_penalties ON public.contracts;
DROP FUNCTION IF EXISTS public.trg_block_contract_close_with_unpaid_penalties();
DROP TRIGGER IF EXISTS trg_penalty_contract_invoice_after_write ON public.penalties;
DROP TRIGGER IF EXISTS trg_propagate_penalty_case_follow_up ON public.penalties;
DROP FUNCTION IF EXISTS public.trg_propagate_penalty_case_follow_up();
DROP FUNCTION IF EXISTS public.trg_penalty_contract_invoice_after_write();
DROP TRIGGER IF EXISTS trg_penalty_case_follow_up_before_write ON public.penalties;
DROP FUNCTION IF EXISTS public.trg_penalty_invoice_and_case_follow_up();
DROP FUNCTION IF EXISTS public.ensure_penalty_contract_invoice(uuid);
DROP INDEX IF EXISTS public.uq_invoices_penalty_id;
ALTER TABLE public.invoices DROP COLUMN IF EXISTS penalty_id;
ALTER TABLE public.penalties DROP COLUMN IF EXISTS case_follow_up_source;
ALTER TABLE public.penalties DROP COLUMN IF EXISTS case_follow_up_at;
ALTER TABLE public.penalties DROP COLUMN IF EXISTS case_follow_up;
COMMIT;
