SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname='daily-legal-workflow-guard-v1';
DROP FUNCTION IF EXISTS public.run_legal_workflow_daily_guard_v1();
DROP FUNCTION IF EXISTS public.reopen_legal_case_v1(uuid,uuid,text,text,uuid);
DROP FUNCTION IF EXISTS public.close_legal_case_final_v1(uuid,uuid,text,boolean,uuid);
DROP FUNCTION IF EXISTS public.record_legal_case_payment_v1(uuid,uuid,numeric,date,text,text,uuid,uuid,text,uuid);
DROP FUNCTION IF EXISTS public.start_legal_case_enforcement_v1(uuid,uuid,text,text,numeric,date,text,uuid);
DROP FUNCTION IF EXISTS public.record_legal_case_judgment_v1(uuid,uuid,text,text,numeric,text,text,date,date,text,uuid);
DROP FUNCTION IF EXISTS public.record_legal_case_hearing_v1(uuid,uuid,timestamptz,text,text,timestamptz,text,uuid);
DROP FUNCTION IF EXISTS public.transition_legal_case_workflow_v1(uuid,uuid,text,text,uuid);
DROP FUNCTION IF EXISTS public.legal_workflow_create_task_v1(uuid,uuid,text,text,text,timestamptz,text,uuid);
DROP FUNCTION IF EXISTS public.legal_workflow_sync_contract_v1(uuid,uuid,text);
DROP FUNCTION IF EXISTS public.legal_workflow_actor_profile_v1(uuid,uuid);
DROP TRIGGER IF EXISTS guard_legal_case_reopen ON public.legal_cases;
DROP FUNCTION IF EXISTS public.prevent_illegal_case_reopen_v1();
DROP TABLE IF EXISTS public.legal_case_enforcements;
DROP TABLE IF EXISTS public.legal_case_appeals;
DROP TABLE IF EXISTS public.legal_case_hearings;
ALTER TABLE public.legal_case_payments DROP COLUMN IF EXISTS reference_number;
ALTER TABLE public.legal_cases DROP CONSTRAINT IF EXISTS legal_cases_workflow_stage_check;
ALTER TABLE public.legal_cases DROP COLUMN IF EXISTS workflow_stage,DROP COLUMN IF EXISTS stage_updated_at,DROP COLUMN IF EXISTS appeal_deadline,DROP COLUMN IF EXISTS judgment_final_at,DROP COLUMN IF EXISTS closed_at,DROP COLUMN IF EXISTS closure_reason,DROP COLUMN IF EXISTS reopened_at,DROP COLUMN IF EXISTS reopened_by,DROP COLUMN IF EXISTS reopen_reason;
