-- Insert basic learning patterns for common queries to prevent empty database issues

-- First, create some sample embeddings (these would normally be generated by OpenAI)
-- Using placeholder embeddings for the basic patterns
INSERT INTO ai_learning_patterns (
  company_id,
  pattern_type,
  pattern_data,
  success_rate,
  usage_count,
  is_active
) VALUES 
-- Contract count queries
(
  '44f2cd3a-5bf6-4b43-a7e5-aa3ff6422f1c',  -- Sample company ID from logs
  'contract_count_query',
  '{
    "query_embedding": [0.1, 0.2, 0.3, 0.4, 0.5],
    "response_quality": 0.9,
    "processing_type": "keyword_match",
    "intent_detected": "contract_count_query",
    "confidence_level": 0.9,
    "context_features": {
      "language": "arabic",
      "hasQuestion": true,
      "keywords": ["كم", "عقد", "اتفاقية", "عدد"],
      "hasNumbers": false
    },
    "original_query": "كم عقد في النظام",
    "sample_response": "لمساعدتك في معرفة عدد العقود، أحتاج للوصول إلى قاعدة البيانات. هل تقصد العقود النشطة فقط أم جميع العقود؟",
    "timestamp": "2025-08-04T19:00:00.000Z"
  }'::jsonb,
  0.85,
  1,
  true
),
-- Customer count queries  
(
  '44f2cd3a-5bf6-4b43-a7e5-aa3ff6422f1c',
  'customer_count_query',
  '{
    "query_embedding": [0.15, 0.25, 0.35, 0.45, 0.55],
    "response_quality": 0.9,
    "processing_type": "keyword_match",
    "intent_detected": "customer_count_query", 
    "confidence_level": 0.9,
    "context_features": {
      "language": "arabic",
      "hasQuestion": true,
      "keywords": ["كم", "عميل", "زبون", "عدد"],
      "hasNumbers": false
    },
    "original_query": "كم عميل في النظام",
    "sample_response": "لعرض إحصائيات العملاء، هل تريد معرفة العملاء النشطين أم جميع العملاء المسجلين في النظام؟",
    "timestamp": "2025-08-04T19:00:00.000Z"
  }'::jsonb,
  0.85,
  1,
  true
),
-- Statistics queries
(
  '44f2cd3a-5bf6-4b43-a7e5-aa3ff6422f1c',
  'statistics_query',
  '{
    "query_embedding": [0.2, 0.3, 0.4, 0.5, 0.6],
    "response_quality": 0.8,
    "processing_type": "intent_classification",
    "intent_detected": "statistics_query",
    "confidence_level": 0.8,
    "context_features": {
      "language": "arabic",
      "hasQuestion": true,
      "keywords": ["إحصائيات", "تقرير", "بيانات"],
      "hasNumbers": true
    },
    "original_query": "أريد إحصائيات النظام",
    "sample_response": "يمكنني مساعدتك في الحصول على الإحصائيات. ما نوع الإحصائيات التي تحتاجها؟",
    "timestamp": "2025-08-04T19:00:00.000Z"
  }'::jsonb,
  0.75,
  1,
  true
),
-- General contract queries
(
  '44f2cd3a-5bf6-4b43-a7e5-aa3ff6422f1c',
  'contract_query',
  '{
    "query_embedding": [0.25, 0.35, 0.45, 0.55, 0.65],
    "response_quality": 0.8,
    "processing_type": "intent_classification",
    "intent_detected": "contract_query",
    "confidence_level": 0.8,
    "context_features": {
      "language": "arabic",
      "hasQuestion": false,
      "keywords": ["عقد", "اتفاقية", "تعديل", "إنشاء"],
      "hasNumbers": false
    },
    "original_query": "أريد إنشاء عقد جديد",
    "sample_response": "يمكنني مساعدتك في إنشاء عقد جديد. ما نوع العقد الذي تريد إنشاؤه؟",
    "timestamp": "2025-08-04T19:00:00.000Z"
  }'::jsonb,
  0.75,
  1,
  true
),
-- Search queries
(
  '44f2cd3a-5bf6-4b43-a7e5-aa3ff6422f1c',
  'search_query',
  '{
    "query_embedding": [0.3, 0.4, 0.5, 0.6, 0.7],
    "response_quality": 0.8,
    "processing_type": "intent_classification", 
    "intent_detected": "search_query",
    "confidence_level": 0.8,
    "context_features": {
      "language": "arabic",
      "hasQuestion": false,
      "keywords": ["بحث", "ابحث", "أجد", "العثور"],
      "hasNumbers": false
    },
    "original_query": "ابحث عن عقد شركة X",
    "sample_response": "يمكنني مساعدتك في البحث. ما هي تفاصيل البحث التي تحتاجها؟",
    "timestamp": "2025-08-04T19:00:00.000Z"
  }'::jsonb,
  0.75,
  1,
  true
);