-- Fix: Ensure process_overdue_invoices() function exists
-- ================================================================
-- Purpose: Create the process_overdue_invoices() function if it doesn't exist
-- This is a safety fix in case the migration 20250126120000 was not fully applied
-- Date: 2025-01-27
-- ================================================================

-- First, ensure calculate_late_fee function exists (dependency)
CREATE OR REPLACE FUNCTION calculate_late_fee(
    p_invoice_id UUID,
    p_days_overdue INTEGER,
    p_late_fee_rule_id UUID DEFAULT NULL
)
RETURNS NUMERIC
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_invoice RECORD;
    v_rule RECORD;
    v_fee_amount NUMERIC := 0;
BEGIN
    -- Get invoice details
    SELECT * INTO v_invoice
    FROM invoices
    WHERE id = p_invoice_id;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invoice not found';
    END IF;
    
    -- Get late fee rule (either provided or company default)
    IF p_late_fee_rule_id IS NOT NULL THEN
        SELECT * INTO v_rule
        FROM late_fee_rules
        WHERE id = p_late_fee_rule_id;
    ELSE
        -- Get active rule for this company and invoice type
        SELECT * INTO v_rule
        FROM late_fee_rules
        WHERE company_id = v_invoice.company_id
        AND is_active = true
        AND (apply_to_invoice_types IS NULL OR v_invoice.invoice_type = ANY(apply_to_invoice_types))
        ORDER BY created_at DESC
        LIMIT 1;
    END IF;
    
    IF NOT FOUND THEN
        RETURN 0; -- No rule found, no fee
    END IF;
    
    -- Apply grace period
    IF p_days_overdue <= v_rule.grace_period_days THEN
        RETURN 0;
    END IF;
    
    -- Calculate fee based on type
    CASE v_rule.fee_type
        WHEN 'fixed' THEN
            v_fee_amount := v_rule.fee_amount;
        WHEN 'percentage' THEN
            v_fee_amount := (v_invoice.total_amount * v_rule.fee_amount) / 100;
        WHEN 'daily' THEN
            v_fee_amount := v_rule.fee_amount * (p_days_overdue - v_rule.grace_period_days);
    END CASE;
    
    -- Apply max fee cap if set
    IF v_rule.max_fee_amount IS NOT NULL AND v_fee_amount > v_rule.max_fee_amount THEN
        v_fee_amount := v_rule.max_fee_amount;
    END IF;
    
    RETURN v_fee_amount;
END;
$$;

-- Now create the process_overdue_invoices function
CREATE OR REPLACE FUNCTION process_overdue_invoices()
RETURNS TABLE (
    invoice_id UUID,
    invoice_number TEXT,
    days_overdue INTEGER,
    fee_amount NUMERIC,
    status TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_invoice RECORD;
    v_days_overdue INTEGER;
    v_fee_amount NUMERIC;
    v_late_fee_id UUID;
    v_existing_fee UUID;
BEGIN
    -- Process all overdue invoices
    FOR v_invoice IN
        SELECT i.*
        FROM invoices i
        WHERE i.status IN ('sent', 'overdue')
        AND i.due_date < CURRENT_DATE
        AND i.payment_status != 'paid'
    LOOP
        -- Calculate days overdue
        v_days_overdue := CURRENT_DATE - v_invoice.due_date;
        
        -- Check if late fee already exists for today
        SELECT id INTO v_existing_fee
        FROM late_fees
        WHERE invoice_id = v_invoice.id
        AND DATE(created_at) = CURRENT_DATE;
        
        IF v_existing_fee IS NOT NULL THEN
            CONTINUE; -- Already processed today
        END IF;
        
        -- Calculate fee amount
        v_fee_amount := calculate_late_fee(v_invoice.id, v_days_overdue);
        
        IF v_fee_amount > 0 THEN
            -- Create late fee record
            INSERT INTO late_fees (
                company_id,
                invoice_id,
                contract_id,
                original_amount,
                days_overdue,
                fee_amount,
                fee_type,
                status
            )
            VALUES (
                v_invoice.company_id,
                v_invoice.id,
                v_invoice.contract_id,
                v_invoice.total_amount,
                v_days_overdue,
                v_fee_amount,
                (SELECT fee_type FROM late_fee_rules WHERE company_id = v_invoice.company_id AND is_active = true LIMIT 1),
                'pending'
            )
            RETURNING id INTO v_late_fee_id;
            
            -- Log history
            INSERT INTO late_fee_history (late_fee_id, action, notes)
            VALUES (v_late_fee_id, 'created', 'Auto-generated by daily cron job');
            
            -- Update invoice status to overdue
            UPDATE invoices
            SET status = 'overdue'
            WHERE id = v_invoice.id;
            
            -- Return result
            invoice_id := v_invoice.id;
            invoice_number := v_invoice.invoice_number;
            days_overdue := v_days_overdue;
            fee_amount := v_fee_amount;
            status := 'created';
            RETURN NEXT;
        END IF;
    END LOOP;
END;
$$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION process_overdue_invoices TO authenticated;
GRANT EXECUTE ON FUNCTION process_overdue_invoices TO service_role;
GRANT EXECUTE ON FUNCTION calculate_late_fee TO authenticated;

-- Add comment
COMMENT ON FUNCTION process_overdue_invoices IS 'Daily cron job to process all overdue invoices and generate late fees';

-- Success message
DO $$
BEGIN
    RAISE NOTICE '✅ process_overdue_invoices() function created successfully';
END $$;

