-- Company-scoped control plane for the system audit agent.
-- Adds ownership, pause/kill switches, and cooperative job cancellation.

BEGIN;

CREATE TABLE IF NOT EXISTS public.system_agent_controls (
  company_id uuid PRIMARY KEY REFERENCES public.companies(id) ON DELETE CASCADE,
  owner_profile_id uuid NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  enabled boolean NOT NULL DEFAULT true,
  paused boolean NOT NULL DEFAULT false,
  kill_switch boolean NOT NULL DEFAULT false,
  pause_reason text NULL,
  paused_at timestamptz NULL,
  paused_by_user_id uuid NULL,
  updated_by_user_id uuid NULL,
  version bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.system_agent_control_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  actor_user_id uuid NOT NULL,
  owner_profile_id uuid NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  enabled boolean NOT NULL,
  paused boolean NOT NULL,
  kill_switch boolean NOT NULL,
  reason text NULL,
  control_version bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.system_agent_controls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_agent_control_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.system_agent_controls FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.system_agent_control_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.system_agent_controls TO service_role;
GRANT ALL ON TABLE public.system_agent_control_events TO service_role;

ALTER TABLE public.system_agent_jobs
  ADD COLUMN IF NOT EXISTS owner_profile_id uuid NULL,
  ADD COLUMN IF NOT EXISTS cancel_requested_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS cancel_requested_by_user_id uuid NULL,
  ADD COLUMN IF NOT EXISTS cancel_reason text NULL,
  ADD COLUMN IF NOT EXISTS cancelled_at timestamptz NULL;

DO $constraints$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'system_agent_jobs_owner_profile_id_fkey'
      AND conrelid = 'public.system_agent_jobs'::regclass
  ) THEN
    ALTER TABLE public.system_agent_jobs
      ADD CONSTRAINT system_agent_jobs_owner_profile_id_fkey
      FOREIGN KEY (owner_profile_id) REFERENCES public.profiles(id) ON DELETE SET NULL;
  END IF;
END;
$constraints$;

CREATE INDEX IF NOT EXISTS idx_system_agent_jobs_cancellation
  ON public.system_agent_jobs(company_id, status, cancel_requested_at)
  WHERE status IN ('queued', 'running', 'retry');

CREATE OR REPLACE FUNCTION public.system_agent_prepare_job_v1()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_control public.system_agent_controls%ROWTYPE;
BEGIN
  SELECT control.*
  INTO v_control
  FROM public.system_agent_controls control
  WHERE control.company_id = NEW.company_id;

  IF v_control.company_id IS NOT NULL
     AND (NOT v_control.enabled OR v_control.paused OR v_control.kill_switch) THEN
    RETURN NULL;
  END IF;

  NEW.owner_profile_id := COALESCE(NEW.owner_profile_id, v_control.owner_profile_id);
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_system_agent_prepare_job_v1 ON public.system_agent_jobs;
CREATE TRIGGER trg_system_agent_prepare_job_v1
BEFORE INSERT ON public.system_agent_jobs
FOR EACH ROW
EXECUTE FUNCTION public.system_agent_prepare_job_v1();

CREATE OR REPLACE FUNCTION public.system_agent_get_company_control_v1(
  p_company_id uuid
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT jsonb_build_object(
    'companyId', p_company_id,
    'ownerProfileId', control.owner_profile_id,
    'enabled', COALESCE(control.enabled, true),
    'paused', COALESCE(control.paused, false),
    'killSwitch', COALESCE(control.kill_switch, false),
    'pauseReason', control.pause_reason,
    'pausedAt', control.paused_at,
    'version', COALESCE(control.version, 0),
    'updatedAt', control.updated_at
  )
  FROM (SELECT 1) seed
  LEFT JOIN public.system_agent_controls control
    ON control.company_id = p_company_id;
$function$;

CREATE OR REPLACE FUNCTION public.system_agent_set_company_control_v1(
  p_company_id uuid,
  p_enabled boolean,
  p_paused boolean,
  p_kill_switch boolean,
  p_reason text,
  p_owner_profile_id uuid,
  p_actor_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_control public.system_agent_controls%ROWTYPE;
  v_run_id uuid;
  v_run_ids uuid[] := ARRAY[]::uuid[];
BEGIN
  IF p_company_id IS NULL OR p_actor_user_id IS NULL THEN
    RAISE EXCEPTION 'company_id and actor_user_id are required';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.companies WHERE id = p_company_id) THEN
    RAISE EXCEPTION 'Company not found';
  END IF;

  IF p_owner_profile_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.profiles profile
    WHERE profile.id = p_owner_profile_id
      AND profile.company_id = p_company_id
      AND profile.is_active = true
  ) THEN
    RAISE EXCEPTION 'Owner profile is not active in the requested company';
  END IF;

  INSERT INTO public.system_agent_controls (
    company_id,
    owner_profile_id,
    enabled,
    paused,
    kill_switch,
    pause_reason,
    paused_at,
    paused_by_user_id,
    updated_by_user_id,
    version,
    updated_at
  ) VALUES (
    p_company_id,
    p_owner_profile_id,
    COALESCE(p_enabled, true),
    COALESCE(p_paused, false),
    COALESCE(p_kill_switch, false),
    NULLIF(left(COALESCE(p_reason, ''), 1000), ''),
    CASE WHEN COALESCE(p_paused, false) OR COALESCE(p_kill_switch, false) THEN now() ELSE NULL END,
    CASE WHEN COALESCE(p_paused, false) OR COALESCE(p_kill_switch, false) THEN p_actor_user_id ELSE NULL END,
    p_actor_user_id,
    1,
    now()
  )
  ON CONFLICT (company_id) DO UPDATE
  SET owner_profile_id = EXCLUDED.owner_profile_id,
      enabled = EXCLUDED.enabled,
      paused = EXCLUDED.paused,
      kill_switch = EXCLUDED.kill_switch,
      pause_reason = EXCLUDED.pause_reason,
      paused_at = EXCLUDED.paused_at,
      paused_by_user_id = EXCLUDED.paused_by_user_id,
      updated_by_user_id = EXCLUDED.updated_by_user_id,
      version = public.system_agent_controls.version + 1,
      updated_at = now()
  RETURNING * INTO v_control;

  INSERT INTO public.system_agent_control_events (
    company_id,
    actor_user_id,
    owner_profile_id,
    enabled,
    paused,
    kill_switch,
    reason,
    control_version
  ) VALUES (
    p_company_id,
    p_actor_user_id,
    v_control.owner_profile_id,
    v_control.enabled,
    v_control.paused,
    v_control.kill_switch,
    v_control.pause_reason,
    v_control.version
  );

  IF v_control.kill_switch THEN
    SELECT COALESCE(array_agg(DISTINCT job.run_id), ARRAY[]::uuid[])
    INTO v_run_ids
    FROM public.system_agent_jobs job
    WHERE job.company_id = p_company_id
      AND job.status IN ('queued', 'running', 'retry');

    UPDATE public.system_agent_jobs job
    SET cancel_requested_at = COALESCE(job.cancel_requested_at, now()),
        cancel_requested_by_user_id = COALESCE(job.cancel_requested_by_user_id, p_actor_user_id),
        cancel_reason = COALESCE(NULLIF(left(COALESCE(p_reason, ''), 1000), ''), 'company_kill_switch'),
        status = CASE WHEN job.status IN ('queued', 'retry') THEN 'cancelled' ELSE job.status END,
        cancelled_at = CASE WHEN job.status IN ('queued', 'retry') THEN now() ELSE job.cancelled_at END,
        finished_at = CASE WHEN job.status IN ('queued', 'retry') THEN now() ELSE job.finished_at END,
        lease_token = CASE WHEN job.status IN ('queued', 'retry') THEN NULL ELSE job.lease_token END,
        lease_expires_at = CASE WHEN job.status IN ('queued', 'retry') THEN NULL ELSE job.lease_expires_at END,
        updated_at = now()
    WHERE job.company_id = p_company_id
      AND job.status IN ('queued', 'running', 'retry');

    FOREACH v_run_id IN ARRAY v_run_ids LOOP
      PERFORM public.system_agent_refresh_run(v_run_id);
    END LOOP;
  END IF;

  RETURN public.system_agent_get_company_control_v1(p_company_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.system_agent_request_cancel_v1(
  p_run_id uuid,
  p_company_id uuid,
  p_actor_user_id uuid,
  p_reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_affected integer := 0;
BEGIN
  IF p_run_id IS NULL OR p_company_id IS NULL OR p_actor_user_id IS NULL THEN
    RAISE EXCEPTION 'run_id, company_id and actor_user_id are required';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.system_agent_jobs
    WHERE run_id = p_run_id AND company_id = p_company_id
  ) THEN
    RAISE EXCEPTION 'Run is not associated with the requested company';
  END IF;

  UPDATE public.system_agent_jobs job
  SET cancel_requested_at = COALESCE(job.cancel_requested_at, now()),
      cancel_requested_by_user_id = COALESCE(job.cancel_requested_by_user_id, p_actor_user_id),
      cancel_reason = COALESCE(NULLIF(left(COALESCE(p_reason, ''), 1000), ''), 'manual_cancel'),
      status = CASE WHEN job.status IN ('queued', 'retry') THEN 'cancelled' ELSE job.status END,
      cancelled_at = CASE WHEN job.status IN ('queued', 'retry') THEN now() ELSE job.cancelled_at END,
      finished_at = CASE WHEN job.status IN ('queued', 'retry') THEN now() ELSE job.finished_at END,
      lease_token = CASE WHEN job.status IN ('queued', 'retry') THEN NULL ELSE job.lease_token END,
      lease_expires_at = CASE WHEN job.status IN ('queued', 'retry') THEN NULL ELSE job.lease_expires_at END,
      updated_at = now()
  WHERE job.run_id = p_run_id
    AND job.company_id = p_company_id
    AND job.status IN ('queued', 'running', 'retry');

  GET DIAGNOSTICS v_affected = ROW_COUNT;
  PERFORM public.system_agent_refresh_run(p_run_id);

  RETURN jsonb_build_object(
    'ok', true,
    'runId', p_run_id,
    'companyId', p_company_id,
    'affectedJobs', v_affected
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.system_agent_get_job_execution_control_v1(
  p_job_id uuid,
  p_lease_token uuid
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'jobId', job.id,
    'companyId', job.company_id,
    'leaseValid', job.status = 'running' AND job.lease_token = p_lease_token,
    'cancelRequested', job.cancel_requested_at IS NOT NULL,
    'cancelReason', job.cancel_reason,
    'enabled', COALESCE(control.enabled, true),
    'paused', COALESCE(control.paused, false),
    'killSwitch', COALESCE(control.kill_switch, false)
  )
  INTO v_result
  FROM public.system_agent_jobs job
  LEFT JOIN public.system_agent_controls control ON control.company_id = job.company_id
  WHERE job.id = p_job_id;

  IF v_result IS NULL THEN
    RAISE EXCEPTION 'System agent job not found';
  END IF;

  RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.system_agent_cancel_claimed_job_v1(
  p_job_id uuid,
  p_lease_token uuid,
  p_reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_job public.system_agent_jobs%ROWTYPE;
BEGIN
  UPDATE public.system_agent_jobs job
  SET status = 'cancelled',
      cancel_requested_at = COALESCE(job.cancel_requested_at, now()),
      cancel_reason = COALESCE(NULLIF(left(COALESCE(p_reason, ''), 1000), ''), job.cancel_reason, 'cooperative_cancel'),
      cancelled_at = now(),
      finished_at = now(),
      lease_token = NULL,
      lease_expires_at = NULL,
      heartbeat_at = now(),
      updated_at = now()
  WHERE job.id = p_job_id
    AND job.status = 'running'
    AND job.lease_token = p_lease_token
  RETURNING job.* INTO v_job;

  IF v_job.id IS NULL THEN
    RAISE EXCEPTION 'System agent job lease is no longer valid';
  END IF;

  PERFORM public.system_agent_refresh_run(v_job.run_id);
  RETURN to_jsonb(v_job);
END;
$function$;

CREATE OR REPLACE FUNCTION public.system_agent_claim_job(
  p_job_id uuid,
  p_lease_seconds integer DEFAULT 90
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_token uuid := gen_random_uuid();
  v_job public.system_agent_jobs%ROWTYPE;
BEGIN
  UPDATE public.system_agent_jobs job
  SET status = 'running',
      lease_token = v_token,
      lease_expires_at = now() + make_interval(secs => LEAST(300, GREATEST(30, p_lease_seconds))),
      heartbeat_at = now(),
      started_at = COALESCE(job.started_at, now()),
      processed_batches = job.processed_batches + 1,
      owner_profile_id = COALESCE(job.owner_profile_id, control.owner_profile_id),
      updated_at = now()
  FROM (
    SELECT candidate_job.id,
           candidate.owner_profile_id,
           candidate.enabled,
           candidate.paused,
           candidate.kill_switch
    FROM public.system_agent_jobs candidate_job
    LEFT JOIN public.system_agent_controls candidate
      ON candidate.company_id = candidate_job.company_id
    WHERE candidate_job.id = p_job_id
  ) control
  WHERE job.id = p_job_id
    AND job.cancel_requested_at IS NULL
    AND COALESCE(control.enabled, true)
    AND NOT COALESCE(control.paused, false)
    AND NOT COALESCE(control.kill_switch, false)
    AND job.attempts < job.max_attempts
    AND (
      (job.status IN ('queued', 'retry') AND job.next_attempt_at <= now())
      OR (job.status = 'running' AND job.lease_expires_at < now())
    )
  RETURNING job.* INTO v_job;

  IF v_job.id IS NULL THEN
    RETURN NULL;
  END IF;
  RETURN to_jsonb(v_job);
END;
$function$;

CREATE OR REPLACE FUNCTION public.system_agent_refresh_run(p_run_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_total integer;
  v_completed integer;
  v_failed integer;
  v_cancelled integer;
  v_active integer;
  v_status text;
  v_summary jsonb;
BEGIN
  SELECT
    count(*),
    count(*) FILTER (WHERE status = 'completed'),
    count(*) FILTER (WHERE status = 'failed'),
    count(*) FILTER (WHERE status = 'cancelled'),
    count(*) FILTER (WHERE status IN ('queued', 'running', 'retry'))
  INTO v_total, v_completed, v_failed, v_cancelled, v_active
  FROM public.system_agent_jobs
  WHERE run_id = p_run_id;

  v_status := CASE
    WHEN v_active > 0 THEN 'running'
    WHEN v_total > 0 AND v_cancelled = v_total THEN 'cancelled'
    WHEN v_failed = 0 AND v_cancelled = 0 AND v_completed = v_total THEN 'completed'
    WHEN v_completed > 0 OR v_cancelled > 0 THEN 'partial'
    ELSE 'failed'
  END;

  SELECT jsonb_build_object(
    'jobs', jsonb_build_object(
      'total', v_total,
      'completed', v_completed,
      'failed', v_failed,
      'cancelled', v_cancelled,
      'active', v_active
    ),
    'findings', jsonb_build_object(
      'total', count(*),
      'repaired', count(*) FILTER (WHERE status = 'repaired'),
      'review', count(*) FILTER (WHERE status = 'review'),
      'failed', count(*) FILTER (WHERE status = 'failed'),
      'planned', count(*) FILTER (WHERE status IN ('detected', 'planned'))
    )
  ) INTO v_summary
  FROM public.system_agent_findings
  WHERE run_id = p_run_id;

  UPDATE public.system_agent_runs
  SET status = v_status,
      summary = v_summary,
      finished_at = CASE WHEN v_active = 0 THEN now() ELSE NULL END,
      updated_at = now()
  WHERE id = p_run_id;

  RETURN jsonb_build_object('status', v_status, 'summary', v_summary);
END;
$function$;

CREATE OR REPLACE FUNCTION public.system_agent_finish_job(
  p_job_id uuid,
  p_lease_token uuid,
  p_success boolean,
  p_has_more boolean DEFAULT false,
  p_cursor jsonb DEFAULT '{}'::jsonb,
  p_stats jsonb DEFAULT '{}'::jsonb,
  p_error text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_job public.system_agent_jobs%ROWTYPE;
BEGIN
  UPDATE public.system_agent_jobs job
      SET status = CASE
        WHEN job.cancel_requested_at IS NOT NULL OR COALESCE(control.kill_switch, false) THEN 'cancelled'
        WHEN NOT COALESCE(control.enabled, true) OR COALESCE(control.paused, false) THEN 'queued'
        WHEN p_success AND p_has_more THEN 'queued'
        WHEN p_success THEN 'completed'
        WHEN job.attempts + 1 < job.max_attempts THEN 'retry'
        ELSE 'failed'
      END,
      attempts = CASE
        WHEN p_success
          OR job.cancel_requested_at IS NOT NULL
          OR COALESCE(control.kill_switch, false)
          OR NOT COALESCE(control.enabled, true)
          OR COALESCE(control.paused, false)
        THEN job.attempts
        ELSE job.attempts + 1
      END,
      cursor = COALESCE(p_cursor, job.cursor),
      stats = COALESCE(p_stats, job.stats),
      last_error = CASE
        WHEN p_success
          OR job.cancel_requested_at IS NOT NULL
          OR COALESCE(control.kill_switch, false)
          OR NOT COALESCE(control.enabled, true)
          OR COALESCE(control.paused, false)
        THEN NULL
        ELSE left(COALESCE(p_error, 'Unknown worker failure'), 4000)
      END,
      next_attempt_at = CASE
        WHEN job.cancel_requested_at IS NOT NULL
          OR COALESCE(control.kill_switch, false)
          OR NOT COALESCE(control.enabled, true)
          OR COALESCE(control.paused, false)
          OR p_success
        THEN now()
        ELSE now() + interval '30 seconds'
      END,
      finished_at = CASE
        WHEN job.cancel_requested_at IS NOT NULL OR COALESCE(control.kill_switch, false) THEN now()
        WHEN NOT COALESCE(control.enabled, true) OR COALESCE(control.paused, false) THEN NULL
        WHEN p_success AND NOT p_has_more THEN now()
        WHEN NOT p_success AND job.attempts + 1 >= job.max_attempts THEN now()
        ELSE NULL
      END,
      cancelled_at = CASE
        WHEN job.cancel_requested_at IS NOT NULL OR COALESCE(control.kill_switch, false) THEN now()
        ELSE job.cancelled_at
      END,
      cancel_requested_at = CASE
        WHEN COALESCE(control.kill_switch, false) THEN COALESCE(job.cancel_requested_at, now())
        ELSE job.cancel_requested_at
      END,
      cancel_reason = CASE
        WHEN COALESCE(control.kill_switch, false) THEN COALESCE(job.cancel_reason, 'company_kill_switch')
        ELSE job.cancel_reason
      END,
      lease_token = NULL,
      lease_expires_at = NULL,
      heartbeat_at = now(),
      updated_at = now()
  FROM (
    SELECT
      candidate_job.id,
      candidate.enabled,
      candidate.paused,
      candidate.kill_switch
    FROM public.system_agent_jobs candidate_job
    LEFT JOIN public.system_agent_controls candidate
      ON candidate.company_id = candidate_job.company_id
    WHERE candidate_job.id = p_job_id
  ) control
  WHERE job.id = p_job_id
    AND job.status = 'running'
    AND job.lease_token = p_lease_token
  RETURNING job.* INTO v_job;

  IF v_job.id IS NULL THEN
    RAISE EXCEPTION 'System agent job lease is no longer valid';
  END IF;

  PERFORM public.system_agent_refresh_run(v_job.run_id);
  RETURN to_jsonb(v_job);
END;
$function$;

REVOKE ALL ON FUNCTION public.system_agent_prepare_job_v1() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_get_company_control_v1(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_set_company_control_v1(uuid,boolean,boolean,boolean,text,uuid,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_request_cancel_v1(uuid,uuid,uuid,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_get_job_execution_control_v1(uuid,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_cancel_claimed_job_v1(uuid,uuid,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_claim_job(uuid,integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_refresh_run(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.system_agent_finish_job(uuid,uuid,boolean,boolean,jsonb,jsonb,text) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.system_agent_get_company_control_v1(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_agent_set_company_control_v1(uuid,boolean,boolean,boolean,text,uuid,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_agent_request_cancel_v1(uuid,uuid,uuid,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_agent_get_job_execution_control_v1(uuid,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_agent_cancel_claimed_job_v1(uuid,uuid,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_agent_claim_job(uuid,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_agent_refresh_run(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_agent_finish_job(uuid,uuid,boolean,boolean,jsonb,jsonb,text) TO service_role;

COMMIT;
