-- Bank <-> ledger bridge:
--  * completed bank transactions generate a balanced journal automatically when
--    their counter-account is determinable (manual counterpart, linked payment
--    journal, or a bank-to-bank transfer); dated in the future they stay drafts;
--  * sync_ledger_to_bank_v1 mirrors posted ledger movements on bank accounts
--    into bank_transactions (linked via journal_entry_id) and recalculates the
--    module balances — closing the 270K-vs-2.67M gap;
--  * post_bank_transaction_journal_v1 lets the reconciliation screen post a
--    completed transaction against an explicitly chosen counterpart account.
BEGIN;
SET LOCAL lock_timeout = '5s';

-- ---------------------------------------------------------------------------
-- 1. Automatic journal for completed bank transactions.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_bank_transaction_journal_fn()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $fn$
DECLARE
  v_bank_account uuid;
  v_counter_account uuid;
  v_je uuid;
  v_amount numeric;
  v_is_in boolean;
  v_today date := (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Qatar')::date;
BEGIN
  IF COALESCE(current_setting('app.financial_controls_bypass', true), '') = 'on' THEN RETURN COALESCE(NEW, OLD); END IF;
  IF NEW.status <> 'completed' OR NEW.journal_entry_id IS NOT NULL THEN RETURN NEW; END IF;

  SELECT b.chart_of_accounts_id INTO v_bank_account FROM public.banks b WHERE b.id = NEW.bank_id;
  IF v_bank_account IS NULL THEN
    SELECT m.chart_of_accounts_id INTO v_bank_account
    FROM public.account_mappings m JOIN public.default_account_types t ON t.id = m.default_account_type_id
    WHERE m.company_id = NEW.company_id AND t.type_code = 'BANK' AND COALESCE(m.is_active, true)
    LIMIT 1;
  END IF;
  IF v_bank_account IS NULL THEN RETURN NEW; END IF;

  v_counter_account := NEW.manual_counterpart_account_id;
  IF v_counter_account IS NULL AND NEW.payment_id IS NOT NULL THEN
    SELECT p.journal_entry_id INTO v_je FROM public.payments p WHERE p.id = NEW.payment_id;
    IF v_je IS NOT NULL THEN
      NEW.journal_entry_id := v_je;
      RETURN NEW;
    END IF;
  END IF;
  IF v_counter_account IS NULL AND NEW.counterpart_bank_id IS NOT NULL THEN
    SELECT cb.chart_of_accounts_id INTO v_counter_account FROM public.banks cb WHERE cb.id = NEW.counterpart_bank_id;
    IF v_counter_account IS NULL THEN
      SELECT m.chart_of_accounts_id INTO v_counter_account
      FROM public.account_mappings m JOIN public.default_account_types t ON t.id = m.default_account_type_id
      WHERE m.company_id = NEW.company_id AND t.type_code = 'BANK' AND COALESCE(m.is_active, true)
      LIMIT 1;
    END IF;
  END IF;
  IF v_counter_account IS NULL OR v_counter_account = v_bank_account THEN RETURN NEW; END IF;

  v_amount := COALESCE(NEW.amount, 0);
  IF v_amount <= 0 THEN RETURN NEW; END IF;
  v_is_in := NEW.transaction_type IN ('deposit', 'transfer_in', 'interest', 'fee_reversal');

  v_je := gen_random_uuid();
  INSERT INTO public.journal_entries (
    id, company_id, entry_number, entry_date, description, reference_type, reference_id,
    total_debit, total_credit, status, created_by, workflow_notes
  ) VALUES (
    v_je, NEW.company_id,
    'BNK-' || to_char(COALESCE(NEW.transaction_date, CURRENT_DATE), 'YYYYMMDD') || '-' || left(NEW.id::text, 8),
    COALESCE(NEW.transaction_date, CURRENT_DATE),
    'حركة بنك - ' || COALESCE(NEW.description, NEW.transaction_number, NEW.id::text),
    'bank_transaction', NEW.id,
    v_amount, v_amount, 'draft', NEW.created_by,
    'Generated by bank transaction trigger'
  );
  INSERT INTO public.journal_entry_lines (journal_entry_id, account_id, line_number, line_description, debit_amount, credit_amount)
  VALUES
    (v_je, CASE WHEN v_is_in THEN v_bank_account ELSE v_counter_account END, 1,
      'حركة بنك - ' || COALESCE(NEW.description, NEW.id::text), CASE WHEN v_is_in THEN v_amount ELSE 0 END, CASE WHEN v_is_in THEN 0 ELSE v_amount END),
    (v_je, CASE WHEN v_is_in THEN v_counter_account ELSE v_bank_account END, 2,
      'الطرف المقابل لحركة بنك - ' || COALESCE(NEW.description, NEW.id::text), CASE WHEN v_is_in THEN 0 ELSE v_amount END, CASE WHEN v_is_in THEN v_amount ELSE 0 END);

  IF COALESCE(NEW.transaction_date, CURRENT_DATE) <= v_today THEN
    UPDATE public.journal_entries SET status = 'posted', posted_at = now(), updated_at = now() WHERE id = v_je;
  END IF;

  NEW.journal_entry_id := v_je;
  RETURN NEW;
END;
$fn$;
REVOKE ALL ON FUNCTION public.trg_bank_transaction_journal_fn() FROM PUBLIC, anon, authenticated, service_role;
DROP TRIGGER IF EXISTS trg_bank_transaction_journal ON public.bank_transactions;
CREATE TRIGGER trg_bank_transaction_journal
  BEFORE INSERT OR UPDATE OF status ON public.bank_transactions
  FOR EACH ROW EXECUTE FUNCTION public.trg_bank_transaction_journal_fn();

-- ---------------------------------------------------------------------------
-- 2. Ledger -> bank module sync: create the missing bank transactions and
--    recalculate the module balances from the ledger.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sync_ledger_to_bank_v1(
  p_company_id uuid,
  p_actor_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $fn$
DECLARE
  v_actor uuid := COALESCE(auth.uid(), p_actor_id);
  v_created integer := 0;
  v_amount numeric := 0;
  v_today date := (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Qatar')::date;
  r record;
  v_txn uuid;
  v_bank uuid;
  v_net numeric;
  v_running numeric := 0;
BEGIN
  IF auth.uid() IS NOT NULL AND public.get_user_company_id() IS DISTINCT FROM p_company_id THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE = '42501';
  END IF;
  IF v_actor IS NULL AND COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Authentication is required' USING ERRCODE = '42501';
  END IF;

  -- Running balance seed: latest transaction balance, else the bank opening.
  SELECT COALESCE((
    SELECT t.balance_after FROM public.bank_transactions t
    JOIN public.banks b ON b.id = t.bank_id
    WHERE b.company_id = p_company_id
    ORDER BY t.transaction_date DESC, t.created_at DESC LIMIT 1
  ), COALESCE((SELECT b2.opening_balance FROM public.banks b2 WHERE b2.company_id = p_company_id LIMIT 1), 0))
  INTO v_running;

  FOR r IN
    SELECT e.id, e.entry_date, e.description,
      sum(COALESCE(l.debit_amount,0) - COALESCE(l.credit_amount,0)) AS net_move,
      (array_agg(l.account_id ORDER BY l.line_number))[1] AS first_bank_account
    FROM public.journal_entries e
    JOIN public.journal_entry_lines l ON l.journal_entry_id = e.id
    WHERE e.company_id = p_company_id AND e.status = 'posted'
      AND NOT EXISTS (SELECT 1 FROM public.bank_transactions t WHERE t.journal_entry_id = e.id)
      AND l.account_id IN (
        SELECT b.chart_of_accounts_id FROM public.banks b WHERE b.company_id = p_company_id AND b.chart_of_accounts_id IS NOT NULL
        UNION
        SELECT m.chart_of_accounts_id FROM public.account_mappings m
        JOIN public.default_account_types t ON t.id = m.default_account_type_id
        WHERE m.company_id = p_company_id AND t.type_code = 'BANK' AND COALESCE(m.is_active, true)
      )
    GROUP BY e.id, e.entry_date, e.description
    HAVING ABS(sum(COALESCE(l.debit_amount,0) - COALESCE(l.credit_amount,0))) > 0.01
    ORDER BY e.entry_date, e.id
    LIMIT 1000
  LOOP
    v_net := r.net_move;
    v_txn := gen_random_uuid();
    SELECT b.id INTO v_bank FROM public.banks b
    WHERE b.company_id = p_company_id AND b.chart_of_accounts_id = r.first_bank_account
       OR (b.company_id = p_company_id AND b.chart_of_accounts_id IS NULL AND b.is_primary)
    LIMIT 1;
    IF v_bank IS NULL THEN
      SELECT b.id INTO v_bank FROM public.banks b WHERE b.company_id = p_company_id LIMIT 1;
    END IF;
    IF v_bank IS NULL THEN CONTINUE; END IF;

    v_running := v_running + CASE WHEN v_net > 0 THEN ABS(v_net) ELSE -ABS(v_net) END;
    INSERT INTO public.bank_transactions (
      id, company_id, bank_id, transaction_date, transaction_type, amount, balance_after, description,
      transaction_number, status, journal_entry_id, reconciled, created_by, reference_number
    ) VALUES (
      v_txn, p_company_id, v_bank, r.entry_date,
      CASE WHEN v_net > 0 THEN 'deposit' ELSE 'withdrawal' END,
      ABS(v_net), v_running, COALESCE(r.description, 'Ledger sync'),
      'LGS-' || to_char(r.entry_date, 'YYYYMMDD') || '-' || left(r.id::text, 8),
      'completed', r.id, true, v_actor, 'LEDGER-SYNC'
    );
    v_created := v_created + 1;
    v_amount := v_amount + ABS(v_net);
  END LOOP;

  -- Recalculate module balances: opening + net posted transactions per bank.
  UPDATE public.banks b
  SET current_balance = COALESCE(b.opening_balance, 0) + COALESCE((
    SELECT sum(CASE WHEN t.transaction_type IN ('deposit','transfer_in','interest','fee_reversal') THEN t.amount ELSE -t.amount END)
    FROM public.bank_transactions t
    WHERE t.bank_id = b.id AND t.status = 'completed'
  ), 0), updated_at = now()
  WHERE b.company_id = p_company_id;

  RETURN jsonb_build_object('createdTransactions', v_created, 'syncedAmount', v_amount, 'asOf', v_today);
END;
$fn$;
REVOKE ALL ON FUNCTION public.sync_ledger_to_bank_v1(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.sync_ledger_to_bank_v1(uuid, uuid) TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. Manual posting from the reconciliation screen (explicit counterpart).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.post_bank_transaction_journal_v1(
  p_company_id uuid,
  p_transaction_id uuid,
  p_counterpart_account_id uuid,
  p_actor_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $fn$
DECLARE
  v_actor uuid := COALESCE(auth.uid(), p_actor_id);
  v_txn public.bank_transactions%ROWTYPE;
  v_bank_account uuid;
  v_je uuid;
  v_amount numeric;
  v_is_in boolean;
  v_today date := (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Qatar')::date;
BEGIN
  IF auth.uid() IS NOT NULL AND public.get_user_company_id() IS DISTINCT FROM p_company_id THEN
    RAISE EXCEPTION 'Company access denied' USING ERRCODE = '42501';
  END IF;
  IF v_actor IS NULL AND COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Authentication is required' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_txn FROM public.bank_transactions
  WHERE id = p_transaction_id AND company_id = p_company_id FOR UPDATE;
  IF v_txn.id IS NULL THEN RAISE EXCEPTION 'Bank transaction not found' USING ERRCODE = 'P0001'; END IF;
  IF v_txn.status <> 'completed' THEN RAISE EXCEPTION 'Only completed bank transactions can be posted' USING ERRCODE = 'P0001'; END IF;
  IF v_txn.journal_entry_id IS NOT NULL THEN RAISE EXCEPTION 'Bank transaction already has a journal' USING ERRCODE = 'P0001'; END IF;
  IF p_counterpart_account_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.chart_of_accounts a
    WHERE a.id = p_counterpart_account_id AND a.company_id = p_company_id
      AND COALESCE(a.is_header, false) = false AND COALESCE(a.account_level, 0) >= 3 AND COALESCE(a.is_active, true)
  ) THEN RAISE EXCEPTION 'A postable counterpart account is required' USING ERRCODE = 'P0001'; END IF;

  SELECT COALESCE(b.chart_of_accounts_id, (
    SELECT m.chart_of_accounts_id FROM public.account_mappings m
    JOIN public.default_account_types t ON t.id = m.default_account_type_id
    WHERE m.company_id = p_company_id AND t.type_code = 'BANK' AND COALESCE(m.is_active, true) LIMIT 1
  )) INTO v_bank_account FROM public.banks b WHERE b.id = v_txn.bank_id;
  IF v_bank_account IS NULL OR v_bank_account = p_counterpart_account_id THEN
    RAISE EXCEPTION 'Bank ledger account is not resolvable' USING ERRCODE = 'P0001';
  END IF;

  v_amount := COALESCE(v_txn.amount, 0);
  IF v_amount <= 0 THEN RAISE EXCEPTION 'Bank transaction amount must be positive' USING ERRCODE = 'P0001'; END IF;
  v_is_in := v_txn.transaction_type IN ('deposit', 'transfer_in', 'interest', 'fee_reversal');
  v_je := gen_random_uuid();

  INSERT INTO public.journal_entries (
    id, company_id, entry_number, entry_date, description, reference_type, reference_id,
    total_debit, total_credit, status, created_by, workflow_notes
  ) VALUES (
    v_je, p_company_id,
    'BNK-' || to_char(COALESCE(v_txn.transaction_date, CURRENT_DATE), 'YYYYMMDD') || '-' || left(v_txn.id::text, 8),
    COALESCE(v_txn.transaction_date, CURRENT_DATE),
    'حركة بنك - ' || COALESCE(v_txn.description, v_txn.transaction_number, v_txn.id::text),
    'bank_transaction', v_txn.id, v_amount, v_amount, 'draft', v_actor,
    'Posted from the bank reconciliation screen'
  );
  INSERT INTO public.journal_entry_lines (journal_entry_id, account_id, line_number, line_description, debit_amount, credit_amount)
  VALUES
    (v_je, CASE WHEN v_is_in THEN v_bank_account ELSE p_counterpart_account_id END, 1,
      'حركة بنك - ' || COALESCE(v_txn.description, v_txn.id::text), CASE WHEN v_is_in THEN v_amount ELSE 0 END, CASE WHEN v_is_in THEN 0 ELSE v_amount END),
    (v_je, CASE WHEN v_is_in THEN p_counterpart_account_id ELSE v_bank_account END, 2,
      'الطرف المقابل لحركة بنك - ' || COALESCE(v_txn.description, v_txn.id::text), CASE WHEN v_is_in THEN 0 ELSE v_amount END, CASE WHEN v_is_in THEN v_amount ELSE 0 END);

  IF COALESCE(v_txn.transaction_date, CURRENT_DATE) <= v_today THEN
    UPDATE public.journal_entries SET status = 'posted', posted_at = now(), updated_at = now() WHERE id = v_je;
  END IF;

  UPDATE public.bank_transactions SET journal_entry_id = v_je, updated_at = now() WHERE id = v_txn.id;
  RETURN jsonb_build_object('journalEntryId', v_je, 'status', CASE WHEN COALESCE(v_txn.transaction_date, CURRENT_DATE) <= v_today THEN 'posted' ELSE 'draft' END);
END;
$fn$;
REVOKE ALL ON FUNCTION public.post_bank_transaction_journal_v1(uuid, uuid, uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.post_bank_transaction_journal_v1(uuid, uuid, uuid, uuid) TO authenticated, service_role;

NOTIFY pgrst,'reload schema';
COMMIT;
