// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseConfig, debugLog, securityLog } from '@/lib/env';

// Get Supabase configuration securely
let supabaseConfig: ReturnType<typeof getSupabaseConfig>;

try {
  supabaseConfig = getSupabaseConfig();
  debugLog('Supabase config loaded successfully', {
    hasUrl: !!supabaseConfig.url,
    hasKey: !!supabaseConfig.anonKey
  });
} catch (error) {
  console.error('❌ [SUPABASE] Failed to load Supabase configuration:', error);
  throw error;
}

// Validate configuration
if (!supabaseConfig.url || !supabaseConfig.anonKey) {
  const error = 'Missing required Supabase configuration';
  securityLog(error, {
    hasUrl: !!supabaseConfig.url,
    hasKey: !!supabaseConfig.anonKey
  });
  throw new Error(error);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseConfig.url, supabaseConfig.anonKey, {
  auth: {
    storage: localStorage,
    storageKey: 'fleetify-auth-token', // Unique key to avoid conflicts
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Detect session from URL for OAuth flows
    flowType: 'pkce', // Use PKCE flow for better security
  }
});

// Export configuration for secure access if needed
export { supabaseConfig };