// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseConfig, debugLog, securityLog } from '@/lib/env';
import { createCapacitorStorageAdapter } from '@/lib/capacitorStorage';

// Get Supabase configuration securely
let supabaseConfig: ReturnType<typeof getSupabaseConfig>;

try {
  supabaseConfig = getSupabaseConfig();
  debugLog('Supabase config loaded successfully', {
    hasUrl: !!supabaseConfig.url,
    hasKey: !!supabaseConfig.anonKey
  });
} catch (error) {
  console.error('❌ [SUPABASE] Failed to load Supabase configuration:', error);
  throw error;
}

// Validate configuration
if (!supabaseConfig.url || !supabaseConfig.anonKey) {
  const error = 'Missing required Supabase configuration';
  securityLog(error, {
    hasUrl: !!supabaseConfig.url,
    hasKey: !!supabaseConfig.anonKey
  });
  throw new Error(error);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseConfig.url, supabaseConfig.anonKey, {
  auth: {
    storage: createCapacitorStorageAdapter(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Enable cross-tab sync via BroadcastChannel API
    // By not specifying storageKey, Supabase will handle multi-tab sync automatically
  },
  // Add retry logic for better reliability
  global: {
    headers: { 'x-client-info': 'fleetify-web' },
    fetch: async (url, options, retries = 2, delay = 1000) => {
      // Add timeout to prevent hanging requests with retry logic
      for (let attempt = 0; attempt <= retries; attempt++) {
        try {
          const timeoutMs = 25000; // Increased to 25s for slow networks
          const response = await Promise.race([
            fetch(url, options),
            new Promise((_, reject) =>
              setTimeout(() => {
                console.warn(`[SUPABASE] Attempt ${attempt + 1}: Request timed out after ${timeoutMs}ms:`, url);
                reject(new Error('Request timeout'));
              }, timeoutMs)
            )
          ]);

          if (response.ok || attempt === retries - 1) {
            return response;
          }
        } catch (error) {
          if (attempt === retries - 1) {
            console.error(`[SUPABASE] All ${retries} attempts failed for:`, url);
            throw error;
          }
          console.warn(`[SUPABASE] Attempt ${attempt + 1} failed, retrying in ${delay}ms...`, error);
          await new Promise(resolve => setTimeout(resolve, delay));
          delay *= 2; // Exponential backoff
        }
      }
    },
  },
  // Realtime configuration for better performance
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Export configuration for secure access if needed
export { supabaseConfig };