export const editCopy = {
  ar: {
    title: 'تعديل العقد', eyebrow: 'إدارة العقود / تحديث البيانات',
    intro: 'عدّل البيانات، ثم راجع أثر التغييرات قبل اعتمادها.',
    edit: 'تعديل البيانات', review: 'مراجعة التغييرات',
    basics: 'مرجع العقد', basicsHint: 'بيانات العقد المعتمدة التي يستند إليها التعديل.',
    customer: 'العميل', currentCustomer: 'عميل العقد الحالي', type: 'نوع العقد',
    start: 'تاريخ البداية', monthly: 'الإيجار الشهري', status: 'الحالة',
    fixedTerms: 'العميل ونوع العقد وتاريخ البداية والإيجار الشهري بيانات ثابتة في هذا الإجراء.',
    vehicle: 'المركبة', vehicleHint: 'أبقِ المركبة الحالية أو اختر بديلًا متاحًا.',
    currentVehicle: 'مركبة العقد الحالية', selectedVehicle: 'المركبة المختارة', changeVehicle: 'اختيار مركبة بديلة',
    vehicleSearch: 'ابحث برقم اللوحة أو الشركة أو الطراز', searchHelp: 'اكتب رقم اللوحة للوصول مباشرة إلى المركبة المطلوبة.',
    available: 'متاحة', current: 'الحالية', noVehicles: 'لا توجد مركبات مطابقة للبحث.',
    loadVehicles: 'جاري تحميل المركبات…', vehicleError: 'تعذر تحميل المركبات. حاول مجددًا.', retry: 'إعادة المحاولة',
    backToCurrent: 'الإبقاء على المركبة الحالية', closeSearch: 'إغلاق البحث',
    extension: 'مدة العقد', extensionHint: 'مدّد تاريخ الانتهاء مع معاينة قيمة العقد الجديدة.',
    currentEnd: 'الانتهاء الحالي', newEnd: 'تاريخ الانتهاء', datePlaceholder: 'اختر تاريخ الانتهاء',
    extensionRule: 'تُحسب الزيادة للشهور الإضافية وفق الإيجار الشهري الحالي.',
    sameMonth: 'التمديد داخل شهر الانتهاء نفسه لا يضيف شهرًا جديدًا إلى قيمة العقد.',
    invalidDate: 'اختر تاريخ انتهاء صحيحًا.', earlierDate: 'لا يمكن تقليص المدة من هنا. اختر تاريخًا لا يسبق انتهاء العقد الحالي.',
    operationalLocked: 'تغيير المركبة وتمديد المدة متاحان للعقود النشطة ذات الإيجار الشهري. يمكنك تعديل الملاحظات لهذا العقد.',
    notes: 'ملاحظات العقد', notesHint: 'دوّن المعلومات التي يحتاجها فريق المتابعة.',
    notesPlaceholder: 'أي ملاحظات إضافية...', emptyNotes: 'لا توجد ملاحظات',
    summary: 'ملخص التعديل', noChanges: 'لم تُجرَ تغييرات بعد', changes: 'تغييرات للمراجعة',
    before: 'قبل التعديل', after: 'بعد التعديل', currentAmount: 'قيمة العقد الحالية',
    newAmount: 'القيمة بعد التعديل', difference: 'زيادة قيمة العقد', noDifference: 'دون تغيير في قيمة العقد',
    noFinancialChanges: 'تعديل الملاحظات وحده لا يغيّر قيمة العقد.',
    previewHint: 'القيم المعروضة معاينة للتعديل؛ يُؤكد الحفظ بعد استجابة النظام.',
    reviewTitle: 'راجع ما سيتغير', reviewHint: 'تحقق من القيم التالية قبل حفظ التعديلات على العقد.',
    noChangesHint: 'اختر مركبة أو مدّد المدة أو حدّث الملاحظات ليظهر الملخص هنا.',
    undo: 'تراجع', cancel: 'إلغاء', next: 'التالي', nextHint: 'مراجعة قبل الحفظ',
    back: 'العودة للتعديل', save: 'حفظ التعديلات', saving: 'جاري الحفظ…',
    unsaved: 'تغييرات غير محفوظة', unchanged: 'لا توجد تغييرات غير محفوظة',
    discardTitle: 'تجاهل التغييرات؟', discardText: 'لديك تعديلات لم تُحفظ. يمكنك متابعة التحرير أو الخروج دون حفظ.',
    keepEditing: 'متابعة التعديل', discard: 'تجاهل والخروج',
    saved: 'تم تحديث العقد بنجاح!', failed: 'تعذر حفظ التعديل. بقيت بياناتك كما أدخلتها.',
    companyChanged: 'تغير العقد أو الشركة أثناء التعديل؛ أغلق النافذة وافتح العقد مجددًا.',
    newerVersion: 'توجد نسخة أحدث من العقد. يحافظ هذا النموذج على البيانات التي بدأت منها؛ قد يطلب النظام إعادة تحميلها قبل الحفظ.',
    refreshFailed: 'تم الحفظ، لكن تعذر تحديث بعض البيانات المعروضة. أعد تحميل صفحة العقد.',
    noVehicle: 'اختر المركبة قبل حفظ التمديد.', changesSaved: 'تُحفظ التغييرات معًا بعد المراجعة.',
  },
  en: {
    title: 'Edit contract', eyebrow: 'Contracts / Update details',
    intro: 'Update the details, then review the changes before saving.',
    edit: 'Edit details', review: 'Review changes',
    basics: 'Contract reference', basicsHint: 'The existing contract details used for this update.',
    customer: 'Customer', currentCustomer: 'Current contract customer', type: 'Contract type',
    start: 'Start date', monthly: 'Monthly rent', status: 'Status',
    fixedTerms: 'Customer, contract type, start date and monthly rent stay fixed in this workflow.',
    vehicle: 'Vehicle', vehicleHint: 'Keep the current vehicle or select an available replacement.',
    currentVehicle: 'Current contract vehicle', selectedVehicle: 'Selected vehicle', changeVehicle: 'Choose a replacement',
    vehicleSearch: 'Search plate, make or model', searchHelp: 'Enter a plate number to find a specific vehicle.',
    available: 'Available', current: 'Current', noVehicles: 'No vehicles match your search.',
    loadVehicles: 'Loading vehicles…', vehicleError: 'Unable to load vehicles. Please try again.', retry: 'Try again',
    backToCurrent: 'Keep the current vehicle', closeSearch: 'Close search',
    extension: 'Contract duration', extensionHint: 'Extend the end date and preview the updated contract value.',
    currentEnd: 'Current end date', newEnd: 'End date', datePlaceholder: 'Choose end date',
    extensionRule: 'Additional months use the existing monthly rent.',
    sameMonth: 'An extension within the same end month does not add another billing month.',
    invalidDate: 'Choose a valid end date.', earlierDate: 'Shortening the term requires settlement. Choose a date on or after the current end date.',
    operationalLocked: 'Vehicle changes and extensions are available for active contracts with monthly rent. You can update the notes for this contract.',
    notes: 'Contract notes', notesHint: 'Add information useful to the follow-up team.',
    notesPlaceholder: 'Any additional notes...', emptyNotes: 'No notes',
    summary: 'Change summary', noChanges: 'No changes yet', changes: 'changes to review',
    before: 'Before', after: 'After', currentAmount: 'Current contract value',
    newAmount: 'Updated value', difference: 'Increase in value', noDifference: 'Contract value unchanged',
    noFinancialChanges: 'Changing notes alone does not change the contract value.',
    previewHint: 'These values preview the update. Saving is confirmed by the system.',
    reviewTitle: 'Review what will change', reviewHint: 'Check these values before saving your contract changes.',
    noChangesHint: 'Choose a vehicle, extend the term or update the notes to see a summary here.',
    undo: 'Undo', cancel: 'Cancel', next: 'Next', nextHint: 'Review before saving',
    back: 'Back to editing', save: 'Save changes', saving: 'Saving…',
    unsaved: 'Unsaved changes', unchanged: 'No unsaved changes',
    discardTitle: 'Discard your changes?', discardText: 'You have unsaved changes. Continue editing or leave without saving.',
    keepEditing: 'Continue editing', discard: 'Discard and leave',
    saved: 'Contract updated successfully!', failed: 'Could not save. Your changes are still available.',
    companyChanged: 'The contract or company changed. Close the editor and reopen the contract.',
    newerVersion: 'A newer version of this contract is available. This form preserves your original snapshot; you may need to reload before saving.',
    refreshFailed: 'Saved, but some displayed data could not refresh. Reload the contract page.',
    noVehicle: 'Choose a vehicle before saving the extension.', changesSaved: 'Changes are saved together after review.',
  },
};
