import type { BalanceSheetAccount, BalanceSheetTotals, ProfessionalBalanceSheet } from '../../../src/types/balanceSheet';
import type { FinancialStatementColumn, FinancialStatementConfiguration, FinancialStatementNote, FinancialStatementRow, FinancialStatementSection, ProfessionalFinancialStatementPackage, SavedFinancialStatementPackage } from '../../../src/types/financialStatementPackage';

export const fixtureCompanyId = '11111111-1111-4111-8111-111111111111';
export const fixturePreparerId = '22222222-2222-4222-8222-222222222222';
export const fixtureReviewerId = '33333333-3333-4333-8333-333333333333';
const fingerprint = 'a1b2c3d4'.repeat(8);
const account = (index: number, code: string, name: string, nameAr: string, type: BalanceSheetAccount['type'], classification: BalanceSheetAccount['classification'], balance: number, comparisonBalance: number): BalanceSheetAccount => ({
  id: `44444444-4444-4444-8444-${String(index).padStart(12, '0')}`, code, name, nameAr, type, classification, subtype: classification, level: 3, isHeader: false, isActive: true,
  debit: ['asset', 'expense'].includes(type) ? Math.max(0, balance) : Math.max(0, -balance), credit: ['asset', 'expense'].includes(type) ? Math.max(0, -balance) : Math.max(0, balance), balance, comparisonBalance,
});
const noteDefinitions: [FinancialStatementNote['code'], string, string][] = [
  ['entity', 'Reporting entity', 'المنشأة المعدة للتقرير'], ['basis', 'Basis of preparation', 'أساس الإعداد'], ['policies', 'Accounting policies', 'السياسات المحاسبية'],
  ['estimates', 'Estimates and judgments', 'التقديرات والأحكام'], ['assets', 'Property and equipment', 'الممتلكات والمعدات'], ['receivables', 'Receivables', 'الذمم المدينة'],
  ['liabilities', 'Liabilities', 'الالتزامات'], ['equity', 'Equity', 'حقوق الملكية'], ['related_parties', 'Related parties', 'الأطراف ذات العلاقة'], ['commitments', 'Commitments', 'الالتزامات التعاقدية'],
  ['subsequent_events', 'Subsequent events', 'الأحداث اللاحقة'], ['going_concern', 'Going concern', 'الاستمرارية'], ['noncash_transactions', 'Non-cash transactions', 'المعاملات غير النقدية'], ['interim_changes', 'Interim changes', 'التغيرات خلال الفترة المرحلية'],
];
const row = (key: string, en: string, ar: string, values: number[], kind: FinancialStatementRow['kind'] = 'line', notes: number[] = []): FinancialStatementRow => ({ key, labelEn: en, labelAr: ar, values, kind, accountIds: [], noteNumbers: notes });

export function makeFinancialStatementPackageFixture(stress = false): ProfessionalFinancialStatementPackage {
  const accounts = [account(1, '1101', 'Cash and bank', 'النقد والأرصدة لدى البنوك', 'asset', 'current', 1000, 800), account(2, '1201', 'Rental vehicles', 'سيارات التأجير', 'asset', 'non_current', 5000, 4500), account(3, '1202', 'Accumulated depreciation', 'مجمع الإهلاك', 'asset', 'non_current', -1000, -600), account(4, '2101', 'Trade payables', 'الذمم الدائنة', 'liability', 'current', 1200, 1100), account(5, '3101', 'Share capital', 'رأس المال', 'equity', 'equity', 2000, 2000), account(6, '3201', 'Retained earnings', 'الأرباح المحتجزة', 'equity', 'equity', 800, 900), account(7, '4101', 'Rental revenue', 'إيرادات التأجير', 'revenue', 'result', 1500, 1200), account(8, '5101', 'Operating expenses', 'مصروفات التشغيل', 'expense', 'result', 500, 500)];
  const totals = (comparison: boolean): BalanceSheetTotals => ({ assets: comparison ? 4700 : 5000, liabilities: comparison ? 1100 : 1200, equityAccounts: comparison ? 2900 : 2800, revenue: comparison ? 1200 : 1500, expenses: 500, unclosedResult: comparison ? 700 : 1000, equity: comparison ? 3600 : 3800, liabilitiesAndEquity: comparison ? 4700 : 5000, imbalance: 0, postedEntries: 120, postedLines: 300, draftEntries: 0 });
  const company: ProfessionalBalanceSheet['company'] = { id: fixtureCompanyId, name: 'Demonstration Fleet Company — TEST DATA', nameAr: 'شركة الأسطول التجريبية — بيانات اختبار', commercialRegister: 'TEST-000123', currency: 'QAR', address: 'Synthetic address — عنوان تجريبي' };
  const configuration: FinancialStatementConfiguration = {
    version: 1, kind: 'interim', scope: 'individual_entity', framework: 'IFRS', legalForm: 'llc', periodStart: '2026-01-01', periodEnd: '2026-08-31', positionComparisonDate: '2025-12-31', comparativePeriodStart: '2025-01-01', comparativePeriodEnd: '2025-08-31', thirdPositionDate: null, requiresThirdPosition: false,
    accountMappings: accounts.map((account, index) => ({ accountId: account.id, positionLine: (['cash', 'property_equipment', 'property_equipment', 'payables', 'share_capital', 'retained_earnings', null, null] as const)[index], comparisonPositionLine: null, thirdPositionLine: null, incomeLine: index === 6 ? 'rental_revenue' : index === 7 ? 'administrative_expenses' : null, cashFlowCategory: index === 1 ? 'investing' : 'operating', isCashEquivalent: index === 0, currentSplit: null, comparisonSplit: null, thirdSplit: null })),
    journalOverrides: [], notes: noteDefinitions.map(([code, titleEn, titleAr], index) => ({ code, number: index + 1, titleEn, titleAr, status: 'complete', text: `Synthetic disclosure ${index + 1}. بيانات إفصاح تجريبية معدة لاختبار شكل القوائم فقط.`, evidence: `TEST-EVIDENCE-${index + 1}` })), preparationNotes: 'Synthetic package for visual and functional tests only — حزمة تجريبية للاختبار فقط.',
  };
  const positionColumns: FinancialStatementColumn[] = [{ key: 'current', labelAr: 'الفترة الحالية', labelEn: 'Current', endDate: configuration.periodEnd }, { key: 'comparison', labelAr: 'المقارنة', labelEn: 'Comparative', endDate: configuration.positionComparisonDate }];
  const periodColumns: FinancialStatementColumn[] = [{ key: 'current', labelAr: 'الفترة الحالية', labelEn: 'Current period', startDate: configuration.periodStart, endDate: configuration.periodEnd }, { key: 'comparison', labelAr: 'الفترة المقارنة', labelEn: 'Comparative period', startDate: configuration.comparativePeriodStart, endDate: configuration.comparativePeriodEnd }];
  const equityColumns: FinancialStatementColumn[] = [
    { key: 'share_capital', labelEn: 'Share capital', labelAr: 'رأس المال' }, { key: 'statutory_reserve', labelEn: 'Statutory reserve', labelAr: 'الاحتياطي القانوني' }, { key: 'retained_earnings', labelEn: 'Retained earnings', labelAr: 'الأرباح المحتجزة' }, { key: 'other_reserves', labelEn: 'Other reserves', labelAr: 'احتياطيات أخرى' }, { key: 'other_equity', labelEn: 'Other equity', labelAr: 'حقوق ملكية أخرى' }, { key: 'total', labelEn: 'Total', labelAr: 'الإجمالي' },
  ];
  const equityRows = (comparative: boolean) => {
    const opening = comparative ? 1300 : 1600, profit = comparative ? 200 : 300, distributions = comparative ? 0 : -100, closing = opening + profit + distributions;
    return [row('opening', 'Opening balance', 'الرصيد الافتتاحي', [2000, 0, opening, 0, 0, 2000 + opening], 'total'), row('profit', 'Profit for the period', 'ربح الفترة', [0, 0, profit, 0, 0, profit]), row('oci', 'Other comprehensive income', 'الدخل الشامل الآخر', [0, 0, 0, 0, 0, 0]), row('contributions', 'Owner contributions', 'مساهمات الملاك', [0, 0, 0, 0, 0, 0]), row('distributions', 'Distributions to owners', 'توزيعات للملاك', [0, 0, distributions, 0, 0, distributions], 'line', [8]), row('transfers', 'Transfers', 'تحويلات', [0, 0, 0, 0, 0, 0]), row('prior_adjustments', 'Prior-period adjustments', 'تعديلات فترات سابقة', [0, 0, 0, 0, 0, 0]), row('other', 'Other movements', 'حركات أخرى', [0, 0, 0, 0, 0, 0]), row('closing', 'Closing balance', 'الرصيد الختامي', [2000, 0, closing, 0, 0, 2000 + closing], 'total'), row('ledger_closing', 'Closing ledger balance', 'الرصيد الختامي بالدفتر', [2000, 0, closing, 0, 0, 2000 + closing], 'total'), row('difference', 'Reconciliation difference', 'فرق المطابقة', [0, 0, 0, 0, 0, 0], 'reconciliation')];
  };
  const statements: FinancialStatementSection[] = [
    { key: 'position', titleEn: 'Statement of financial position', titleAr: 'قائمة المركز المالي', columns: positionColumns, rows: [
      row('cash', 'Cash and cash equivalents', 'النقد وما في حكمه', [1000, 800], 'line', [3]), row('property_equipment', 'Property and equipment, net', 'الممتلكات والمعدات، بالصافي', [4000, 3900], 'line', [5]), row('current_assets_total', 'Total current assets', 'إجمالي الأصول المتداولة', [1000, 800], 'subtotal'), row('noncurrent_assets_total', 'Total non-current assets', 'إجمالي الأصول غير المتداولة', [4000, 3900], 'subtotal'), row('assets_total', 'Total assets', 'إجمالي الأصول', [5000, 4700], 'total'),
      row('payables', 'Trade payables', 'الذمم الدائنة التجارية', [1200, 1100], 'line', [7]), row('current_liabilities_total', 'Total current liabilities', 'إجمالي الالتزامات المتداولة', [1200, 1100], 'subtotal'), row('noncurrent_liabilities_total', 'Total non-current liabilities', 'إجمالي الالتزامات غير المتداولة', [0, 0], 'subtotal'), row('liabilities_total', 'Total liabilities', 'إجمالي الالتزامات', [1200, 1100], 'total'), row('share_capital', 'Share capital', 'رأس المال', [2000, 2000], 'line', [8]), row('retained_earnings', 'Retained earnings including unclosed results', 'الأرباح المحتجزة شاملة النتيجة غير المقفلة', [1800, 1600], 'line', [8]), row('equity_total', 'Total equity', 'إجمالي حقوق الملكية', [3800, 3600], 'total'), row('liabilities_equity_total', 'Total liabilities and equity', 'إجمالي الالتزامات وحقوق الملكية', [5000, 4700], 'total'), row('position_difference', 'Accounting equation difference', 'فرق المعادلة المحاسبية', [0, 0], 'reconciliation'),
    ] },
    { key: 'profit_loss_oci', titleEn: 'Profit or loss and other comprehensive income', titleAr: 'قائمة الربح أو الخسارة والدخل الشامل الآخر', columns: periodColumns, rows: [
      row('rental_revenue', 'Rental revenue', 'إيرادات التأجير', [2500, 1800], 'line', [3]), row('administrative_expenses', 'Operating expenses', 'مصروفات التشغيل', [-1800, -1300]), row('depreciation', 'Depreciation expense', 'مصروف الإهلاك', [-400, -300], 'line', [5]), row('profit_before_tax', 'Profit before tax', 'الربح قبل الضريبة', [300, 200], 'subtotal'), row('income_tax', 'Income tax', 'ضريبة الدخل', [0, 0]), row('profit', 'Profit for the period', 'ربح الفترة', [300, 200], 'total'), row('oci_reclassifiable', 'OCI that may be reclassified', 'دخل شامل آخر يمكن إعادة تصنيفه', [0, 0]), row('oci_nonreclassifiable', 'OCI that will not be reclassified', 'دخل شامل آخر لا يعاد تصنيفه', [0, 0]), row('total_comprehensive_income', 'Total comprehensive income', 'إجمالي الدخل الشامل', [300, 200], 'total'),
    ] },
    { key: 'equity_current', titleEn: 'Changes in equity — current period', titleAr: 'التغيرات في حقوق الملكية — الفترة الحالية', columns: equityColumns.map(column => ({ ...column, startDate: configuration.periodStart, endDate: configuration.periodEnd })), rows: equityRows(false) },
    { key: 'equity_comparative', titleEn: 'Changes in equity — comparative period', titleAr: 'التغيرات في حقوق الملكية — الفترة المقارنة', columns: equityColumns.map(column => ({ ...column, startDate: configuration.comparativePeriodStart, endDate: configuration.comparativePeriodEnd })), rows: equityRows(true) },
    { key: 'cash_flow', titleEn: 'Statement of cash flows', titleAr: 'قائمة التدفقات النقدية', columns: periodColumns, rows: [row('opening', 'Opening cash and equivalents', 'النقد وما في حكمه أول الفترة', [800, 600]), row(`operating_receipts_${accounts[6].id}`, 'Receipts — rental revenue', 'مقبوضات — إيرادات التأجير', [1000, 800]), row(`operating_payments_${accounts[7].id}`, 'Payments — operating expenses', 'مدفوعات — مصروفات التشغيل', [-400, -350]), row('operating', 'Net cash from operating activities', 'صافي النقد من الأنشطة التشغيلية', [600, 450], 'subtotal'), row(`investing_payments_${accounts[1].id}`, 'Payments — rental vehicles', 'مدفوعات — سيارات التأجير', [-400, -300]), row('investing', 'Net cash used in investing activities', 'صافي النقد المستخدم في الأنشطة الاستثمارية', [-400, -300], 'subtotal'), row('financing', 'Net cash from financing activities', 'صافي النقد من الأنشطة التمويلية', [0, 0], 'subtotal'), row('exchange', 'Exchange effects on cash', 'أثر تغير سعر الصرف على النقد', [0, 0]), row('net_change', 'Net increase in cash', 'صافي الزيادة في النقد', [200, 150], 'total'), row('closing', 'Closing cash and equivalents', 'النقد وما في حكمه آخر الفترة', [1000, 750], 'total'), row('ledger_closing', 'Closing cash in ledger', 'الرصيد الختامي للنقد بالدفتر', [1000, 750], 'total'), row('difference', 'Cash reconciliation difference', 'فرق مطابقة النقد', [0, 0], 'reconciliation')] },
  ];
  if (stress) {
    statements[0].rows[1].labelEn = 'Property and equipment with detailed procurement and supporting document references. '.repeat(55);
    statements[0].rows[1].labelAr = 'الممتلكات والمعدات مع تفاصيل الشراء والمراجع والمستندات المؤيدة لكل أصل وتكلفته الدفترية. '.repeat(55);
    configuration.notes[4].text = 'Long synthetic asset note preserves all text across page boundaries. إيضاح تجريبي مطول للأصول مع حفظ جميع تفاصيل النص دون اقتطاع. '.repeat(110);
  }
  const position: ProfessionalBalanceSheet = { version: 1, company, asOfDate: configuration.periodEnd, comparisonDate: configuration.positionComparisonDate, generatedAt: '2026-09-18T09:00:00Z', accounts, current: totals(false), comparison: totals(true), checks: [], fingerprint, permissions: { canSave: true, canApprove: true } };
  return { version: 1, company, configuration, generatedAt: '2026-09-18T09:00:00Z', fingerprint, position, statements, findings: [], journals: [], permissions: { canSave: true, canApprove: true } };
}

export function makeSavedFinancialStatementPackageFixture(report = makeFinancialStatementPackageFixture(), status: SavedFinancialStatementPackage['status'] = 'draft'): SavedFinancialStatementPackage {
  return { id: '66666666-6666-4666-8666-666666666666', company_id: fixtureCompanyId, payload: structuredClone(report), source_fingerprint: report.fingerprint, status, created_by: fixturePreparerId, created_by_name: 'Synthetic Preparer', created_at: '2026-09-18T09:01:00Z', approved_by: status === 'approved' ? fixtureReviewerId : null, approved_by_name: status === 'approved' ? 'Synthetic Reviewer' : null, approved_at: status === 'approved' ? '2026-09-18T10:00:00Z' : null, review_notes: status === 'approved' ? 'Synthetic review for testing only, not a company approval.' : null, void_reason: status === 'voided' ? 'Synthetic cancelled version for testing.' : null };
}
